### ISSUE TITLE
PostgreSQL type REAL and DOUBLE PRECISION are not supported.

### ISSUE THREAD

**Issue by DanAmel** [taozhi8833998/node-sql-parser#1002]
**Describe the bug**
The type  **REAL** and  **DOUBLE PRECISION** ([TYPES](https://www.postgresql.org/docs/13/datatype-numeric.html))  are not supported  by node-sql-parser
I got a syntax error  when i call astify function.

> Expected "BIGINT", "BOOL", "BOOLEAN", "CHAR", "DATE", "DATETIME", "DECIMAL", "DOUBLE", "ENUM", "FLOAT", 
> "GEOMETRY", "INT", "INTEGER", "INTERVAL", "JSON", "JSONB", "LONGTEXT", "MEDIUMTEXT", "NUMERIC", "SERIAL", 
> "SMALLINT", "TEXT", "TIME", "TIMESTAMP", "TINYINT", "TINYTEXT", "UUID", or "VARCHAR" but "r" found.

**Database Engine**
PostgreSQL.

**To Reproduce**
-the SQL that be parsed

```
  SELECT (COALESCE(wp.weight,  0))::real as net_weight    FROM  wp ;
```

```
     SELECT (COALESCE(wp.weight,  0))::double precision as net_weight , wp.gross_weight:: double precision
     FROM  wp ;
```

-the node-sql-parser version
4.3.0

-the node version
v14.15.4

**Expected behavior**
Expected call to astify to parse the sql without error.

**Comment by taozhi8833998** [comment]
@DanAmel there is an empty space after `::`, I will try to fix it asap.

**Comment by chareice** [comment]
Seems it's not just a problem with spaces. For example, when I use this SQL statement 
```
const sql = `
CREATE TABLE test (
    amount double precision,
);
`;

const opt = {
  database: "Postgresql"
};
const { Parser } = require("node-sql-parser");
const parser = new Parser();
const ast = parser.astify(sql, opt);

console.log(JSON.stringify(ast, null, 2));
```
 and call astify, it also throws an error.

**Comment by taozhi8833998** [comment]
> Seems it's not just a problem with spaces. For example, when I use this SQL statement
> 
> ```
> const sql = `
> CREATE TABLE test (
>     amount double precision,
> );
> `;
> 
> const opt = {
>   database: "Postgresql"
> };
> const { Parser } = require("node-sql-parser");
> const parser = new Parser();
> const ast = parser.astify(sql, opt);
> 
> console.log(JSON.stringify(ast, null, 2));
> ```
> 
> and call astify, it also throws an error.

it's a different issue, please reopen another issue for it. 
BTW, does the tail comma after `precision` can cause an error in pg?
