### ISSUE TITLE
Include parsing of binary MySQL constants

### ISSUE THREAD

**Issue by Badestrand** [taozhi8833998/node-sql-parser#1024]
**Describe the bug**
The library doesn't yet parse binary constants in the form of 0x1234.

**Database Engine**
MySQL 8.0

**To Reproduce**
Example SQL:

 - `SELECT * FROM t1 where id=0x1ecc96ce15`
 - `SELECT * FROM t1 where id=x'1ecc96ce15`
 - `SELECT * FROM t1 where id=X'1ecc96ce15`

Node v14.15.0

node-sql-parser 4.3.0

**Expected behavior**
Should not generate an error.

**Comment by taozhi8833998** [comment]
[hexadecimal-literals](https://dev.mysql.com/doc/refman/8.0/en/hexadecimal-literals.html)

**Comment by taozhi8833998** [comment]
```sql
SELECT * FROM t1 where id=0x1ecc96ce15
SELECT * FROM t1 where id=x'1ecc96ce15'
SELECT * FROM t1 where id=X'1ecc96ce15'
```
