### ISSUE TITLE
backtick quoted table.column cause syntax error

### ISSUE THREAD

**Issue by ghostoy** [taozhi8833998/node-sql-parser#1045]
**Describe the bug**
`` `table`.`column` `` throws syntax error. This issue doesn't appear in version < 4.3.0.

**Database Engine**
MySQL

**To Reproduce**
- ``SELECT `sometable`.`id` FROM sometable``
- node-sql-parser version: 4.3.0
- Node.js version: v14.19.0

**Expected behavior**
should get passed by syntax check

**Screenshots**
na

**Additional context**
na

**Comment by taozhi8833998** [comment]
@ghostoy Sorry for the bug in latest version, I will fix it asap.

**Comment by taozhi8833998** [comment]
@ghostoy Please upgrade to the latest version`4.4.0`, try again.
