### ISSUE TITLE
TransactSQL Issue With Some Window Functions

### ISSUE THREAD

**Issue by sirosenf** [taozhi8833998/node-sql-parser#1058]
**Describe the bug**
Functions that could be used as aggregate or window functions throw error when used as window function. 

**Database Engine**
TransactSQL

**To Reproduce**
- ```select t.*,
  sum(order_rate) over(
    order by quarter_time
    rows between 4 preceding and 1 preceding -- window frame
  ) as new_sum from t 

Error Thrown:
> Expected \"#\", \",\", \"--\", \"/*\", \";\", \"FROM\", \"GO\", \"GROUP\", \"HAVING\", \"LIMIT\", \"ORDER\", \"UNION\", \"WHERE\", [ \\t\\n\\r], or end of input but \"(\" found.

- 4.3
- 18.0

**Expected behavior**
Generate properly formed AST. 

**Screenshots**
![image](https://user-images.githubusercontent.com/16842242/178069926-bdaba558-d52b-491d-97a5-76a3895a5c3d.png)

**Additional context**
I also tested with MIN and MAX window functions and got the same error.

TSQL Documentation: https://docs.microsoft.com/en-us/sql/t-sql/functions/aggregate-functions-transact-sql?view=sql-server-ver16
> The [OVER clause](https://docs.microsoft.com/en-us/sql/t-sql/queries/select-over-clause-transact-sql?view=sql-server-ver16) may follow all aggregate functions, except the STRING_AGG, GROUPING or GROUPING_ID functions.

**Comment by sirosenf** [comment]
Row_Number() window function works fine. I believe this is isolated to aggregate functions.

**Comment by taozhi8833998** [comment]
@sirosenf it has been fixed in the new release, please upgrade to the `4.4.0`.

**Comment by taozhi8833998** [comment]
so do the other issues #1057 , #1056 , #1055.
