### ISSUE TITLE
Support for Common Table Expressions

### ISSUE THREAD

**Issue by nicoabie** [taozhi8833998/node-sql-parser#1090]
**Describe the bug**
If I try to astify a CTE, the method fails

**Database Engine**
MySQL

**To Reproduce**
-the SQL that be parsed
WITH cte AS (SELECT id, ROW_NUMBER() OVER (PARTITION BY id, uid ORDER BY time DESC) rank FROM t) SELECT id FROM cte WHERE rank = 1
-the node-sql-parser version
4.4.0
-the node version
v16.14.2

**Expected behavior**
An AST representation of the provided SQL statement

**Comment by taozhi8833998** [comment]
@nicoabie `rank` is a reserved word in [MySQL(8.2)](https://dev.mysql.com/doc/refman/8.0/en/keywords.html), you could fix it quickly by renaming `rank` to any other nonreserved words in MySQL.

**Comment by nicoabie** [comment]
@taozhi8833998 you are so right!!! thanks!

One thing I noticed is that cte is not escaped.
Would that be an issue?

<img width="1552" alt="image" src="https://user-images.githubusercontent.com/2797992/183926906-8750b179-d3f5-473d-bd42-c781ff546290.png">

I'm closing this as it was an error on my end. Thanks again!

**Comment by taozhi8833998** [comment]
> @taozhi8833998 you are so right!!! thanks!
> 
> One thing I noticed is that cte is not escaped. Would that be an issue?
> 
> <img alt="image" width="1552" src="https://user-images.githubusercontent.com/2797992/183926906-8750b179-d3f5-473d-bd42-c781ff546290.png">
> 
> I'm closing this as it was an error on my end. Thanks again!

ok, that's an issue, I will add escape to the `cte` name later.

**Comment by taozhi8833998** [comment]
@nicoabie fixed the escape issue.

**Comment by nicoabie** [comment]
> @nicoabie fixed the escape issue.

thanks a lot for the support!
