### ISSUE TITLE
[MySQL]: Allow parentheses after `FROM` clause

### ISSUE THREAD

**Issue by OBannon37** [taozhi8833998/node-sql-parser#1097]
**Describe the bug**
MySQL's syntax allows parentheses after a `FROM` clause. However, `node-sql-parser`'s PEG.js grammar fails to parse parentheses after a FROM clause. Example below.

**Database Engine**
MySQL 8.0.28

**To Reproduce**
```js
import { Parser } from 'node-sql-parser';
const parser = new Parser();

const sql = `SELECT * FROM (user)`
const ast = parser.astify(sql);
```

**Expected behavior**
`sql` should be parsed into AST.

**Screenshots**
N/A

**Additional context**
The statement above should produce the same result for `ast` as the following (note the missing parantheses around `user`):

```js
import { Parser } from 'node-sql-parser';
const parser = new Parser();

const sql = `SELECT * FROM user`
const ast = parser.astify(sql);
```

**Comment by taozhi8833998** [comment]
@OBannon37 please review the above pr, if it's not as expected, please let me know. thank you for ur time, and pr again
