### ISSUE TITLE
Error parsing extract for bigquery

### ISSUE THREAD

**Issue by elshor** [taozhi8833998/node-sql-parser#1106]
**Describe the bug**
The parsing fails for extract date from timestamp
**Database Engine**
bigquery

**To Reproduce**
SELECT
  CONCAT('transaction ',transaction_id,' from ', 
  EXTRACT(date from TIMESTAMP_SECONDS(CAST(CAST(event_timestamp AS INT64)/1000000 AS INT64))))
FROM
  transactions

This sql was tested on bigquery and worked fine.
-the node-sql-parser version: 4.4.0
-the node version 14.20.0

see this link: https://runkit.com/elshor/runkit-npm-node-sql-parser

**Comment by taozhi8833998** [comment]
@elshor please upgrade to the `4.5.0` version, and try again.

**Comment by elshor** [comment]
works ok now
