### ISSUE TITLE
Bit Functions and Operators unsupport

### ISSUE THREAD

**Issue by LuoHaibin** [taozhi8833998/node-sql-parser#1118]
**Describe the bug**
Put any bit operations into the parser and it explodes
[12.13 Bit Functions and Operators](https://dev.mysql.com/doc/refman/8.0/en/bit-functions.html)

**Database Engine**
MySQL 8.0

**To Reproduce**
-the SQL that be parsed: SELECT 1 << 2;
-the node-sql-parser version: 4.4.0
-the node version: 12.4.0

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by taozhi8833998** [comment]
@LuoHaibin it has been supported, I will release a new version today. You can try it, thanks!

**Comment by taozhi8833998** [comment]
@LuoHaibin please try the `4.5.0` version.
