### ISSUE TITLE
TSQL: Incorrect bracket position when using fully qualified table name

### ISSUE THREAD

**Issue by woodenconsulting** [taozhi8833998/node-sql-parser#1123]
## Describe the bug
When using a fully qualified table name, the `sqlify` output incorrectly positions brackets which breaks the query.

## Database Engine
SQL Server 2017

## To Reproduce

**SQL Parser Version:** 4.5.0
**Node Version:** 16.15.0

**Input Example**
```
INSERT INTO source.dbo.movie (genre_id, title, release_date)
VALUES (@param1, @param2, @param3), (@param1, @param2, @param3);
```

**Output Example**
```
INSERT INTO [source.dbo].[movie] ([genre_id], [title], [release_date], [description])
VALUES (@param1, @param2, @param3), (@param1, @param2, @param3);
```

## Expected behavior
The query output should be as follows:
```
INSERT INTO [source].[dbo].[movie] ([genre_id], [title], [release_date], [description])
VALUES (@param1, @param2, @param3), (@param1, @param2, @param3);
```

On the AST side, it would be nice if the table object added a `schema` prop, e.g.:
```
{
  "db": "source",
  "schema": "dbo",
  "table": "movie",
  "as": null,
}
```

## Additional context
As an aside, it would also be nice if there was an option not to add new brackets, but rather preserve any that were in the original query.

**Comment by taozhi8833998** [comment]
@woodenconsulting fixed it.

**Comment by woodenconsulting** [comment]
@taozhi8833998 That was fast, thank you for the fix and your wonderful work on this project! The only callout I have is on the AST side. When there is a query that does not reference the db name, for example:
```sql
INSERT INTO dbo.movie (genre_id, title, release_date)
VALUES (@param1, @param2, @param3), (@param1, @param2, @param3);
```
The AST output for the table object is as follows:
```javascript
{
  db: 'dbo',
  table: 'movie',
  as: null
}
```
I can work around this, but it would be more accurate if the output was:
```javascript
{
  schema: 'dbo',
  table: 'movie',
  as: null
}
```
