### ISSUE TITLE
TSQL: Table hints break parser

### ISSUE THREAD

**Issue by woodenconsulting** [taozhi8833998/node-sql-parser#1124]
## Describe the bug
Table hints are currently breaking the parser; it's pretty common to add the `WITH (nolock)` table hint to optimize queries where appropriate.

## Database Engine
SQL Server 2017

## To Reproduce

**SQL Parser Version:** 4.5.0
**Node Version:** 16.15.0

**Input Example**
```
SELECT title FROM dbo.movie WITH (nolock)
WHERE release_date >= '01/01/2021';
```

**Output Error**
```
SyntaxError: Expected [A-Za-z0-9_] but " " found.
```

## Expected behavior
The query should successfully be parsed.

**Comment by taozhi8833998** [comment]
[table hint](https://docs.microsoft.com/en-us/sql/t-sql/queries/hints-transact-sql-table?view=sql-server-ver16)

**Comment by taozhi8833998** [comment]
@woodenconsulting please upgrade to the newer `4.5.1` version

**Comment by woodenconsulting** [comment]
@taozhi8833998 Works like a charm! Thank you 🙏
