### ISSUE TITLE
ReferenceError: global is not defined when using in browser installed via npm

### ISSUE THREAD

**Issue by valerii15298** [taozhi8833998/node-sql-parser#1128]
**Describe the bug**
ReferenceError: global is not defined when using in browser installed via npm

**Database Engine**
MySQL

**To Reproduce**
-install node-sql-parser via npm to react project created with vite
-run app via `npm run dev`

**Expected behavior**
App should not crash

**Additional context**
```ts
import { Parser } from "node-sql-parser";
const parser = new Parser();
```

**Comment by taozhi8833998** [comment]
@valerii15298 it looks like caused by [vite](https://github.com/vitejs/vite/issues/2618), you can import `<script>window.global = window;</script>` to your index.html as a work around, and I will try to fix it in vite at the same time.

**Comment by JulienLecoq** [comment]
I had a similar issue with Angular, ``<script>window.global = window;</script>`` solved it. Thanks!
