### ISSUE TITLE
Error when importing types from a specific database engine in TypeScript

### ISSUE THREAD

**Issue by poulinjulien** [taozhi8833998/node-sql-parser#1145]
**Describe the bug**
When using TypeScript, it is no longer possible to import a specific engine (in my case, Flink).

**Database Engine**
I do not think this problem is related to a specific database engine.

**To Reproduce**
- in a TypeScript project, import types from a specific database engine;
  ```ts
  import { AST, Dual, From, Parser, Select, Column } from 'node-sql-parser/build/flinksql';
  ```
  produces the following error:
  ```
  TS2305: Module '"node-sql-parser/build/flinksql"' has no exported member 'AST'.
  ```
- the node-sql-parser version: 4.5.1
- the node version: v12.16.1

**Expected behavior**
The types should be imported properly.

**Screenshots**

![image](https://user-images.githubusercontent.com/1919739/193911744-bd62d52c-7faf-43b3-ac21-dce218b85262.png)

**Additional context**
I *think* it is related to commit https://github.com/taozhi8833998/node-sql-parser/commit/9de356b6d491a537474bebcd71cff516a7226ea7.  
Manually changing `build/flinksql.d.ts` to `export * from '../types';` fixes the issue.

**Comment by taozhi8833998** [comment]
@poulinjulien You're right! I will fix it today.
