### ISSUE TITLE
Problems with MySQL AND/OR/XOR operators

### ISSUE THREAD

**Issue by nene** [taozhi8833998/node-sql-parser#1154]
Some operators are not supported, others have often wrong precedence.

#### XOR operator is not supported

```sql
SELECT (true XOR false); --> results in parse error
```

#### AND / OR operators break precedence rules or even crash the parser

This SQL produces incorrect syntax tree, where `AND` does not precedence over `OR`:

```sql
SELECT (true OR false AND true);
```

```json
      {
        "type": "binary_expr",
        "operator": "AND",
        "left": {
          "type": "binary_expr",
          "operator": "OR",
          "left": {
            "type": "bool",
            "value": true
          },
          "right": {
            "type": "bool",
            "value": false
          }
        },
        "right": {
          "type": "bool",
          "value": true
        }
```

The same happens with `&&` and `||` operators.

Interestingly when I remove the parentheses, the parser crashes:
```sql
SELECT true OR false AND true; --> crash!
```

More interestingly, when I replace true/false with comparsion expressions, the parsing works:

```sql
SELECT x>3 or x<9 AND x=3;
```
producing the following syntax tree, which correctly has `AND` with higher precedence than `OR`:
```json
      {
        "type": "binary_expr",
        "operator": "OR",
        "left": {
          "type": "binary_expr",
          "operator": ">",
          "left": {
            "type": "column_ref",
            "table": null,
            "column": "x"
          },
          "right": {
            "type": "number",
            "value": 3
          }
        },
        "right": {
          "type": "binary_expr",
          "operator": "AND",
          "left": {
            "type": "binary_expr",
            "operator": "<",
            "left": {
              "type": "column_ref",
              "table": null,
              "column": "x"
            },
            "right": {
              "type": "number",
              "value": 9
            }
          },
          "right": {
            "type": "binary_expr",
            "operator": "=",
            "left": {
              "type": "column_ref",
              "table": null,
              "column": "x"
            },
            "right": {
              "type": "number",
              "value": 3
            }
          }
        }
```

But when I replace `AND`/`OR` with `&&`/`||` the parser crashes:

```sql
SELECT x>3 || x<9 && x=3; --> crash!
```

**Comment by nene** [comment]
I think you misunderstood what I meant by **operator precedence**. 

Previously the following SQL:

```sql
SELECT true OR false AND true OR false
```

was parsed as if it were parenthesized as follows:

```sql
SELECT ((true OR false) AND true) OR false
```

Now, after the "fix", this gets parsed as if it were:

```sql
SELECT true OR (false AND (true OR false))
```

That is, you have changed AND and OR operators from being left-associative to being right-associative (which is incorrect - AND/OR operators, are left-associative).

But the operators still have the same precedence. This means, AND operator should bind more tightly than OR operator. The correct parsing should be:

```sql
SELECT (true OR (false AND true)) OR false
```

So, as a result of this "fix", the parsing of AND/OR operators is even more incorrect than it was before (previously at last the left-associativity was correct).

**Comment by nene** [comment]
I should also point out that `||` and `&&` logical operators seem to be supported in all dialects, but in fact only MySQL and MariaDB support these.

In most other dialects `||` is a string concatenation operator, and in PostgreSQL the `&&` operator does something altogether different.

Funnily enough the code even contains a line:

```
OPERATOR_CONCATENATION = '||'
```

**Comment by taozhi8833998** [comment]
> ```sql
> ```sql
> SELECT ((true OR false) AND true) OR false
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
> ```

**Comment by taozhi8833998** [comment]
> I think you misunderstood what I meant by **operator precedence**.
> 
> Previously the following SQL:
> 
> ```sql
> SELECT true OR false AND true OR false
> ```
> 
> was parsed as if it were parenthesized as follows:
> 
> ```sql
> SELECT ((true OR false) AND true) OR false
> ```
> 
> Now, after the "fix", this gets parsed as if it were:
> 
> ```sql
> SELECT true OR (false AND (true OR false))
> ```
> 
> That is, you have changed AND and OR operators from being left-associative to being right-associative (which is incorrect - AND/OR operators are left-associative).
> 
> But the operators still have the same precedence. This means, AND operator should bind more tightly than OR operator. The correct parsing should be:
> 
> ```sql
> SELECT (true OR (false AND true)) OR false
> ```
> 
> or to only highlight the precedence of operators:
> 
> ```sql
> SELECT true OR (false AND true) OR false
> ```
> 
> So, as a result of this "fix", the parsing of AND/OR operators is even more incorrect than it was before (previously at last the left-associativity was correct).

Sorry for that, I know what you are pointing out now. I will try to fix it.

**Comment by taozhi8833998** [comment]
> I should also point out that `||` and `&&` logical operators seem to be supported in all dialects, but in fact only MySQL and MariaDB support these.
> 
> In most other dialects `||` is a string concatenation operator, and in PostgreSQL the `&&` operator does something altogether different.
> 
> Funnily enough the code even contains a line:
> 
> ```
> OPERATOR_CONCATENATION = '||'
> ```

Please open a new issue for it, thanks.
