### ISSUE TITLE
 hive create table Full syntax is not supported

### ISSUE THREAD

**Issue by wseven10** [taozhi8833998/node-sql-parser#1177]
**Describe the bug**
 hive create table Full syntax is not supported

**Database Engine**
Hive

**To Reproduce**
-the SQL that be parsed
-the node-sql-parser version
-the node version

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by taozhi8833998** [comment]
@wseven10 Please give more info by following the issue template.
