### ISSUE TITLE
Support for INSERT...SELECT statements

### ISSUE THREAD

**Issue by JesseCastro** [taozhi8833998/node-sql-parser#118]
INSERT...SELECT statements are fairly common in MySQL and other SQL dialects.  https://dev.mysql.com/doc/refman/8.0/en/insert-select.html

Currently when you submit an insert statement with a select as the values, the parser will throw an error.  E.g.
```
let query = 'INSERT INTO foo (col_a, col_b) SELECT col_a, col_b FROM bar;
let ast = parser.astify(query);
```
This issue is an enhancement request to include this grammar in the parser.

**Comment by taozhi8833998** [comment]
supported in `1.6.7` version, try it

**Comment by JesseCastro** [comment]
Works, thanks!
