### ISSUE TITLE
Support type cast in postgresql

### ISSUE THREAD

**Issue by jingsam** [taozhi8833998/node-sql-parser#119]
@taozhi8833998 thanks for your great work. Recently I am on a project that send sql to the server. Your library helps me to avoid sql injection and enable gran permission control.

Currently I notice the library not support `CAST( expr as typename )` or `expr::typename` syntax. Could you consider to support it?

http://www.postgresqltutorial.com/postgresql-cast/

**Comment by taozhi8833998** [comment]
working on this feature now...

**Comment by taozhi8833998** [comment]
published in `1.6.7` version, support simple cast grammer

```javascript
const { Parser } = require("node-sql-parser");
const parser = new Parser();
const grammar = "select col::CHAR from tableName";
const opt = {
  database: 'postgresql'
}
const ast = parser.astify(grammar, opt);
const sql = parser.sqlify(ast); // SELECT `col`::CHAR FROM `t`
```

**Comment by jingsam** [comment]
👍

**Comment by jingsam** [comment]
Note that `expr::typename` is postgresql only syntax, but `CAST( expr as typename )` is ANSI standard. What ever, thank you for your great work!

**Comment by taozhi8833998** [comment]
same as I know and what I do, you could use `CAST` in mysql too, but `::` for pg only
