### ISSUE TITLE
BigQuery: parse fails on "extract(year from ...)"

### ISSUE THREAD

**Issue by joffreyvillard** [taozhi8833998/node-sql-parser#1192]
**Describe the bug**
 The parser fails on the query below, while being valid:

```sql
select extract(year from current_date())
```

The raised error (actual location redacted for readability):

```
ReferenceError: f is not defined
   at /--/node_modules/node-sql-parser/index.js:1:90458
    at /--/node_modules/node-sql-parser/index.js:1:90495
    at /--/node_modules/node-sql-parser/index.js:1:90786
    at Qo (/--/node_modules/node-sql-parser/index.js:1:92377)
    at /--/node_modules/node-sql-parser/index.js:1:78546
    at $o (/--/node_modules/node-sql-parser/index.js:1:78830)
    at co (/--/node_modules/node-sql-parser/index.js:1:63280)
    at fo (/--/node_modules/node-sql-parser/index.js:1:64323)
    at lo (/--/node_modules/node-sql-parser/index.js:1:62977)
    at io (/--/node_modules/node-sql-parser/index.js:1:62835)
```

**Database Engine**
BigQuery

**To Reproduce**
-the SQL that be parsed: see above
-the node-sql-parser version: 4.5.1
-the node version: 14.15.5

**Expected behavior**
 No error, and the appropriate properties being filled up in the AST.

**Comment by gibraltariq** [comment]
Same issue in PostgreSQL btw. Hopefully your fix catches it :)

**Comment by taozhi8833998** [comment]
> Same issue in PostgreSQL btw. Hopefully your fix catches it :)

ok, got it

**Comment by taozhi8833998** [comment]
@joffreyvillard some closed issues about bigquery database have been fixed in the latest version `4.6.0`, you can upgrade to it and try again, the left issues, which are still open will be fixed asap. Thanks for ur patience.

**Comment by joffreyvillard** [comment]
Thanks for the update (and the fixes!)

**Comment by gibraltariq** [comment]
Thanks @taozhi8833998 ! One small issue remains though. A query like this still fails

`EXTRACT (MONTH FROM timestamp) as month`

this should not fail b/c in bigquery you can extract from any valid timestamp column no matter what the column name is. For example:

`EXTRACT (MONTH FROM coconuts) as month`

as long as coconuts is of type timestamp column.

**Comment by taozhi8833998** [comment]
> Thanks @taozhi8833998 ! One small issue remains though. A query like this still fails
> 
> `EXTRACT (MONTH FROM timestamp) as month`
> 
> this should not fail b/c in bigquery you can extract from any valid timestamp column no matter what the column name is. For example:
> 
> `EXTRACT (MONTH FROM coconuts) as month`
> 
> as long as coconuts is of type timestamp column.

@gibraltariq Sorry for that, it has been fixed.

**Comment by gibraltariq** [comment]
You're so fast at responses, thank you! If there are any further issues will let you know.
