### ISSUE TITLE
Logical operators not supported in column expressions

### ISSUE THREAD

**Issue by vincenzon** [taozhi8833998/node-sql-parser#1196]
This query:

```
select true or false
```

fails to parse for postgresql but it is valid in Postgres. This fails as well:

```
select true and false
```

It appears to be the logical operator, as this fails as well: 

```
select c1 or c2
```

**Comment by taozhi8833998** [comment]
@vincenzon it has been fixed by pr #1160, I will publish a new version this week.

**Comment by taozhi8833998** [comment]
same with #1154

**Comment by vincenzon** [comment]
Awesome! Sorry I missed that.

**Comment by taozhi8833998** [comment]
> Awesome! Sorry I missed that.

never mind.
