### ISSUE TITLE
Mysql / Mariadb INSERT SET syntax not supported

### ISSUE THREAD

**Issue by vincenzon** [taozhi8833998/node-sql-parser#1197]
Both Mysql and Mariadb support a SET form for INSERT:

https://dev.mysql.com/doc/refman/8.0/en/insert.html

This does not seem to currently be supported as this query gives parse errors: 

```
insert t1 set c1 = 1
```

**Comment by taozhi8833998** [comment]
@vincenzon the two issues created by you have been fixed in the new version `4.6.0`, please upgrade to the latest version, and try it, thanks.
