### ISSUE TITLE
[bigquery] cannot use left and right functions

### ISSUE THREAD

**Issue by elshor** [taozhi8833998/node-sql-parser#1201]
**Describe the bug**
cannot use left and right functions
**Database Engine**
bigquery
**To Reproduce**
SELECT right('xx',3)
-the node-sql-parser version

-the node version

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by taozhi8833998** [comment]
@elshor I have published a new version `4.6.0`, the issues you created have been fixed in the new version, please upgrade to it, and try again. Thanks.
