### ISSUE TITLE
Parser errors out when parsing embedded queries.

### ISSUE THREAD

**Issue by rogozind** [taozhi8833998/node-sql-parser#1220]
**Describe the bug**
Parser cannot parse embedded queries.

**Database Engine**
Mysql

**To Reproduce**
-the SQL that be parsed
-the node-sql-parser version
-the node version

**Expected behavior**
select
  (SELECT  group_concat(v SEPARATOR ', ' )
   FROM category_table WHERE category = 3)
AS category
FROM fssa_esg_issues
group by id

<img width="587" alt="image" src="https://user-images.githubusercontent.com/10505245/205366478-b4cfe560-19d6-430d-adf3-0a5b5e33db32.png">

**Comment by camoonke** [comment]
I have the same problem. 
sql case: select GROUP_CONCAT(DISTINCT abc order by abc SEPARATOR ';') as abc from business_table

**Comment by taozhi8833998** [comment]
@camoonke it's not the same issue. The module doesn't parse the `SEPARATOR ';'` currently, so `select GROUP_CONCAT(DISTINCT abc order by abc) as abc from business_table` would be parsed successfully. You can open another issue for that, thx.

**Comment by camoonke** [comment]
> @camoonke it's not the same issue. The module doesn't parse the `SEPARATOR ';'` currently, so `select GROUP_CONCAT(DISTINCT abc order by abc) as abc from business_table` would be parsed successfully. You can open another issue for that, thx.

thx. i have open a new issue [issue1234](https://github.com/taozhi8833998/node-sql-parser/issues/1234)
