### ISSUE TITLE
why export * from "../types"?

### ISSUE THREAD

**Issue by xdewx** [taozhi8833998/node-sql-parser#1227]
**Describe the bug**
It seems that it should be `export * from "./types"`

**Database Engine**
which database engine does your SQL running on? such as MySQL, PostgreSQL.

**To Reproduce**
-the SQL that be parsed
-the node-sql-parser version
-the node version

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by taozhi8833998** [comment]
@xdewx please upgrade to the `4.6.1`

**Comment by xdewx** [comment]
> @xdewx please upgrade to the `4.6.1`

It seems that `node_modules/node-sql-parser/index.d.ts` still is `export * from ../types`
