### ISSUE TITLE
Double quotes problem with PostgreSQL parser and SyntaxError with PostgresQL data types.

### ISSUE THREAD

**Issue by yurii-buhaichuk** [taozhi8833998/node-sql-parser#1236]
Hi!
Thanks for your work, it's very useful package for our project.

I had some problems while using this package.

**BUG 1**. When using the `columnList` method with a query that contains double quotes, it does not find any of the columns that were used in the query. Same problems with `tableList`.

**To Reproduce**
SQL query: `SELECT "Id" FROM "Test";`
node-sql-parser version: `4.6.2`
the node version: `16.18.1`

**Database Engine**
PostgresQL

**Expected behavior**

Example code: ![image](https://user-images.githubusercontent.com/118465408/207629721-752daec2-0185-45da-94e6-93fdfc38d6c1.png)

Results: 
![image](https://user-images.githubusercontent.com/118465408/207629389-0432febe-5900-4fb2-914a-9f93e0ed55bf.png)

**BUG 2**. When parsing queries, the parser does not know many Postgres types. For example: `BIGSERIAL`, `SMALLSERIAL`, `REAL`.

**To Reproduce**
SQL query: `create table if not exists "users" (
  "id" bigserial,
  "name" varchar(128) not null,
  "second_name" varchar(128) default null
);`
node-sql-parser version: `4.6.2`
the node version: `16.18.1`

**Database Engine**
PostgresQL

**Expected behavior**

Expected: success parsing

Actual: 
![image](https://user-images.githubusercontent.com/118465408/207632410-a71ac0f6-7954-4ddb-885e-dc7991c114ec.png)
![image](https://user-images.githubusercontent.com/118465408/207632534-84caf6f9-7b6a-4f21-8276-23800c38d579.png)

**BUG 3**. Syntax error on parsing delete query.

**To Reproduce**
SQL query: `DELETE FROM users WHERE id = 2;`
node-sql-parser version: `4.6.2`
the node version: `16.18.1`

**Database Engine**
PostgresQL

**Expected behavior**

Expected: success parsing

Actual: 
![image](https://user-images.githubusercontent.com/118465408/207647848-7e0d2583-77de-469d-9468-db3d822e1b05.png)

**Comment by taozhi8833998** [comment]
@yurii-buhaichuk the bugs have been fixed in the new version `4.6.4`, try it.
