### ISSUE TITLE
`boolean`, `autoincrement`, other standard table definitions fail to parse in sqlite

### ISSUE THREAD

**Issue by Joeb3219** [taozhi8833998/node-sql-parser#1288]
**Describe the bug**
Given the input: 
```sql
CREATE TABLE `foobar1` (`id` integer not null primary key autoincrement, `name` varchar(255), `batch` boolean, `migration_time` datetime)
```

the parser will yield errors for both `autoincrement` and `boolean`, despite them being valid. 

I've also encountered issues with create table statements from sqlite's analyze, e.g.
 ```sql
CREATE TABLE sqlite_stat4(tbl,idx,neq,nlt,ndlt,sample)
```
since there are no type definitions.

**Database Engine**
SQLite

**To Reproduce**
-the SQL that be parsed: 
```sql
CREATE TABLE `foobar1` (`id` integer not null primary key autoincrement, `name` varchar(255), `batch` boolean, `migration_time` datetime)
```
-the node-sql-parser version: 4.6.4
-the node version: v18.9.0

**Expected behavior**
Should be able to successfully parse table definitions that are auto-generated by SQLite + handle autoincrement and booleans.

**Screenshots**

**Additional context**

**Comment by Joeb3219** [comment]
I can potentially help fix these issues, but will need some time to dive into the codebase.

**Comment by taozhi8833998** [comment]
@Joeb3219 Thank you for that. I will fix it tomorrow. You can review the pr to get a better understanding of my mess codes. hhh

**Comment by taozhi8833998** [comment]
@Joeb3219 the first issue that failed to parse the `autoincrement ` and `boolean` has been fixed locally. try the next one.

**Comment by taozhi8833998** [comment]
@Joeb3219 the two issues have been fixed, I will add test cases and open pr tomorrow.

**Comment by Joeb3219** [comment]
Thanks you! I look forward to reviewing. As an aside, I have been looking for a good type-safe SQL parser, and yours is perhaps the best out there. I was mid writing my own, which I was dreading 😭

**Comment by taozhi8833998** [comment]
@Joeb3219 feel free to review the above pr, thank you.
