### ISSUE TITLE
Didn't support WEEK unit for date in mysql

### ISSUE THREAD

**Issue by Mini256** [taozhi8833998/node-sql-parser#1295]
**Describe the bug**

Didn't support WEEK unit for date.

**Database Engine**

MySQL

**To Reproduce**
- the SQL that be parsed

```sql
SELECT
  COUNT(*) AS issues_closed_per_week
FROM
  github_events ge
WHERE
  ge.type = 'IssuesEvent'
  AND ge.action = 'closed'
  AND ge.repo_id = (
    SELECT
      repo_id
    FROM
      github_repos
    WHERE
      repo_name = 'vuejs/vue'
    LIMIT
      1
  )
  AND ge.created_at >= DATE_SUB(NOW(), INTERVAL 1 WEEK)
  AND ge.created_at < NOW()
```

Expected "!=", "#", "%", "&", "&&", "", "+", "-", "--", "/", "/", "<", "<<", "<=", "<>", "=", ">", ">=", ">>", "BETWEEN", "DAY", "HOUR", "IN", "IS", "LIKE", "MINUTE", "MONTH", "NOT", "REGEXP", "RLIKE", "SECOND", "YEAR", "^", "div", "|", "||", "~", or [ \t\n\r] but "W" found.

- the node-sql-parser version

4.6.4

- the node version

v16.16.0

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by Mini256** [comment]
@taozhi8833998 Hi, I would like to ask if this project has a plan to release a minor version recently.

**Comment by taozhi8833998** [comment]
@Mini256 I will release a new minor version tomorrow. Thanks for ur pr.

**Comment by taozhi8833998** [comment]
@Mini256 the latest version `4.6.5`  has been released.

**Comment by Mini256** [comment]
@taozhi8833998 Thanks a lot! 🎉
