### ISSUE TITLE
got SyntaxError when table named "table"

### ISSUE THREAD

**Issue by TheresaQWQ** [taozhi8833998/node-sql-parser#1297]
**Describe the bug**
got SyntaxError when table named "table"
such as `select * from table`

**Database Engine**
mysql, sqlite, mariadb (maybe others db engine also have the same problem)

**To Reproduce**
- the SQL that be parsed: `select * from table`
- the node-sql-parser version: node-sql-parser@4.6.4
- the node version: v19.2.0

**Expected behavior**
```
{
  with: null,
  type: 'select',
  options: null,
  distinct: null,
  columns: '*',
  into: { position: null },
  from: [ { db: null, table: 'table', as: null } ],
  where: null,
  groupby: null,
  having: null,
  orderby: null,
  limit: null,
  locking_read: null,
  window: null
}
```

**Screenshots**
![image](https://user-images.githubusercontent.com/22370654/217523958-34cde9a6-e8b3-4db6-afb9-13d96991119d.png)

**Additional context**
No further information is available

**Comment by nene** [comment]
I should point out that this is invalid syntax in at least MySQL, SQLite and PostgreSQL. Didn't test with MariaDB. You should quote such a table name, as `table` is a reserved keyword in most SQL dialects:

```sql
-- in MySQL
SELECT * FROM `table`
-- in PostgreSQL
SELECT * FROM "table"
```

**Comment by taozhi8833998** [comment]
@TheresaQWQ the reason has been pointed out as above by @nene, please check it.
