### ISSUE TITLE
Postgresql - some bugs with returning

### ISSUE THREAD

**Issue by onutosora** [taozhi8833998/node-sql-parser#1307]
**Describe the bug**
Subquery, naming fields, and fields after "*" leads to an error.

**Database Engine**
PostgreSQL.

**To Reproduce**
The node-sql-parser version: 4.6.5
The node version: 16.19.0

**SQLs:**

Query: "UPDATE buildings SET address = 'update test 2' WHERE id = 18 RETURNING *, address;"
Error:   "Expected "--", "/*", ";", [ \t\n\r], or end of input but "," found."
Maybe senselessly, but it should work.

Query: "UPDATE buildings SET address = 'update test 2' WHERE id = 18 RETURNING address as newAddress;"
Error:   "Expected ",", "--", "->", "->>", ".", "/*", ";", or [ \t\n\r] but "a" found."

Query: "UPDATE buildings SET address = 'update test 2' WHERE id = 18 RETURNING *,
    (SELECT address FROM buildings WHERE id = 18) as old_address;"
Error:   "Expected "'", "*", "--", "/*", "E", "\"", "`", [ \t\n\r], or [A-Za-z_] but "(" found."

**Comment by taozhi8833998** [comment]
@onutosora the comma after the `RETURNING` keyword is required or not? what's the difference between `RETURNING , address` and `RETURNING address;`

**Comment by onutosora** [comment]
Sorry, I made a typo. I meant "RETURNING *, address;"
