### ISSUE TITLE
Didn't support INTERSECT keyword in MySQL

### ISSUE THREAD

**Issue by Mini256** [taozhi8833998/node-sql-parser#1309]
**Describe the bug**

Didn't support INTERSECT keyword in MySQL

Related issue: https://github.com/pingcap/ossinsight/issues/1297

**Database Engine**

MySQL

**To Reproduce**

- the SQL that be parsed

```sql
SELECT
  *
FROM
  (
    SELECT
      1
  ) INTERSECT
SELECT
  *
FROM
  (
    SELECT
      2
  )
```

Expected "#", ",", "--", "/*", ";", "FOR", "FULL", "GO", "GROUP", "HAVING", "INNER", "INTO", "JOIN", "LEFT", "LIMIT", "LOCK", "ORDER", "RIGHT", "UNION", "WHERE", "WINDOW", [ \t\n\r], or end of input but "S" found.

- the node-sql-parser version

4.6.5

- the node version

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by taozhi8833998** [comment]
@Mini256 the issue has been fixed. I will open a pr later.

**Comment by Mini256** [comment]
@taozhi8833998 Maybe we should find an automated method to help us find the syntax difference between node-sql-parser and mysql parser.
