### ISSUE TITLE
Parser fails to parse CREATE TABLE index with specified length

### ISSUE THREAD

**Issue by VanTanev** [taozhi8833998/node-sql-parser#1312]
**Describe the bug**
Indexes can optionally specify the length of the column to be considered. The parser fails to parse CREATE TABLE statements with such indexes

**Database Engine**
MySQL 8.0

**To Reproduce**
 - the SQL that be parsed
```sql
CREATE TABLE `Translation` (
  `id` char(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `en-GB` text,
  PRIMARY KEY (`id`),
  KEY `Translation_en-GB_btree_idx` (`en-GB`(768)),
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
```
 - the node-sql-parser version
```
4.6.5
```
 - the node version
```
v18.13.0
```
**Expected behavior**
The above SQL should parse

**Actual behavior**
```
[SyntaxError]: Expected "#", ")", ",", "--", "/*", "ASC", "DESC", or [ \t\n\r] but "(" found.
```

**Comment by taozhi8833998** [comment]
@VanTanev fixed it, I will open a pr later.

**Comment by VanTanev** [comment]
Thank you!
