### ISSUE TITLE
[bigquery] parameters should be denoted by @

### ISSUE THREAD

**Issue by elshor** [taozhi8833998/node-sql-parser#1340]
**Describe the bug**
In current implementation, parameters are denoted by a preceding :, they should be denoted by a '@' symbol. 
Since this would be a breaking change, I suggest supporting both options

**Database Engine**
bigquery

**To Reproduce**
select a from x where a > @param
**Expected behavior**
should parse

**Screenshots**

**Additional context**

**Comment by taozhi8833998** [comment]
@elshor it has been fixed in the latest version, please upgrade the module. thanks.

**Comment by elshor** [comment]
My bad. I checked against the wrong version. Thanks
