### ISSUE TITLE
[bigquery] should support accessing records

### ISSUE THREAD

**Issue by elshor** [taozhi8833998/node-sql-parser#1358]
**Describe the bug**
when accessing record types, the syntax should be like object path:
```
select a.b.c.d.e.f from a
```
however, the parser treats it as schema and then columns with . in it
```
{
  type: 'column_ref',
  schema: 'a',
  table: 'b',
  column: 'c.d.e.f'
}
```
The correct handling might be a bit tricky because it requires to determine that a is a table base on the context. Ideally, record types should be treated differently.
**Database Engine**
bigquery

**Comment by nene** [comment]
There are two fundamental problems here:

- There can never be a reference to schema in SELECT-clause. I don't know of any SQL dialect which allows this, definitely not BigQuery.
- To determine whether `a` refers to a table or column one would need to create a list of all the tables referenced by FROM-clause. Such analysis is IMHO better done after parsing.

In [my own little parser](https://github.com/nene/sql-parser-cst) I parse above `a.b.c.d.e.f` expression into the following structure which is agnostic regarding the specific meaning of identifier `a`:

```js
{
  type: "member_expr",
  object: {
    type: "member_expr",
    object: {
      type: "member_expr",
      object: {
        type: "member_expr",
        object: {
          type: "member_expr",
          object: { type: "identifier", name: "a" },
          property: { type: "identifier", name: "b" },
        },
        property: { type: "identifier", name: "c" },
      },
      property: { type: "identifier", name: "d" },
    },
    property: { type: "identifier", name: "e" },
  },
  property: { type: "identifier", name: "f" },
}
```
