### ISSUE TITLE
Make Node SQL Parser Web Worker Compatible

### ISSUE THREAD

**Issue by troygibb** [taozhi8833998/node-sql-parser#1382]
**Describe the bug**
Node SQL Parser isn't currently web worker compatible.  The fix should be to rely on `globalThis` [here](https://github.com/taozhi8833998/node-sql-parser/blob/master/index.js). See [the MDN docs here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/globalThis#description) for more on when/why to use `globalThis`. TL;DR is it's cross platform compatible! 

**Database Engine**
N/A

**To Reproduce**
Instantiate the node-sql-parser library in a web worker.

Unfortunately this isn't super trivial, I have a repro attempt here but it's not currently working: https://github.com/troygibb/node-sql-parser-bug.

**Expected behavior**
Should work within a web worker-- there aren't any browser main-thread apis this library should really depend on.

**Comment by taozhi8833998** [comment]
@troygibb Sorry for the delay, the latest `node-sql-parser`  module version works in web-worker now. You can try it in ur repository.

![image](https://github.com/taozhi8833998/node-sql-parser/assets/7252180/e64d21aa-9e7a-4847-9fbb-d14809d4ef34)
