### ISSUE TITLE
[bigquery]not preserving double parenthesis

### ISSUE THREAD

**Issue by elshor** [taozhi8833998/node-sql-parser#1410]
**Describe the bug**
Given the following SQL:
```
SELECT COUNT(( SELECT x))
```
When passing it through astify and then sqlify, it does not preserve the double parenthesis. The output is
```
SELECT COUNT(SELECT x)
```
This is a problem because in bigquery, select statement that are function arguments need to be wrapped with additional parenthesis
**Database Engine**
bigquery
**To Reproduce**

```javascript
var nodeSqlParser = require("node-sql-parser")
const parser = new nodeSqlParser.Parser();
x = parser.astify(`
SELECT COUNT(( SELECT x))
`,{database:'bigquery'})
parser.sqlify(x, {database:'bigquery'})
```
**Expected behavior**

**Screenshots**

**Additional context**

**Comment by taozhi8833998** [comment]
@elshor Please upgrade to version `4.7.0`, and try again.
