### ISSUE TITLE
Subqueries not supported?

### ISSUE THREAD

**Issue by jlmgtech** [taozhi8833998/node-sql-parser#1430]
Subqueries don't seem to be supported (at least in the mysql grammar).
Not a big deal, because you can achieve the effect using joins, but it might be fairly straightforward to implement. Let me know if you plan on supporting subqueries and if you would like me to PR a possible implementation.
BTW, great lib!  I've been enjoying using it!

**To Reproduce**
"SELECT * FROM users WHERE name IN (SELECT name FROM people);"
-the node-sql-parser version: 1.0.4
-the node version: 16.16.0

**Expected behavior**
Should receive a syntax tree where the right hand side of the IN expression is another `select` type.

**Additional Context**
The grammar for mysql that deals with `in_op` would need to support having a select_stmt on the right hand side:
https://github.com/taozhi8833998/node-sql-parser/blob/master/pegjs/mysql.pegjs#LL2554C1-L2554C1
^ notice that `expr_list` does not support having a select statement

```
/home/james/programming/node/sqlmock/node_modules/node-sqlparser/lib/parse.js:9000
    throw peg$buildStructuredError(
    ^
peg$SyntaxError: Expected "(" or WHITE_SPACE but "`" found.
    at peg$buildStructuredError (/home/james/programming/node/sqlmock/node_modules/node-sqlparser/lib/parse.js:999:12)
    at peg$parse (/home/james/programming/node/sqlmock/node_modules/node-sqlparser/lib/parse.js:9000:11)
    at Object.<anonymous> (/home/james/programming/node/sqlmock/index.js:477:17)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47 {
  expected: [
    { type: 'other', description: 'WHITE_SPACE' },
    { type: 'literal', text: '(', ignoreCase: false }
  ],
  found: '`',
  location: {
    start: { offset: 48, line: 1, column: 49 },
    end: { offset: 49, line: 1, column: 50 }
  }
}
```

**Comment by jlmgtech** [comment]
I forgot to put this here:
https://dev.mysql.com/doc/refman/8.0/en/subqueries.html

**Comment by taozhi8833998** [comment]
@jlmgtech Please upgrade the node-sql-parser module version to `4.6.6`, and try again, it works in the latest version.

**Comment by taozhi8833998** [comment]
```javascript
const { Parser } = require('node-sql-parser/build/mysql');
const parser = new Parser();
const sql = 'SELECT * FROM users WHERE name IN (SELECT name FROM people);'
const ast = parser.astify(sql, { database: 'mysql'})
console.log(parser.sqlify(ast, { database: 'mysql'}))

```

**Comment by jlmgtech** [comment]
Alright that definitely fixed it. Thank you!
