### ISSUE TITLE
`astify` doesn't throw the `SyntaxError` exception on invalid sql syntax

### ISSUE THREAD

**Issue by corocoto** [taozhi8833998/node-sql-parser#1441]
**Describe the bug**
I'm trying to create AST by using invalid MySQL request via `astify` method. I'm wait that the method thows the `SyntaxError` exception, but it doesn't.

**Database Engine**
MySQL

**To Reproduce**
- Code snippet:

```js
import { Parser } from 'node-sql-parser/build/mysql';

try {
  const parser = new Parser();
  const astified = parser.astify('select\nselect * from test_table', { database: 'MySQL' });
} catch (error) {
 // Do something with an error
}
```

- the SQL that be parsed: 
```sql
select
select * from test_table
```
- the node-sql-parser version: 4.7.0
- the node version: 16.14.2

**Expected behavior**
Should throw the `SyntaxError` exception from `astify` method

**Comment by corocoto** [comment]
@taozhi8833998, thanks a lot for fixing the bug. Would you release new version of the package?

**Comment by taozhi8833998** [comment]
> @taozhi8833998, thanks a lot for fixing the bug. Would you release new version of the package?

The `4.8.0` version will be released this week.

**Comment by corocoto** [comment]
@taozhi8833998, cool! Thanks
