### ISSUE TITLE
Presto / Trino Support on the roadmap?

### ISSUE THREAD

**Issue by npmccauslin** [taozhi8833998/node-sql-parser#1457]
Would be great to see Presto / Trino support for some projects I'm working on, let me know if this is on the roadmap for supported dbs.

**Comment by darzIdo** [comment]
@taozhi8833998 We've started working on some Trino related features, and noticed you added this to the 5.0.0 milestone. Do you have anything you started with? We can help developing this if you want

**Comment by taozhi8833998** [comment]
@darzIdo It looks like you have added trino in the #1680

**Comment by darzIdo** [comment]
@taozhi8833998 you're right, but it's actually just a copy of snowflake, as we saw this is the closest dialect. We took a sample of 2000~ queries and tried to parse them - snowflake was the one with the lowest amount of errors

**Comment by taozhi8833998** [comment]
@darzIdo ok, we can build the trino parser based on the snowflake together, you can show the failed test cases here.

**Comment by darzIdo** [comment]
@taozhi8833998 I've updated our PR with some modification to the trino dialect to support what we encountered.
The biggest issue we're currently facing is [lambda expressions](https://trino.io/docs/current/functions/lambda.html) which have no currecnt representation in other dialects.  This means that there's a new type of entity to be added, which is something we feel you'd might want to set the tone for.

Your opinion?

**Comment by taozhi8833998** [comment]
@darzIdo ok， thanks for your hard work. I will try to add lambda expressions to trino dialect.

**Comment by taozhi8833998** [comment]
@darzIdo  I have added lambda expressions in the trino dialect, I will push the codes later.

**Comment by jordanfowler** [comment]
+1 @taozhi8833998 What's the status on this? If you'd like any help, I'm happy to pitch in.

**Comment by taozhi8833998** [comment]
@jordanfowler Thanks for your help, you can try `5.0.0` the latest version, which support Trino now.

**Comment by npmccauslin** [comment]
Hi, I just got around to trying this out and I don't think the `*-*-*-*-*` is valid trino syntax but it doesn't error, instead it reports an error at the `t('today')` part:
```SELECT *
FROM table
WHERE u BETWEEN * - * - * - * - * t('today')
LIMIT 10

If I'm missing something let me know, otherwise I'd be happy to help with future testing.

**Comment by taozhi8833998** [comment]
> Hi, I just got around to trying this out and I don't think the `*-*-*-*-*` is valid trino syntax but it doesn't error, instead it reports an error at the `t('today')` part:
> 
> ```
> FROM table
> WHERE u BETWEEN * - * - * - * - * t('today')
> LIMIT 10
> ```
> 
> It also still seem unable to handle brackets in queries.
> 
> If I'm missing something let me know, otherwise I'd be happy to help with future testing.

@npmccauslin Please open a new issue for that. Thank you.

**Comment by taozhi8833998** [comment]
what does this mean `It also still seem unable to handle brackets in queries.`. I think it works
```sql
FROM tableName
WHERE u BETWEEN t('today') and t('tommorrow')
LIMIT 10
```

**Comment by npmccauslin** [comment]
Of course: https://github.com/taozhi8833998/node-sql-parser/issues/1935

Let me dig up a good example query for the brackets problem 👍
