### ISSUE TITLE
Postgres joined table syntax not supported

### ISSUE THREAD

**Issue by vincenzon** [taozhi8833998/node-sql-parser#1459]
Postgres joined table syntax ([see 7.2.1.1 here](https://www.postgresql.org/docs/current/queries-table-expressions.html)) gives an error.

For example,

```
select last_name, salary 
from (
   employees inner join salaries on employees.emp_no = salaries.emp_no
);
```

**Comment by vincenzon** [comment]
It's a different construct. Maybe I made the example too simple, here is where the parenthesis matter:

```
select last_name, salary, title
from employees e left join (
    salaries s inner join titles t on s.emp_no = t.emp_no
) on e.emp_no = s.emp_no
```

**Comment by taozhi8833998** [comment]
ok, so it is a construct for a temp table.
