### ISSUE TITLE
[TSQL] ALTER VIEW Support

### ISSUE THREAD

**Issue by esetnik** [taozhi8833998/node-sql-parser#1465]
**Describe the bug**
ALTER VIEW is not supported by the parser

**Database Engine**
sql server

**To Reproduce**
-the SQL that be parsed
```sql
ALTER VIEW [dbo].[reporting_class]
AS
SELECT
  [ClassHexID]
  [DepartmentID] AS class_source
FROM [Class]
WHERE [Class].[active] = 1
```
-the node-sql-parser version v4.3.0
-the node version 18.16.1

**Expected behavior**
No error

**Screenshots**
<img width="712" alt="image" src="https://github.com/taozhi8833998/node-sql-parser/assets/664434/b8b13180-971b-4982-90bd-18728e8a81ed">

**Additional context**
https://learn.microsoft.com/en-us/sql/t-sql/statements/alter-view-transact-sql?view=sql-server-ver16

**Comment by taozhi8833998** [comment]
@esetnik please upgrade to `4.8.0`, sorry for the lately released.
