### ISSUE TITLE
[Postgres] (ALTER/CREATE/DROP) SCHEMA support

### ISSUE THREAD

**Issue by athewsey** [taozhi8833998/node-sql-parser#1471]
**Describe the bug**

ALTER SCHEMA seems not supported by the parser, and as far as I can tell the `CREATE` & `DROP` commands aren't supported either.

**Database Engine**

PostgreSQL

**To Reproduce**

SQL as per the [Pagila sample schema loading script](https://github.com/devrimgunduz/pagila/blob/fef9675714cfba1756df4719b5e36075a7ddf90e/pagila-schema.sql#L26):

```sql
ALTER SCHEMA public OWNER TO postgres;
```

node-sql-parser version 4.7.0

node version 18.15

**Expected behavior**

No parsing error, supported statement as per the [postgres docs here](https://www.postgresql.org/docs/current/sql-alterschema.html).

**Additional context**

I was hoping to use node-sql-parser to parse this whole file, but seems like there might be too many gaps...

**Comment by taozhi8833998** [comment]
The following SQL syntanx should be supported
- alter schema / domain / type / function / aggregate
- create domain / type / function / sequence / aggregate/view / trigger
- revoke / grant
