### ISSUE TITLE
Is it possible to get/use this as Apache 2.0 licensed , as we want to use this in our project which is Apache 2.0 licensed

### ISSUE THREAD

**Issue by oasisk** [taozhi8833998/node-sql-parser#1481]
**Describe the bug**
Looks like the license was changed to  GPLv2 to be compatible to flora sql parser license(https://github.com/taozhi8833998/node-sql-parser/commit/7f570cac0be72ce289b8f29bbc503be3ea75b039) 

I don't see flora sql parser being used in project. We want to use node-sql-parser in our project which is Apache 2.0 licensed , is it possible to get/use this as Apache 2.0 licensed?

**Comment by taozhi8833998** [comment]
@oasisk emm, this project is hugely different from the flora sql parser, I will change to the appropriate license later.

**Comment by taozhi8833998** [comment]
@oasisk The license has been changed to Apache 2.0,  I will publish a new version `4.8.0` this week, you can use it in your project.

**Comment by taozhi8833998** [comment]
@oasisk `4.8.0` has been released, it's Apache 2.0 license that you can use in your business project.
