### ISSUE TITLE
allow floats to terminate at .

### ISSUE THREAD

**Issue by pdhorn** [taozhi8833998/node-sql-parser#1485]
**Describe the bug**
Floats must have digits after the decimal point, despite being valid SQLite or MySQL syntax.

node-sql-parser cannot parse statements such as `select count(*)*1. from ...` since it expects `[0-9]`.  See for example, this runkit https://runkit.com/embed/qaf7ujk3uj0v

**Database Engine**
SQLite and MySQL

**To Reproduce**
-the SQL that be parsed: `SELECT *, a*1., b FROM t`
-the node-sql-parser version: 4.7.0
-the node version: 18

**Expected behavior**
node-sql-parser can parse/astify/digest floats such as `1.` as well as `1` and `1.0`

**Screenshots**
na

**Additional context**
I successfully ran sqlite queries and mysql queries such as `select count(*)*1. from tbl` in MySQL 5.7 and https://sqliteonline.com/, so I believe it's valid syntax

**Comment by taozhi8833998** [comment]
@pdhorn fixed in the `4.8.0` version, please upgrade it and try again
