### ISSUE TITLE
Operation "On Conflict" cannot be parsed 

### ISSUE THREAD

**Issue by MIC-BO** [taozhi8833998/node-sql-parser#1486]
**Describe the bug**
A query that contains "on conflict" cannot be parsed.

**Database Engine**
PostgreSQL.

**To Reproduce**
-the SQL that be parsed

insert into table1 (id, firstname, lastname, email) 
            values ($id, $firstname, $lastname, $email)
            on conflict (id)
            do
               update set 
                   firstname = $firstname, 
                   lastname = $lastname, 
                   email = $email,
                   updatedon = CURRENT_TIMESTAMP
                   RETURNING *

-the node-sql-parser version
4.7.0
-the node version
14.19.0
**Expected behavior**
The query should be parsed satisfactorily.

**Screenshots**

**Additional context**

**Comment by taozhi8833998** [comment]
[insert syntax](https://www.postgresql.org/docs/current/sql-insert.html)
