### ISSUE TITLE
Error parsing sql with misformated html contents

### ISSUE THREAD

**Issue by pidgeonman** [taozhi8833998/node-sql-parser#149]
Using node-sql-parser version 1.6.10.

I'm trying to parse SQL with some badly formatted HTML. The actual content was much larger, but I tracked it down to this sequence:

INSERT INTO `mytablehere` (`ID`, `post_author`, `post_date`, `post_date_gmt`, `post_content`, `post_title`, `post_excerpt`, `post_status`, `comment_status`, `ping_status`, `post_password`) VALUES (2564,1,'2018-06-28 21:37:58','2018-06-24 19:37:58','I haven\'t <a href=\"http://www.someurl.com/somepartofurl\0\">figured</a>',0,'revision','',0);

As you can see, at the end of the URL there's a `\0`, which I believe should be `/0`. The combination with the `\'t` before breaks the parser, throwing this error: 

`UnhandledPromiseRejectionWarning: SyntaxError: Expected "'", "\\'", "\\/", "\\\"", "\\\\", "\\b", "\\f", "\\n", "\\r", "\\t", "\\u", or [^'\\\0-\x1F\x7F] but "\\" found.`

I think the parser shouldn't care about this. This SQL code was generated using mysqldump.

**Comment by pidgeonman** [comment]
Here it is raw, because GH's formatter replaces the backticks as code blocks: https://pastebin.com/S71QBiW3

**Comment by taozhi8833998** [comment]
supported in `1.6.11` version, try it

**Comment by pidgeonman** [comment]
It works. Thanks!
