### ISSUE TITLE
allow brackets for databases, schemas and tables in T-SQL

### ISSUE THREAD

**Issue by SebastianBehrens** [taozhi8833998/node-sql-parser#1493]
Although `SELECT col1, col2 FROM [10db].[schema].[table]` is correct SQL, the characters after the [ get tagged with the following error: "Expected "#", "$", "'", "(", ..........., or [A-Za-z_] but "[" found."

Would it be difficult to add those brackets to the regex in the parsers?

[This](https://github.com/taozhi8833998/node-sql-parser/issues/174) issue seems related.

**Comment by taozhi8833998** [comment]
@SebastianBehrens what's the version of the `node-sql-parser` module you are using? it had been fixed already. [Example codes](https://runkit.com/636d9fb4da573500088dbcc9/64b203142220d8000862270d), it works.

**Comment by SebastianBehrens** [comment]
I am on 4.7.0, but I still get the issue.
![image](https://github.com/taozhi8833998/node-sql-parser/assets/51058351/f8eac503-7f06-466b-a0c0-ac5e25f18eca)
![image](https://github.com/taozhi8833998/node-sql-parser/assets/51058351/df49e1d1-6711-43e0-b5d7-434c4ca2bb4d)

**Comment by taozhi8833998** [comment]
@SebastianBehrens please show me the full code, you should specify the database to `transactsql` by the options

```javascript
const { Parser } = require('node-sql-parser');
const parser = new Parser();
const sql = 'SELECT distinct t.col1, t.col2 FROM [10db].[schema].[table] t'
const ast = parser.astify(sql, {database: 'transactsql'})
console.log(ast)
console.log(parser.sqlify(ast, {databse: 'transactsql'}))

```
You will get the above error, if you do not specify the database, that is `mysql` by default.

**Comment by labs20** [comment]
Hi!

Having kinda same problem here, but field related:

````
select tipo, '12023' as 'Janeiro/2023', [120232] as 'EXTERNAL_FIELD'
            FROM (
               
               select 'Realizado' tipo, 'Teste' '12023', 'DESIRED_VALUE' [120232]
                 FROM docs
                -- where doc_id = '1'
            
            ) as x
````

The field `EXTERNAL_FIELD` was expected to have `DESIRED_VALUE`, but it has `120232` as value, because the parse are removing the brackets from `[120232]` fields.

Using `{ database: 'transactsql' }`;

Any help?

Thanks!

**Comment by taozhi8833998** [comment]
> Hi!
> 
> Having kinda same problem here, but field related:
> 
> ```
> select tipo, '12023' as 'Janeiro/2023', [120232] as 'EXTERNAL_FIELD'
>             FROM (
>                
>                select 'Realizado' tipo, 'Teste' '12023', 'DESIRED_VALUE' [120232]
>                  FROM docs
>                 -- where doc_id = '1'
>             
>             ) as x
> ```
> 
> The field `EXTERNAL_FIELD` was expected to have `DESIRED_VALUE`, but it has `120232` as value, because the parse are removing the brackets from `[120232]` fields.
> 
> Using `{ database: 'transactsql' }`;
> 
> Any help?
> 
> Thanks!

Sorry I don't understand ur issue, you can open a new one for it, and describe the error you got, Thanks for that.

**Comment by SebastianBehrens** [comment]
@taozhi8833998 Sorry, for the delay, now I'm back.
How do I specify the database when using node-sql-parser within [coc-sql](https://github.com/fannheyward/coc-sql)?

**Comment by taozhi8833998** [comment]
@SebastianBehrens Read the above codes, or readme.

**Comment by SebastianBehrens** [comment]
That fixed it. Thank you so much!
