### ISSUE TITLE
SQL with CONVERT against SEC_TO_TIME is not parsed correctly

### ISSUE THREAD

**Issue by kei-katahira** [taozhi8833998/node-sql-parser#1500]
**Describe the bug**
I wrote SQL to convert the result of the SEC_TO_TIME function to type TIME in the CONVERT function, but TIME is treated as a column and escaped by backslash.

**Database Engine**
MySQL

**To Reproduce**
-the SQL that be parsed
SELECT CONVERT(SEC_TO_TIME(2378), TIME);
→ SELECT CONVERT(SEC_TO_TIME(2378), \`TIME\`);
-the node-sql-parser version
4.8.0
-the node version
16.20.0

**Expected behavior**
The CONVERT function argument, TIME, should be treated as an argument, not a column.

**Screenshots**

**Additional context**
Error messages when parsed SQL is executed in MySQL.
```
ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '`TIME`) at line 1
```

**Comment by taozhi8833998** [comment]
@kei-katahira fixed it.
