### ISSUE TITLE
MySQL astify syntaxError on constraints

### ISSUE THREAD

**Issue by TonyGravagno** [taozhi8833998/node-sql-parser#1501]
v4.8.0 **and prior** : This SQL results in an error from `astify` string.

```sql
  `last_modified_time` timestamp(4) NOT NULL DEFAULT '1970-01-01 00:00:00' ON UPDATE current_timestamp(4),
```

Common Error:

> s [SyntaxError]: Expected "#", ")", ",", "--", "/*", "AS", "AUTO_INCREMENT", "CHARACTER", "CHECK", "COLLATE", "COLUMN_FORMAT", "COMMENT", "CONSTRAINT", "DEFAULT", "GENERATED", "KEY", "NOT NULL", "NULL", "ON", "PRIMARY", "REFERENCES", "STORAGE", "UNIQUE", or [ \t\n\r] 
but "(" found.
> ...
>  expected: [
>    {
>    }
> found: '(',
>  location: {
>    start: { offset: 783, line: 15, column: 108 },
>    end: { offset: 784, line: 15, column: 109 }
>  }

The detail that it doesn't like is the default timestamp value. This field does not result in an error:

```sql
`created_time` timestamp(4) NOT NULL DEFAULT current_timestamp(4),
```

The error location>start (column 108), when the default value is present, is the open parenthesis of `current_timestamp(` , not the quoted default value. The problem in `astify` might not be that it doesn't recognize the default value, but that the cursor is broken when the default is present.

The timestamp may or may not include the decimal precision: '00:00:00.0000'. Interestingly, even if that precision is not present in the original CREATE TABLE or ALTER TABLE, the SHOW TABLE command may include ".0000" anyway. So the `astify` parsing should ignore that detail.

**Comment by taozhi8833998** [comment]
@TonyGravagno fixed it, will work in the `4.9.0` version.
