### ISSUE TITLE
[TSQL] ADD CHECK CONSTRAINT "OR"

### ISSUE THREAD

**Issue by esetnik** [taozhi8833998/node-sql-parser#1502]
**Describe the bug**

**Database Engine**
MSSQL

**To Reproduce**
-the SQL that be parsed
```
ALTER TABLE [Class]
ADD CONSTRAINT [chk_quizId_or_QuizLink]
CHECK (
    ([quizId] IS NOT NULL AND [QuizLink] IS NULL) OR
    ([quizId] IS NULL AND [QuizLink] IS NOT NULL)
);
```

-the node-sql-parser version: v4.8.0
-the node version: v18.16

**Expected behavior**
No error, this is valid TSQL

**Screenshots**
<img width="1089" alt="image" src="https://github.com/taozhi8833998/node-sql-parser/assets/664434/610590e9-8ab9-4a29-bca6-ed5c2856a49e">

**Additional context**
[Add any other context about the problem here.
](https://learn.microsoft.com/en-us/sql/relational-databases/tables/create-check-constraints?view=sql-server-ver16)

**Comment by taozhi8833998** [comment]
@esetnik fixed in the future version `4.9.0`, which I will publish recently.
