### ISSUE TITLE
Old version in npm.pkg.github.com registry

### ISSUE THREAD

**Issue by TonyGravagno** [taozhi8833998/node-sql-parser#1505]
The README shows:

> From [GitHub Package Registry](https://npm.pkg.github.com/)
> npm install @taozhi8833998/node-sql-parser --registry=https://npm.pkg.github.com/

The version of node-sql-parser that comes from there is 2.2.0.

I was hoping that you have a Git process to upload the latest compiled build from the master branch to this registry. 😉

**Comment by taozhi8833998** [comment]
@TonyGravagno ok, I will update it with the latest version this week.

**Comment by taozhi8833998** [comment]
@TonyGravagno integrated with GitHub action, the new version will be published to GPR automatically when a new release is created.
