### ISSUE TITLE
Extremely slow parse of nested function calls (Postgres)

### ISSUE THREAD

**Issue by vincenzon** [taozhi8833998/node-sql-parser#1508]
The following query takes 50 seconds to parse. I have stripped it down to the essentials: deeply nested function calls with an embedded select call over many columns. This sort of construct is not artificial, it arose in our work from queries that build json objects from various select calls. If instead of postgres, I specify mysql, it parses in about 100ms. 

```
SELECT
    f(f(f(
                SELECT 
                    f(
                        f(
                            f(c1,c2,c3,c4,c5,c6,c7,c8,c9)
                        )
                    ) 
                FROM t2
            
    ))) as cf
FROM t1
```

**Comment by taozhi8833998** [comment]
same with #658

**Comment by taozhi8833998** [comment]
@vincenzon fixed the issue. it will take about 250ms to parse the above nested function calls SQL in pg.

**Comment by vincenzon** [comment]
Awesome! Thanks.

**Comment by taozhi8833998** [comment]
@vincenzon  try the latest version `4.9.0`.
