### ISSUE TITLE
Support hive sql parser

### ISSUE THREAD

**Issue by Nabufaces** [taozhi8833998/node-sql-parser#151]
node-sql-parser will support hive sql parser?

**Comment by taozhi8833998** [comment]
if you need it, I will try my best. Show me the hive SQL you want to be parsed

**Comment by Nabufaces** [comment]
such like `SELECT DISTINCT user_id FROM TABLE` or `INSERT OVERWRITE`

**Comment by taozhi8833998** [comment]
It looks like basically same as MySQL, I will add it in next version

**Comment by Nabufaces** [comment]
yes，select is very similar to mysql, insert is not

**Comment by Nabufaces** [comment]
Thank you very much

**Comment by taozhi8833998** [comment]
working on it now, I will publish new version tommorrow

**Comment by Nabufaces** [comment]
Hi, is there any progress on hive parser?

**Comment by taozhi8833998** [comment]
yeah, the last check for that, I will push my code in one hour

**Comment by Nabufaces** [comment]
Looking forward

**Comment by taozhi8833998** [comment]
`1.6.13` version has been published, that support simple hive SQL, you can try it. if more hive grammar is required, please let me know.

```javascript
const Parser = require('node-sql-parser')
const parser = new Parser()
const sql = 'INSERT overwrite table account select col_a, col_b from t2'
const ast = parser.astify(sql, { database: 'hive' })
const backSQL = parser.sqlify(ast) //  INSERT OVERWRITE TABLE `account` SELECT `col_a`, `col_b` FROM `t2`
```

**Comment by Nabufaces** [comment]
It looks like `INSERT INTO TABLE VALUES (1, 'c')` parse error

**Comment by taozhi8833998** [comment]
> INSERT INTO TABLE VALUES (1, 'c')

there is no table name ???  is that correct?.  ` INSERT INTO TABLE tableName VALUES (1, 'c')` is valid

**Comment by Nabufaces** [comment]
`INSERT INTO tableName VALUES (1, 'c')`

**Comment by taozhi8833998** [comment]
ok, I got it, wait for a moment

**Comment by taozhi8833998** [comment]
fixed in `1.6.14` version

**Comment by Nabufaces** [comment]
Add `alter` and `PARTITION` support, such like:
1. `ALTER TABLE oldTable RENAME TO newtable`
2. insert overwrite table tmp1 PARTITION (partitionkey='2008-08-15') select * from tmp

**Comment by taozhi8833998** [comment]
got it, the first feature has been supported, the second one is under developing

**Comment by taozhi8833998** [comment]
try `1.6.15` version
