### ISSUE TITLE
Brackets being removed from field declaration

### ISSUE THREAD

**Issue by labs20** [taozhi8833998/node-sql-parser#1510]
Hi, fisrt of all, kudos for your work and dedication. 

You are always quick and nice to provide feedback. Appreciate it! Thanks!

My case is, I have a very large SQL on SQL Server and I have to use brackets around some fields to achieve some results. 

As the query itself is quite large and bound to my own tables, I have a simplified example below that can illustrate the problem.

````
SELECT tipo, [120232] AS 'INTERNAL_FIELD'
   FROM (
               
        SELECT 'Realizado' AS tipo,  'DESIRED_VALUE' AS [120232]
        FROM docs                -- <<  Replace docs with any table of yours
        --WHERE doc_id = '1'
            
) AS result
````

If you take this SQL and run it on SQL Server you will see that it results 2 fields as expected, with the the field `INTERNAL_FIELD` showing the expected value of `DESIRED_VALUE`, but if you run it trough the parser and then execute it on Node, it will have  `120232` as value instead, because the parser is removing the brackets from all `[120232]` fields, thus making it an int value aliased as 'INTERNAL_FIELD' instead of a link between outer and inner selects.

Im using `{ database: 'transactsql' }` on parser options, by the way.

What is needed here, I suppose, is that the parser do not remove those fields brackets.

Any help?

Thanks!

**Comment by taozhi8833998** [comment]
@labs20 I have run a [test case](https://runkit.com/636d9fb4da573500088dbcc9/64c36d1603b1b200086a4c46) online, please help me check it. what you want are the brackets that should be reserved in the ast json?  Because I think the sqlify result is right, which have brackets.

**Comment by labs20** [comment]
Really sorry for spend your time. The error it's on my side. I have an internal `__astObjToString` function that do the `sqlify`, and later on on that function I do a regex and that regex is cleaning up the brackets. 

There is nothing wrong on your side, I was overlooking this internal function and assuming that the parser went wrong. Sorry about that.

Thank you!
