### ISSUE TITLE
LOCK TABLES / UNLOCK TABLES

### ISSUE THREAD

**Issue by fdsis** [taozhi8833998/node-sql-parser#152]
Hi, 
thank you very much for your work.
I would like to use your library but currently the `LOCK TABLES 'things' WRITE;` and `UNLOCK TABLES;` statements are not working. So an automated process of reading and writing a data-only-sql-dump is impossible. 

The SQL is MariaDB and the error occurred in an file with `LOCK TABLES 'things' WRITE;`, `INSERT INTO things...` and `UNLOCK TABLES;` statements.

**Comment by taozhi8833998** [comment]
working on it...

**Comment by taozhi8833998** [comment]
fixed in `1.6.12` version, try it

**Comment by fdsis** [comment]
Working great. Thanks alot!
