### ISSUE TITLE
unable parser nested subqueries

### ISSUE THREAD

**Issue by xuybin** [taozhi8833998/node-sql-parser#1521]
**Describe the bug**
unable parser nested subqueries

**Database Engine**
MySQL

**To Reproduce**
-the SQL that be parsed：select t.a,(select ( select POW(1 + 3, 2) from dual) from dual) from db.t
-the node-sql-parser version：4.9.0
-the node version:18.17.0

**Expected behavior**
```
import { default as MySQLParser49 } from "https://esm.sh/v130/node-sql-parser@4.9.0/umd/mysql.umd.js";
const parser49 = new MySQLParser49.Parser();
parser49.parse(`select t.a,(select ( select POW(1 + 3, 2) from dual) from dual) from db.t`)
// parser a ast
```
**Screenshots**
![image](https://github.com/taozhi8833998/node-sql-parser/assets/10354549/493a0063-18cf-4f99-bdeb-5111cce8bb9a)

**Additional context**
4.7.0 ok
4.8.0 error
4.9.0 error

**Comment by taozhi8833998** [comment]
@xuybin imported by the pr #1442, sorry for that. It has been fixed now.
