### ISSUE TITLE
ILIKE doesn't appear to be supported

### ISSUE THREAD

**Issue by invisibled** [taozhi8833998/node-sql-parser#1534]
**Describe the bug**
When queries include the ILIKE operator, the parser generates a syntax error. #424 says this was fixed but It's not working in my conditions. 

**Database Engine**
PostgreSQL

**To Reproduce**
- SELECT * FROM table where name ILIKE '%foo%'
- node-sql-parser v4.9.0
- node v16.14.0

**Expected behavior**
The above should parse

**Additional context**
Instead the parser throws a SyntaxError. It seems like ILIKE isn't in this list

SyntaxError: Expected "!=", "#", "%", "&", "&&", "(", "*", "+", ",", "-", "--", "->", "->>", ".", "/", "/*", ";", "<", "<<", "<=", "<>", "=", ">", ">=", ">>", "AND", "BETWEEN", "FOR", "GO", "GROUP", "HAVING", "IN", "INTERSECT", "INTO", "IS", "LIKE", "LIMIT", "LOCK", "MINUS", "NOT", "OR", "ORDER", "REGEXP", "RLIKE", "UNION", "WINDOW", "XOR", "^", "div", "|", "||", "~", [ \t\n\r], or end of input but "I" found.]

**Comment by invisibled** [comment]
My mistake, once the database is defined, it works. `const ast = parser.astify(query, { database: 'PostgresQL' })`.

**Comment by taozhi8833998** [comment]
@invisibled I will add the usage to README to make it simple and clear.
