### ISSUE TITLE
[Question] Why make the implicit sort order explicit?

### ISSUE THREAD

**Issue by takaaa220** [taozhi8833998/node-sql-parser#1540]
(Sorry but this issue is not a bug report and is just a question.)

Why make the implicit sort order explicit? 
For example, if do astify and then sqlify, sort direction is added.

```javascript
const ast = parser.astify('SELECT a FROM t order by id');
const output = parser.sqlify(ast); // 'SELECT `a` FROM `t` ORDER BY `id` ASC'
```

---

The motivation of this question:
I am building a linter for sql (it is just a hobby) by using this great library.
And now, I am trying to build the same rule as [this](https://docs.sqlfluff.com/en/stable/rules.html#ambiguous-ordering-directions-for-columns-in-order-by-clause) but it is difficult to build it because of this behavior.

**Comment by taozhi8833998** [comment]
ascending order is the default sort direction, add it explicitly to make the SQL more readable and understandable. Do you mean that if the sqlify function adds the sort order explicitly to the original SQL, it makes you could not determine whether the SQL is anti-pattern or best practice?

**Comment by takaaa220** [comment]
I'm sorry I didn't make it clear enough. (I realized my question was not accurate.)

I mean the result of astify already has the sort order direction like below even if sort direction is not specifie and it makes implementation of verification on linter difficult. 
```json
   ...
   "orderby": [
      {
        "expr": {
          "type": "column_ref",
          "table": null,
          "column": "a"
        },
        "type": "ASC" ← this
      }
    ],
    ...
```

**Comment by taozhi8833998** [comment]
@takaaa220 ok, I will try to remove the default asc sort type.

**Comment by taozhi8833998** [comment]
@takaaa220 remove the default sort type in ast, it will be `null` now if the sort type is not defined.
