### ISSUE TITLE
Support for json query in Postgres

### ISSUE THREAD

**Issue by adrafiq** [taozhi8833998/node-sql-parser#156]
Does the library support json manipulation syntax for postgresql ? 
Specifically this query throws syntax error.
SELECT id, 
config, 
busy, 
'templateId', 
active, 
domain 
FROM instances WHERE  config ->> 'email' = 'email@provider.com'

**Comment by taozhi8833998** [comment]
got it, I will support it as soon as possible

**Comment by taozhi8833998** [comment]
try `1.6.16` version

**Comment by taozhi8833998** [comment]
close for inactive
