### ISSUE TITLE
不支持SELECT MAX(date) AS datanew FROM table 这种语法的解析吗

### ISSUE THREAD

**Issue by TZonly** [taozhi8833998/node-sql-parser#1566]
**Describe the bug**

**Database Engine**
which database engine does your SQL running on? such as MySQL, PostgreSQL.

**To Reproduce**
-the SQL that be parsed
-the node-sql-parser version
-the node version

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by taozhi8833998** [comment]
@TZonly  please do not use `table` as the table name, since it's a keyword.  the below SQL is valid: 

```sql
SELECT MAX(date) AS datanew FROM tableName
```

**Comment by TZonly** [comment]
Thank you, it's really possible

**Comment by taozhi8833998** [comment]
> Thank you, it's really possible

If it's possible to use `table` as table name, then you must escape it. following SQL is valid also:

```sql

SELECT MAX(date) AS datanew FROM `table`

```

**Comment by taozhi8833998** [comment]
> > Thank you, it's really possible
> 
> If it's possible to use `table` as table name, then you must escape it. following SQL is valid also:
> 
> ```sql
> SELECT MAX(date) AS datanew FROM `table`
> ```

You cannot execute SQL `SELECT MAX(date) AS datanew FROM table` since it's an invalid SQL.
