### ISSUE TITLE
Cannot parse sql with UNIQUE INDEX or PRIMARY KEY including ASC/DESC option.

### ISSUE THREAD

**Issue by jinzhubaofu** [taozhi8833998/node-sql-parser#1571]
**Describe the bug**

**Database Engine**
MySQL

**To Reproduce**
-the SQL that be parsed
```sql
CREATE TABLE foo (
  id INTEGER NOT NULL AUTO_INCREMENT,
  c1 INT,
  UNIQUE INDEX idx1 (c1 ASC),
  PRIMARY KEY (id ASC)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci
```
-the node-sql-parser version
4.10.0
-the node version
v18.17.0

**Expected behavior**
should not throw error.

**Screenshots**
error screenshot
![image](https://github.com/taozhi8833998/node-sql-parser/assets/811195/69c0fa1c-e10e-4c10-ad3f-08a92e5486dc)

**Additional context**

1. remove `UNIQUE` and just a normal `INDEX` goes well;
2. remove ASC from primary key and it will work.

![image](https://github.com/taozhi8833998/node-sql-parser/assets/811195/55cf3072-8e84-4e37-8e8f-b86d52a716ca)

**Comment by jinzhubaofu** [comment]
@taozhi8833998 Hi, I noticed that the fix be published within milestone 4.11.0. Could you please confirm the exact release date for 4.11.0?

**Comment by taozhi8833998** [comment]
@jinzhubaofu I will release it on Sep 22 according to the milestone.

**Comment by jinzhubaofu** [comment]
@taozhi8833998 I get it. That would be great! Thank you!
