### ISSUE TITLE
Parsing SHOW TABLES query results in error sometimes

### ISSUE THREAD

**Issue by liuliu-dev** [taozhi8833998/node-sql-parser#1577]
**Describe the bug**
Before I bumped t0 4.10.0, we used to always get the error parsing `SHOW TABLES`, now it sometimes parses correctly but sometimes will throw error.

**Database Engine**
which database engine does your SQL running on? such as MySQL, PostgreSQL.
MySQL

**To Reproduce**
-the SQL that be parsed
-the node-sql-parser version: ^4.10.0
-the node version

```
console.error
    query: SHOW TABLES
    error: SyntaxError: Expected "#", "--", "/*", ":=", "=", "BINARY", "BINLOG", "CHARACTER", "COLLATION", "COLUMNS", "CREATE", "FUNCTION", "GRANTS", "INDEXES", "MASTER", "PROCEDURE", "PROCESSLIST", "STATUS", "TRIGGERS", or [ \t\n\r] but "T" found.
```

**Comment by taozhi8833998** [comment]
@liuliu-dev Sorry for that, I will try to find it asap.

**Comment by taozhi8833998** [comment]
@liuliu-dev In my bad test case, I got the error message, which include `TABLES` keyword, while not in your error message.

<img width="950" alt="image" src="https://github.com/taozhi8833998/node-sql-parser/assets/7252180/c00d60fd-3055-4677-bcbd-b3f6c1c17e0b">

I am not sure whether you have the latest `node-sql-parser` version installed only. Can you provide any reappear env for me to check it in more detail?

Thanks.

**Comment by liuliu-dev** [comment]
Thanks for the quick response! I have 4.10.0 installed.

I created a code sandbox if that helps.
https://codesandbox.io/s/dry-silence-y4srts?file=/src/index.tsx

But as I said, this is a bit flaky, sometimes the same test errors while sometimes it does not.
![Screenshot 2023-09-14 at 10 22 29 AM](https://github.com/taozhi8833998/node-sql-parser/assets/6688812/1e9a2061-0882-41eb-8013-066a1b646960)

also noticed something interesting, that in code sandbox I can install a version higher than 4.10.0, the newest version of node-sql-parser is 4.6.6.

**Comment by taozhi8833998** [comment]
@liuliu-dev After upgrading to the latest version `4.10.0`, the error was gone. 

<img width="1728" alt="image" src="https://github.com/taozhi8833998/node-sql-parser/assets/7252180/61b5ec60-66ef-4615-9645-c73c13e29fd3">

I think you should remove your `node_modules`, and reinstall the latest version, then try again.

**Comment by taozhi8833998** [comment]
@liuliu-dev Did you use it for multiple databases? anything I can help with now?

**Comment by liuliu-dev** [comment]
@taozhi8833998 , thanks for your help! I tried your fix, will let you know if there is any issues.
