### ISSUE TITLE
Request  for Redshift support

### ISSUE THREAD

**Issue by jafarijason** [taozhi8833998/node-sql-parser#1594]
First of all, I want to express my appreciation for the fantastic work you've done on node-sql-parser. It's been a valuable tool for many projects.

I'm reaching out because I'd like to request support for Amazon Redshift in the node-sql-parser library. Redshift is a popular data warehousing solution, and having compatibility with it would greatly benefit the community and make this library even more versatile.

**Comment by taozhi8833998** [comment]
@jafarijason [The Amazon Redshift  SQL Reference](https://docs.aws.amazon.com/redshift/latest/dg/c_SQL_reference_conventions.html). Do you have any idea how I can generate the parser based on which databases like it most? pg or MySQL or bigquery?

**Comment by jafarijason** [comment]
> @jafarijason It's my pleasure. [The Amazon Redshift SQL Reference](https://docs.aws.amazon.com/redshift/latest/dg/c_SQL_reference_conventions.html). Do you have any idea how I can generate the parser based on which databases like it most? pg or MySQL or bigquery?

@taozhi8833998, thanks for you answer, basically Amzon Redshift is based on Postgres interface and it has most compatibility with it and there are some more option on top of it which if you can supported it it will really usefull.

**Comment by taozhi8833998** [comment]
@jafarijason OK, I will generate it based on the pg.
