### ISSUE TITLE
VARCHAR(NUMBER) return VARCHARNUMBER

### ISSUE THREAD

**Issue by AvivVegh** [taozhi8833998/node-sql-parser#1600]
Using parser astify:

const sql = select name::varchar(200) from raw_hosts
const parsedQuery = this.parser.astify(sql, { database: 'PostgresQL' })
const updatedSql = parser.sqlify(parsedQuery)

console.log(updatedSql)

Actual result: 
SELECT name::VARCHAR200 FROM raw_hosts

Expected result 
SELECT name::VARCHAR(200) FROM raw_hosts

**Comment by taozhi8833998** [comment]
@AvivVegh Thanks for pointing it out, fixed.
