### ISSUE TITLE
no definition for the 'checksum' / 'delay_key_write' part of a create table statement

### ISSUE THREAD

**Issue by croconut** [taozhi8833998/node-sql-parser#1608]
if a checksum is defined for your mysql table, then a valid table definition with it included will not be parsable. i also dont see delay key write in the error options, that probably also is missing from the PEG.

issue was seen with msyql and current node-sql-parser version.

**To Reproduce**

``` js

const { Parser } = require('node-sql-parser/build/mysql');
const parser = new Parser();

parser.astify('create table `users` (id int(11) not null) ENGINE=InnoDB AUTO_INCREMENT=10833 DEFAULT CHARSET=utf8 CHECKSUM=1 DELAY_KEY_WRITE=1 ROW_FORMAT=DYNAMIC')

```

node-sql-parser: 4.11.0
node: 16.20.0
mysql: 5.7 / aws aurora

**Expected behavior**
Table should be parsed and checksum / delay key write should be defined in the ast's table_options

Thanks for the great parser! In the mean time, i'll strip out the end of my tables since i dont care about anything after the charset

**Comment by croconut** [comment]
btw checksum and delay_key_write are 0 / 1 only. let me know if youd prefer i add a PR myself. as i'd like to adopt this for part of a CLI tool i need, im down to help with maintenance.

**Comment by taozhi8833998** [comment]
@croconut Thank you for ur future pr, you can add any pr for the feature you wanted.
