### ISSUE TITLE
parse failing for convert("" using <charset>) in mysql

### ISSUE THREAD

**Issue by croconut** [taozhi8833998/node-sql-parser#1609]
**Describe the bug**
when a convert is in my view definition (for me, its to ensure columns with different charsets can be compared) the parse fails.

**Database Engine**
mysql 5.7 / aurora

**To Reproduce**
-the SQL to be parsed:
``` sql 
-- this one worked
-- select convert("some kinda data" using utf8) = "banana";

-- this one didnt
select convert(json_unquote(json_extract('{"thing": "252"}', "$.thing")) using utf8);
```
-the node-sql-parser version: 4.11.0
-the node version: 16.20.0

**Expected behavior**
This should be part of the known engine keywords for mysql 5.7+. I guess i just want it to astify and then sqlify back to an equivalent statement

Thanks as always! I may have more of these since i have pretty involved table / view setups.

**Comment by croconut** [comment]
oops that minimum reproduction is passing let me step through my view until its big enough to cause the issue

**Comment by croconut** [comment]
okay updated the issue with a minimum reproduction. parse fails at 'u' of using

**Comment by croconut** [comment]
additionally this successfully parses but it should error out instead

``` sql 
select convert(json_unquote(json_extract('{"thing": "252"}', "$.thing")));
```

**Comment by taozhi8833998** [comment]
@croconut Thank you for reporting this, fixed already.
