### ISSUE TITLE
MySQL Extract function is not parsed correctly

### ISSUE THREAD

**Issue by Rusty-Beard** [taozhi8833998/node-sql-parser#1617]
**Describe the bug**
EXTRACT function is not parsed correctly

**Database Engine**
MySQL

**To Reproduce**
```
import { Parser } from 'node-sql-parser';
const parser = new Parser();
const res = parser.parse("SELECT EXTRACT(YEAR_MONTH FROM '2023-10-10')")
```

node v18.17.1
node-sql-parser v4.11.0

**Expected behavior**
An AST is built.

**Actual behavior**
Error is thrown.
`Expected "#", "(", "--", ".", "/*", or [ \t\n\r] but "F" found`

**Comment by Rusty-Beard** [comment]
BTW, it successfully parses `SELECT EXTRACT(YEAR FROM '2023-10-10')` so I guess there are just missing definitions.
https://dev.mysql.com/doc/refman/8.0/en/expressions.html#temporal-intervals

**Comment by taozhi8833998** [comment]
@Rusty-Beard Thanks for reporting it, fixing it, and adding more test cases for this now. I will open a new PR for it tomorrow.
