### ISSUE TITLE
dataType transfer error

### ISSUE THREAD

**Issue by kaimeng** [taozhi8833998/node-sql-parser#1625]
**Describe the bug**
parse sql:  
Select Convert(T.Name, char(10)) AS Name From AA T

to ast, then conver the ast to sql

got: 
SELECT CONVERT(`T`.`Name`, CHAR10) AS `Name` FROM `AA` AS `T`

**ERROR**: 
dataType char(10) became CHAR10

**Database Engine**
mysql

**Comment by taozhi8833998** [comment]
@kaimeng same with #1600, fixed already, will be right in next version.
