### ISSUE TITLE
Snowflake sqlify issue

### ISSUE THREAD

**Issue by AvivVegh** [taozhi8833998/node-sql-parser#1632]
Using function sqlify for Snowflake 
...
const sql = 'select NAME  as "a\b" from schmea.table'
const ast = parser.astify(sql, { database: 'Snowflake' })
const parsedSql = parser.sqlify(sql, { database: 'Snowflake' })
console.log(parsedSql)

expected: select "NAME" as "a\b" from "schmea"."table"
actual: select "NAME" as \`a\b` from "schmea"."table"

\`a\b`  is not valid in Snowflake 

also in adding quotes you are losing the "Letter case"
the column/schema/table should be the exact name (with letter case) as it is in the warehouse. 

can we do something with that ?

**Comment by AvivVegh** [comment]
sorry there is not issues "schame"."table", the main issues with quotes is that it you are losing the "Letter case"
the column/schema/table should be the exact name (with letter case) as it is in the warehouse. 

can we do something with that ?

**Comment by taozhi8833998** [comment]
two issue here:

1. the alias is not identified by `"`
2. when sqlify back losing the "letter case"

**Comment by taozhi8833998** [comment]
@AvivVegh the first issue has been fixed. working on the second one now.

**Comment by taozhi8833998** [comment]
@AvivVegh for the second issue, can you give me some cases to make it more clearly?

**Comment by AvivVegh** [comment]
case sensitive example: 

warehouse state:
table name: SRC_HOST
column name: name

const sql = 'select NAME from dev.src_host'

if Im running this query directly in the warehouse or in some db client 
there is no case sensitive, but when the parser is adding quotes, we are losing this functionality 

parser result:
select "NAME" from "dev"."src_host"

can we might add a flag to parser remove quotes ?
