### ISSUE TITLE
BigQuery: parse fails on "CREATE TABLE"

### ISSUE THREAD

**Issue by yo16** [taozhi8833998/node-sql-parser#1636]
**Describe the bug**
fails to parse `CREATE TABLE` on BigQuery.
Even simple `CREATE TABLE` statements like the following fail.
```
CREATE TABLE mydataset.newtable ( x INT64 );
```
Is `CREATE TABLE` not supported yet?
https://cloud.google.com/bigquery/docs/reference/standard-sql/data-definition-language#create_table_statement

This error is rised.
```
Uncaught ReferenceError: n is not defined
```

**Database Engine**
BigQuery

**To Reproduce**
-the SQL that be parsed: complex query in addition to the above. (I've never been successful)
-the node-sql-parser version: 4.11.0
-the node version: 18.12.1

**Expected behavior**
No error, and the appropriate properties being filled up in the AST.

**Comment by taozhi8833998** [comment]
@yo16 Sorry for that, we support `create table`. It's a bug and has been fixed.
