### ISSUE TITLE
Parsing Update query for MySQL Error on First SET

### ISSUE THREAD

**Issue by Etep15** [taozhi8833998/node-sql-parser#1657]
**Describe the bug**
Given the following UPDATE statement :

`UPDATE go_draw_type SET go=0, drawType=0, changeTag=(go_draw_type.changeTag + 1), modifiedAt='2023-11-09 20:27:47.735 UTC' WHERE (go_draw_type.id IN (405) AND (go_draw_type.uuid='1EE7DD91-2893-4296-A3C6-F7F5A62A134F' AND 1=1))`

We are getting the error "SyntaxError: Expected [A-Za-z0-9_$\\x80-\uffff] or [A-Za-z0-9_:] but \"=\" found."

Further details shows that it is occuring on at the = at the go=0 location.

```
"found": "=",
        "location": {
            "start": {
                "offset": 26,
                "line": 1,
                "column": 27
            },
            "end": {
                "offset": 27,
                "line": 1,
                "column": 28
            }
        }
```

This is valid SQL that runs on our MySQL server. Not sure why it's confused on the first set?

**Database Engine**
MySQL

**To Reproduce**
-the SQL that be parsed
See above
-the node-sql-parser version
4.11.0

-the node version
v14.17.1

**Expected behavior**
It should parse.

**Screenshots**

**Additional context**

**Comment by taozhi8833998** [comment]
@Etep15 `go` is a reserved word in MySQL, which causes the parser to fail. fixed it now.
