### ISSUE TITLE
Add support for REPLACE function

### ISSUE THREAD

**Issue by victorbadila** [taozhi8833998/node-sql-parser#167]
It seems the query builder does not like the replace function as shown in the example:
```
const { Parser } = require("node-sql-parser")
const parser = new Parser()
const ast = parser.astify('SELECT REPLACE('w3resource','ur','r');');
```
Not sure if the issue should be opened here given as it might be related to a dependency of this project.

**Comment by taozhi8833998** [comment]
fixed

**Comment by taozhi8833998** [comment]
try `1.6.17` version
