### ISSUE TITLE
Postgres dialect returns array of a single AST

### ISSUE THREAD

**Issue by nicoabie** [taozhi8833998/node-sql-parser#1677]
**Describe the bug**
If I create an AST for `select u.name, p.title, p.content from users u inner join posts p on u.id = p.user_id` in mysql returns an object

but for postgres it returns an array with a single object

**Database Engine**
which database engine does your SQL running on? such as MySQL, PostgreSQL.

**To Reproduce**
-the SQL that be parsed `select u.name, p.title, p.content from users u inner join posts p on u.id = p.user_id`
-the node-sql-parser version latest
-the node version current

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by taozhi8833998** [comment]
@nicoabie Sorry for that. it duplicated with #1611 , which was fixed in #1615 , and will be available in the next version.

**Comment by nicoabie** [comment]
Thanks! Looking forward to new release!
