### ISSUE TITLE
Add support for PARTITION

### ISSUE THREAD

**Issue by victorbadila** [taozhi8833998/node-sql-parser#168]
I have the following query which doesn't seem to get parsed:
```
const statement = `
SELECT id, name, gender, COUNT(gender) OVER (PARTITION BY gender) AS Total_students,
FROM student
`

var { Parser } = require("node-sql-parser")
const parser = new Parser()
const ast = parser.astify(statement);
```
It throws the following error:
```
peg$SyntaxError: Expected "#", ",", "--", "/*", ";", "FROM", "GROUP", "HAVING", "LIMIT", "ORDER", "UNION", "WHERE", [ \t\n\r], or end of input but "(" found.
```
If I remove the paranthesis before andafter "PARTITION BY gender" it seems to have a problem with the "P" from the start of the word "PARTITION", though I'm not sure that is related.

**Comment by taozhi8833998** [comment]
is it ANSI SQL, not MySQL SQL grammar?

**Comment by victorbadila** [comment]
Hi, from what I could gather the scripts that I'm trying to parse are used in Google Cloud Platform's Big Query. Is this something for which support can be added?

**Comment by AndyClausen** [comment]
I'm also having this problem. Google have made specs on the language here: https://github.com/google/zetasql/tree/master/docs

**Comment by taozhi8833998** [comment]
ok, I would check it out

**Comment by taozhi8833998** [comment]
try `1.6.20`

**Comment by victorbadila** [comment]
Thanks, I checked the example I originally posted and it indeed works. In the production scripts that I intend to parse with this tool I found another place where it breaks, and there might be similar cases which don't come to mind since I'm a not a main SQL person. Here's an example on a test table:
```
SELECT ROW_NUMBER() OVER (PARTITION BY gender) AS Total_students FROM student
```
I have tested this example and the others that I will be posting directly on Google's Big Query and they get executed without problems, so it's valid SQL according to them.

**Comment by taozhi8833998** [comment]
> Thanks, I checked the example I originally posted and it indeed works. In the production scripts that I intend to parse with this tool I found another place where it breaks, and there might be similar cases which don't come to mind since I'm a not a main SQL person. Here's an example on a test table:
> 
> ```
> SELECT ROW_NUMBER() OVER (PARTITION BY gender) AS Total_students FROM student
> ```
> 
> I have tested this example and the others that I will be posting directly on Google's Big Query and they get executed without problems, so it's valid SQL according to them.

fixed in new version

**Comment by victorbadila** [comment]
Works well, in another script I have to parse I have PARTITION by followed by ORDER statement. I have simplified it in the following example that seems to also throw an error when parsing while working in SQL:
```
`SELECT ROW_NUMBER() OVER (PARTITION BY gender ORDER BY gender asc) AS mycol FROM student`
```
I really hope that's the last thing I have to say regarding this PARITION issue, and thank you very much for the quick updates!

**Comment by taozhi8833998** [comment]
supported in `1.6.23`. Any more features or issues you could create a new issue to describe. Don't leave a reply to a closed issue again!  Thanks for ur understand
