### ISSUE TITLE
parses AVG() with more than one argument to AST without detecting syntax error

### ISSUE THREAD

**Issue by meghna786** [taozhi8833998/node-sql-parser#1682]
**Describe the bug**
AVG(), SUM() syntax error is not detected

**Database Engine**
MySQL

**To Reproduce**
SELECT AVG(Quantity,age)
FROM table1;

**Expected behavior**
should result in invalid sql, but it parses the query into AST

**Screenshots**
![image](https://github.com/taozhi8833998/node-sql-parser/assets/66870732/e3398842-cd4d-42b4-b360-1f39da8593e0)

**Comment by taozhi8833998** [comment]
> is not supported currently

It has been supported before.

**Comment by meghna786** [comment]
@taozhi8833998 
 Version- I'm using 4.12.0 version
Code- I'm not following up with what code you are referring here, could you elaborate a bit so I can add it here.

I've added the library using <script src="https://unpkg.com/node-sql-parser/umd/mysql.umd.js"></script> CND

for t-SQL
I've tried with 'opt' as I've mentioned in my previous comment

**Comment by taozhi8833998** [comment]
> @taozhi8833998 Version- I'm using 4.12.0 version Code- I'm not following up with what code you are referring here, could you elaborate a bit so I can add it here.
> 
> I've added the library using <script src="https://unpkg.com/node-sql-parser/umd/mysql.umd.js"></script> CND
> 
> for t-SQL I've tried with 'opt' as I've mentioned in my previous comment

You import MySQL parser, while trying to parse tsql. Code below copy from the readme.
```js
// support all database parser, but file size is about 750K
<script src="https://unpkg.com/node-sql-parser/umd/index.umd.js"></script>

// or you can import specified database parser only, it's about 150K

<script src="https://unpkg.com/node-sql-parser/umd/mysql.umd.js"></script>

<script src="https://unpkg.com/node-sql-parser/umd/postgresql.umd.js"></script>
```

**Comment by meghna786** [comment]
now it worked, thanks!
