### ISSUE TITLE
Add support for RETURNING

### ISSUE THREAD

**Issue by bigbn** [taozhi8833998/node-sql-parser#169]
Unable to parse expressions with "returning" operator

    const opt = {
      database: 'postgresql'
    }
    const ast = parser.astify(sql, opt)

Example:

    INSERT INTO "order" (regtime, phone_id, src, dst, rate_id, region_id, service_id, queue_id, city_id) VALUES ('2019-12-23T10:16:23.816Z', 1, 'A', 'B', 1, 1, 1, 1, 1) RETURNING id

Got:

    SyntaxError: Expected "#", ",", "--", "/*", ";", or [ \t\n\r] but "R" found.

**Comment by taozhi8833998** [comment]
try `1.6.17` version

**Comment by bigbn** [comment]
Yep. Now it works. 

    returning: { type: 'returning', columns: [ [Object] ] } }

Thank you very much
