### ISSUE TITLE
Support for BigQuery 'EXCEPT' syntax

### ISSUE THREAD

**Issue by atardadi** [taozhi8833998/node-sql-parser#1696]
**Describe the bug**
BigQuery allows selecting columns with 'EXCEPT' syntax.
For example:
```sql
SELECT * EXCEPT(id)
FROM some_table 
```

**Database Engine**
BigQuery

**To Reproduce**
-the SQL that be parsed
```sql
SELECT * EXCEPT(id)
FROM some_table 
```

-the node-sql-parser version
`^4.12.0`

-the node version
`v18.17.0`

**Comment by taozhi8833998** [comment]
@atardadi It has been supported before, can you show me the codes you are using?

**Comment by atardadi** [comment]
@taozhi8833998 you're right, it works!
My bad :)
