### ISSUE TITLE
if insert into sql has word 'rank', throw error

### ISSUE THREAD

**Issue by iblold** [taozhi8833998/node-sql-parser#1697]
wrong: insert into abc(rank) values(1)
ok: insert into abc(rank1) values(1)

Why hate this word. :P

**Comment by taozhi8833998** [comment]
@iblold `rank` is a reserved word since [MySQL 8.0.2](https://dev.mysql.com/doc/refman/8.0/en/keywords.html). so if you using it as a column name , you should identify it:

```sql
insert into abc(`rank`) values(1)
```
