### ISSUE TITLE
AST types inconsistencies

### ISSUE THREAD

**Issue by tbantle22** [taozhi8833998/node-sql-parser#1701]
I'm attempting to parse a query string (using `parser.astify`), make some changes to the resulting `AST` and then `parser.sqlify` to get the resulting query string. We use typescript and have found some issues:

1. The is no `Drop` AST for `drop table [tablename]`. It parses to:

```ts
{
      type: "drop",
      keyword: "table",
      name: [{ db: null, table: tableName, as: null }],
    }
```

  But I get a type error trying to pass that to `parser.sqlify`

2. `table` method for `Alter` is incorrect. It is currently `table: From;`, but `parser.sqlify` only works if the `table` field is an array, like `table: From[];`, otherwise it omits the table name from the query string

3. The `where` field (applicable to mutliple AST) used to be `any`. It now has a few issues: 

      a. It is no longer nullable (it should be for queries without a where clause)
      
      b. For `left` and `right`, the only options are now `ColumnRef` and `Param`. Neither of these allow "null" or "string" types (i.e. `where col1 = "string"` or `where col2 is null`) 

      c. The `where` type for queries using `WHERE NOT` no longer work. The parsed `WHERE NOT` query looks like:
```ts
where: {
        name: "NOT",
        type: "function",
        args: { type: "expr_list", value: [] as Expr[] }
      },
```

**Comment by taozhi8833998** [comment]
@tbantle22 Sorry for that, I will try to fix it later.

**Comment by tbantle22** [comment]
Thank you!

**Comment by tbantle22** [comment]
Another one I found:

The `Column` interface is currently 
```ts
export interface Column {
  expr: ColumnRef | AggrFunc;
  as: string;
}
```
But it should be
```ts
export interface Column {
  expr: ColumnRef | AggrFunc;
  as: string | null;
}
```
