### ISSUE TITLE
cant parse valid postgres query when column name is surroundeed by double quotes

### ISSUE THREAD

**Issue by karanssj4** [taozhi8833998/node-sql-parser#1714]
**Describe the bug**

```
const { Parser } = require('node-sql-parser');
const parser = new Parser({ database: 'Postgresql'});

const ast = parser.astify(`SELECT res.expectedResponseSchema->'statusCode'->'value' as sc FROM res`) // works

const ast = parser.astify(`SELECT res."expectedResponseSchema"->'statusCode'->'value' as sc FROM res`) // throws error
```

**Database Engine**
PostgreSQL.

**To Reproduce**
-the SQL that be parsed: SELECT res."expectedResponseSchema"->'statusCode'->'value' as sc FROM res

refer this https://runkit.com/embed/wxp2yoy2c8h4

**Comment by taozhi8833998** [comment]
@karanssj4 It has been fixed in the latest version, please upgrade the version to `4.1.5.0`, and try again, thanks.

**Comment by karanssj4** [comment]
I tried this on the 4.15.0 only. The runkit example uses 4.11.0 i guess. But this doesnt work on 4.15.0
