### ISSUE TITLE
cant parse valid postgres query when column name is surrounded by double quotes

### ISSUE THREAD

**Issue by karanssj4** [taozhi8833998/node-sql-parser#1719]
@karanssj4 It has been fixed in the latest version, please upgrade the version to `4.15.0`, and try again, thanks. If it's still not working, please reopen the issue, and let me know.

_Originally posted by @taozhi8833998 in https://github.com/taozhi8833998/node-sql-parser/issues/1714#issuecomment-1857182126_

**Comment by karanssj4** [comment]
@taozhi8833998 this is still an issue in 4.15.0

**Comment by taozhi8833998** [comment]
> @taozhi8833998 this is still an issue in 4.15.0

@karanssj4 please show the codes you are using.

**Comment by taozhi8833998** [comment]
@karanssj4  I can't reproduce it in the latest version.

**Comment by karanssj4** [comment]
> > @taozhi8833998 this is still an issue in 4.15.0
> 
> @karanssj4 please show the codes you are using.

```
const { Parser } = require('node-sql-parser');
const parser = new Parser({ database: 'Postgresql' });

let ast

try {
    ast = parser.parse(`SELECT res."expectedResponseSchema"->'statusCode' as sc FROM res limit 20`)
} catch (e) {
    console.log('err');
    throw e
}
```

@taozhi8833998 this is the console output

> err
> 
> /home/karan/Projects/node-playground/node-sql-parser.js:11
>     throw e
>     ^
> s [SyntaxError]: Expected "!", "#", "$", "'", "(", "+", "-", "--", "/*", "0x", ":", "?", "@", "@@", "AVG", "CASE", "CAST", "COUNT", "CURRENT_DATE", "CURRENT_TIME", "CURRENT_TIMESTAMP", "CURRENT_USER", "DATE", "DATETIME", "DATE_TRUNC", "EXTRACT", "FALSE", "GROUP_CONCAT", "INTERVAL", "MATCH", "MAX", "MIN", "N", "NULL", "SESSION_USER", "SUM", "SYSTEM_USER", "TIME", "TIMESTAMP", "TRUE", "USER", "X", "\"", "_binary", "_latin1", "`", "b", "binary", "convert", "trim", "~", [ \t\n\r], [0-9], or [A-Za-z_] but ">" found.
>     at Fa (/home/karan/Projects/node-playground/node_modules/node-sql-parser/index.js:1:372557)
>     at Object.parse [as mysql] (/home/karan/Projects/node-playground/node_modules/node-sql-parser/index.js:1:542279)
>     at r.value (/home/karan/Projects/node-playground/node_modules/node-sql-parser/index.js:1:1555476)
>     at Object.<anonymous> (/home/karan/Projects/node-playground/node-sql-parser.js:7:18)
>     at Module._compile (node:internal/modules/cjs/loader:1241:14)
>     at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
>     at Module.load (node:internal/modules/cjs/loader:1091:32)
>     at Module._load (node:internal/modules/cjs/loader:938:12)
>     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)
>     at node:internal/main/run_main_module:23:47 {
>   expected: [
>     {
>       type: 'class',
>       parts: [ ' ', '\t', '\n', '\r' ],
>       inverted: false,
>       ignoreCase: false
>     },
>     { type: 'literal', text: '/*', ignoreCase: false },
>     { type: 'literal', text: '--', ignoreCase: false },
>     { type: 'literal', text: '#', ignoreCase: false },
>     { type: 'literal', text: 'CAST', ignoreCase: true },
>     { type: 'literal', text: 'CAST', ignoreCase: true },
>     { type: 'literal', text: 'CAST', ignoreCase: true },
>     { type: 'literal', text: 'CAST', ignoreCase: true },
>     { type: 'literal', text: 'CAST', ignoreCase: true },
>     { type: 'literal', text: 'binary', ignoreCase: true },
>     { type: 'literal', text: '_binary', ignoreCase: true },
>     {
>       type: 'class',
>       parts: [ ' ', '\t', '\n', '\r' ],
>       inverted: false,
>       ignoreCase: false
>     },
>     { type: 'literal', text: '/*', ignoreCase: false },
>     { type: 'literal', text: '--', ignoreCase: false },
>     { type: 'literal', text: '#', ignoreCase: false },
>     { type: 'literal', text: '_binary', ignoreCase: true },
>     { type: 'literal', text: '_latin1', ignoreCase: true },
>     {
>       type: 'class',
>       parts: [ ' ', '\t', '\n', '\r' ],
>       inverted: false,
>       ignoreCase: false
>     },
>     { type: 'literal', text: '/*', ignoreCase: false },
>     { type: 'literal', text: '--', ignoreCase: false },
>     { type: 'literal', text: '#', ignoreCase: false },
>     { type: 'literal', text: 'X', ignoreCase: true },
>     { type: 'literal', text: '_binary', ignoreCase: true },
>     { type: 'literal', text: '_latin1', ignoreCase: true },
>     {
>       type: 'class',
>       parts: [ ' ', '\t', '\n', '\r' ],
>       inverted: false,
>       ignoreCase: false
>     },
>     { type: 'literal', text: '/*', ignoreCase: false },
>     { type: 'literal', text: '--', ignoreCase: false },
>     { type: 'literal', text: '#', ignoreCase: false },
>     { type: 'literal', text: 'b', ignoreCase: true },
>     { type: 'literal', text: '_binary', ignoreCase: true },
>     { type: 'literal', text: '_latin1', ignoreCase: true },
>     {
>       type: 'class',
>       parts: [ ' ', '\t', '\n', '\r' ],
>       inverted: false,
>       ignoreCase: false
>     },
>     { type: 'literal', text: '/*', ignoreCase: false },
>     { type: 'literal', text: '--', ignoreCase: false },
>     { type: 'literal', text: '#', ignoreCase: false },
>     { type: 'literal', text: '0x', ignoreCase: true },
>     { type: 'literal', text: 'N', ignoreCase: true },
>     { type: 'literal', text: "'", ignoreCase: false },
>     { type: 'literal', text: '"', ignoreCase: false },
>     {
>       type: 'class',
>       parts: [ [ '0', '9' ] ],
>       inverted: false,
>       ignoreCase: false
>     },
>     {
>       type: 'class',
>       parts: [ [ '0', '9' ] ],
>       inverted: false,
>       ignoreCase: false
>     },
>     { type: 'literal', text: '-', ignoreCase: false },
>     { type: 'literal', text: '+', ignoreCase: false },
>     { type: 'literal', text: '-', ignoreCase: false },
>     { type: 'literal', text: '+', ignoreCase: false },
>     {
>       type: 'class',
>       parts: [ [ '0', '9' ] ],
>       inverted: false,
>       ignoreCase: false
>     },
>     {
>       type: 'class',
>       parts: [ [ '0', '9' ] ],
>       inverted: false,
>       ignoreCase: false
>     },
>     { type: 'literal', text: '-', ignoreCase: false },
>     { type: 'literal', text: '+', ignoreCase: false },
>     { type: 'literal', text: '-', ignoreCase: false },
>     { type: 'literal', text: '+', ignoreCase: false },
>     {
>       type: 'class',
>       parts: [ [ '0', '9' ] ],
>       inverted: false,
>       ignoreCase: false
>     },
>     {
>       type: 'class',
>       parts: [ [ '0', '9' ] ],
>       inverted: false,
>       ignoreCase: false
>     },
>     { type: 'literal', text: '-', ignoreCase: false },
>     { type: 'literal', text: '+', ignoreCase: false },
>     { type: 'literal', text: '-', ignoreCase: false },
>     { type: 'literal', text: '+', ignoreCase: false },
>     {
>       type: 'class',
>       parts: [ [ '0', '9' ] ],
>       inverted: false,
>       ignoreCase: false
>     },
>     {
>       type: 'class',
>       parts: [ [ '0', '9' ] ],
>       inverted: false,
>       ignoreCase: false
>     },
>     { type: 'literal', text: '-', ignoreCase: false },
>     { type: 'literal', text: '+', ignoreCase: false },
>     { type: 'literal', text: '-', ignoreCase: false },
>     { type: 'literal', text: '+', ignoreCase: false },
>     { type: 'literal', text: 'TRUE', ignoreCase: true },
>     { type: 'literal', text: 'FALSE', ignoreCase: true },
>     { type: 'literal', text: 'NULL', ignoreCase: true },
>     { type: 'literal', text: 'TIME', ignoreCase: true },
>     { type: 'literal', text: 'DATE', ignoreCase: true },
>     { type: 'literal', text: 'TIMESTAMP', ignoreCase: true },
>     { type: 'literal', text: 'DATETIME', ignoreCase: true },
>     { type: 'literal', text: 'TIME', ignoreCase: true },
>     { type: 'literal', text: 'DATE', ignoreCase: true },
>     { type: 'literal', text: 'TIMESTAMP', ignoreCase: true },
>     { type: 'literal', text: 'DATETIME', ignoreCase: true },
>     { type: 'literal', text: 'MATCH', ignoreCase: true },
>     { type: 'literal', text: 'COUNT', ignoreCase: true },
>     { type: 'literal', text: 'GROUP_CONCAT', ignoreCase: true },
>     { type: 'literal', text: 'SUM', ignoreCase: true },
>     { type: 'literal', text: 'MAX', ignoreCase: true },
>     { type: 'literal', text: 'MIN', ignoreCase: true },
>     { type: 'literal', text: 'AVG', ignoreCase: true },
>     { type: 'literal', text: 'EXTRACT', ignoreCase: true },
>     { type: 'literal', text: 'EXTRACT', ignoreCase: true },
>     { type: 'literal', text: 'DATE_TRUNC', ignoreCase: true },
>     { type: 'literal', text: 'trim', ignoreCase: true },
>     { type: 'literal', text: 'convert', ignoreCase: true },
>     { type: 'literal', text: 'CURRENT_DATE', ignoreCase: true },
>     { type: 'literal', text: 'CURRENT_TIME', ignoreCase: true },
>     { type: 'literal', text: 'CURRENT_TIMESTAMP', ignoreCase: true },
>     { type: 'literal', text: 'CURRENT_USER', ignoreCase: true },
>     { type: 'literal', text: 'USER', ignoreCase: true },
>     { type: 'literal', text: 'SESSION_USER', ignoreCase: true },
>     { type: 'literal', text: 'SYSTEM_USER', ignoreCase: true },
>     { type: 'literal', text: 'CURRENT_DATE', ignoreCase: true },
>     { type: 'literal', text: 'CURRENT_TIME', ignoreCase: true },
>     { type: 'literal', text: 'CURRENT_TIMESTAMP', ignoreCase: true },
>     {
>       type: 'class',
>       parts: [ [ 'A', 'Z' ], [ 'a', 'z' ], '_' ],
>       inverted: false,
>       ignoreCase: false
>     },
>     { type: 'literal', text: '"', ignoreCase: false },
>     { type: 'literal', text: "'", ignoreCase: false },
>     { type: 'literal', text: '`', ignoreCase: false },
>     ... 33 more items
>   ],
>   found: '>',
>   location: {
>     start: { offset: 36, line: 1, column: 37 },
>     end: { offset: 37, line: 1, column: 38 }
>   }
> }
> 
> Node.js v20.9.0
> [nodemon] app crashed - waiting for file changes before starting...
> 
> 
>

**Comment by taozhi8833998** [comment]
> > > @taozhi8833998 this is still an issue in 4.15.0
> > 
> > 
> > @karanssj4 please show the codes you are using.
> 
> ```
> const { Parser } = require('node-sql-parser');
> const parser = new Parser({ database: 'Postgresql' });
> 
> let ast
> 
> try {
>     ast = parser.parse(`SELECT res."expectedResponseSchema"->'statusCode' as sc FROM res limit 20`)
> } catch (e) {
>     console.log('err');
>     throw e
> }
> ```
> 
> @taozhi8833998 this is the console output
> 
> > err
> > /home/karan/Projects/node-playground/node-sql-parser.js:11
> > throw e
> > ^
> > s [SyntaxError]: Expected "!", "#", "$", "'", "(", "+", "-", "--", "/*", "0x", ":", "?", "@", "@@", "AVG", "CASE", "CAST", "COUNT", "CURRENT_DATE", "CURRENT_TIME", "CURRENT_TIMESTAMP", "CURRENT_USER", "DATE", "DATETIME", "DATE_TRUNC", "EXTRACT", "FALSE", "GROUP_CONCAT", "INTERVAL", "MATCH", "MAX", "MIN", "N", "NULL", "SESSION_USER", "SUM", "SYSTEM_USER", "TIME", "TIMESTAMP", "TRUE", "USER", "X", """, "_binary", "_latin1", "`", "b", "binary", "convert", "trim", "~", [ \t\n\r], [0-9], or [A-Za-z_] but ">" found. at Fa (/home/karan/Projects/node-playground/node_modules/node-sql-parser/index.js:1:372557) at Object.parse [as mysql] (/home/karan/Projects/node-playground/node_modules/node-sql-parser/index.js:1:542279) at r.value (/home/karan/Projects/node-playground/node_modules/node-sql-parser/index.js:1:1555476) at Object.<anonymous> (/home/karan/Projects/node-playground/node-sql-parser.js:7:18) at Module._compile (node:internal/modules/cjs/loader:1241:14) at Module._extensions..js (node:internal/modules/cjs/loader:1295:10) at Module.load (node:internal/modules/cjs/loader:1091:32) at Module._load (node:internal/modules/cjs/loader:938:12) at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12) at node:internal/main/run_main_module:23:47 { expected: [ { type: 'class', parts: [ ' ', '\t', '\n', '\r' ], inverted: false, ignoreCase: false }, { type: 'literal', text: '/*', ignoreCase: false }, { type: 'literal', text: '--', ignoreCase: false }, { type: 'literal', text: '#', ignoreCase: false }, { type: 'literal', text: 'CAST', ignoreCase: true }, { type: 'literal', text: 'CAST', ignoreCase: true }, { type: 'literal', text: 'CAST', ignoreCase: true }, { type: 'literal', text: 'CAST', ignoreCase: true }, { type: 'literal', text: 'CAST', ignoreCase: true }, { type: 'literal', text: 'binary', ignoreCase: true }, { type: 'literal', text: '_binary', ignoreCase: true }, { type: 'class', parts: [ ' ', '\t', '\n', '\r' ], inverted: false, ignoreCase: false }, { type: 'literal', text: '/*', ignoreCase: false }, { type: 'literal', text: '--', ignoreCase: false }, { type: 'literal', text: '#', ignoreCase: false }, { type: 'literal', text: '_binary', ignoreCase: true }, { type: 'literal', text: '_latin1', ignoreCase: true }, { type: 'class', parts: [ ' ', '\t', '\n', '\r' ], inverted: false, ignoreCase: false }, { type: 'literal', text: '/*', ignoreCase: false }, { type: 'literal', text: '--', ignoreCase: false }, { type: 'literal', text: '#', ignoreCase: false }, { type: 'literal', text: 'X', ignoreCase: true }, { type: 'literal', text: '_binary', ignoreCase: true }, { type: 'literal', text: '_latin1', ignoreCase: true }, { type: 'class', parts: [ ' ', '\t', '\n', '\r' ], inverted: false, ignoreCase: false }, { type: 'literal', text: '/*', ignoreCase: false }, { type: 'literal', text: '--', ignoreCase: false }, { type: 'literal', text: '#', ignoreCase: false }, { type: 'literal', text: 'b', ignoreCase: true }, { type: 'literal', text: '_binary', ignoreCase: true }, { type: 'literal', text: '_latin1', ignoreCase: true }, { type: 'class', parts: [ ' ', '\t', '\n', '\r' ], inverted: false, ignoreCase: false }, { type: 'literal', text: '/*', ignoreCase: false }, { type: 'literal', text: '--', ignoreCase: false }, { type: 'literal', text: '#', ignoreCase: false }, { type: 'literal', text: '0x', ignoreCase: true }, { type: 'literal', text: 'N', ignoreCase: true }, { type: 'literal', text: "'", ignoreCase: false }, { type: 'literal', text: '"', ignoreCase: false }, { type: 'class', parts: [ [ '0', '9' ] ], inverted: false, ignoreCase: false }, { type: 'class', parts: [ [ '0', '9' ] ], inverted: false, ignoreCase: false }, { type: 'literal', text: '-', ignoreCase: false }, { type: 'literal', text: '+', ignoreCase: false }, { type: 'literal', text: '-', ignoreCase: false }, { type: 'literal', text: '+', ignoreCase: false }, { type: 'class', parts: [ [ '0', '9' ] ], inverted: false, ignoreCase: false }, { type: 'class', parts: [ [ '0', '9' ] ], inverted: false, ignoreCase: false }, { type: 'literal', text: '-', ignoreCase: false }, { type: 'literal', text: '+', ignoreCase: false }, { type: 'literal', text: '-', ignoreCase: false }, { type: 'literal', text: '+', ignoreCase: false }, { type: 'class', parts: [ [ '0', '9' ] ], inverted: false, ignoreCase: false }, { type: 'class', parts: [ [ '0', '9' ] ], inverted: false, ignoreCase: false }, { type: 'literal', text: '-', ignoreCase: false }, { type: 'literal', text: '+', ignoreCase: false }, { type: 'literal', text: '-', ignoreCase: false }, { type: 'literal', text: '+', ignoreCase: false }, { type: 'class', parts: [ [ '0', '9' ] ], inverted: false, ignoreCase: false }, { type: 'class', parts: [ [ '0', '9' ] ], inverted: false, ignoreCase: false }, { type: 'literal', text: '-', ignoreCase: false }, { type: 'literal', text: '+', ignoreCase: false }, { type: 'literal', text: '-', ignoreCase: false }, { type: 'literal', text: '+', ignoreCase: false }, { type: 'literal', text: 'TRUE', ignoreCase: true }, { type: 'literal', text: 'FALSE', ignoreCase: true }, { type: 'literal', text: 'NULL', ignoreCase: true }, { type: 'literal', text: 'TIME', ignoreCase: true }, { type: 'literal', text: 'DATE', ignoreCase: true }, { type: 'literal', text: 'TIMESTAMP', ignoreCase: true }, { type: 'literal', text: 'DATETIME', ignoreCase: true }, { type: 'literal', text: 'TIME', ignoreCase: true }, { type: 'literal', text: 'DATE', ignoreCase: true }, { type: 'literal', text: 'TIMESTAMP', ignoreCase: true }, { type: 'literal', text: 'DATETIME', ignoreCase: true }, { type: 'literal', text: 'MATCH', ignoreCase: true }, { type: 'literal', text: 'COUNT', ignoreCase: true }, { type: 'literal', text: 'GROUP_CONCAT', ignoreCase: true }, { type: 'literal', text: 'SUM', ignoreCase: true }, { type: 'literal', text: 'MAX', ignoreCase: true }, { type: 'literal', text: 'MIN', ignoreCase: true }, { type: 'literal', text: 'AVG', ignoreCase: true }, { type: 'literal', text: 'EXTRACT', ignoreCase: true }, { type: 'literal', text: 'EXTRACT', ignoreCase: true }, { type: 'literal', text: 'DATE_TRUNC', ignoreCase: true }, { type: 'literal', text: 'trim', ignoreCase: true }, { type: 'literal', text: 'convert', ignoreCase: true }, { type: 'literal', text: 'CURRENT_DATE', ignoreCase: true }, { type: 'literal', text: 'CURRENT_TIME', ignoreCase: true }, { type: 'literal', text: 'CURRENT_TIMESTAMP', ignoreCase: true }, { type: 'literal', text: 'CURRENT_USER', ignoreCase: true }, { type: 'literal', text: 'USER', ignoreCase: true }, { type: 'literal', text: 'SESSION_USER', ignoreCase: true }, { type: 'literal', text: 'SYSTEM_USER', ignoreCase: true }, { type: 'literal', text: 'CURRENT_DATE', ignoreCase: true }, { type: 'literal', text: 'CURRENT_TIME', ignoreCase: true }, { type: 'literal', text: 'CURRENT_TIMESTAMP', ignoreCase: true }, { type: 'class', parts: [ [ 'A', 'Z' ], [ 'a', 'z' ], '_' ], inverted: false, ignoreCase: false }, { type: 'literal', text: '"', ignoreCase: false }, { type: 'literal', text: "'", ignoreCase: false }, { type: 'literal', text: '`', ignoreCase: false },
> > ... 33 more items
> > ],
> > found: '>',
> > location: {
> > start: { offset: 36, line: 1, column: 37 },
> > end: { offset: 37, line: 1, column: 38 }
> > }
> > }
> > Node.js v20.9.0
> > [nodemon] app crashed - waiting for file changes before starting...

The database option is the paramater of parse function, while not on contructor.
```javascript
const { Parser } = require('node-sql-parser');
const parser = new Parser();

let ast

try {
    ast = parser.parse(`SELECT res."expectedResponseSchema"->'statusCode' as sc FROM res limit 20`, { database: 'postgresql' }) // database options should be here
   console.log('ast=', ast)
} catch (e) {
    console.log('err');
    throw e
}

```

**Comment by karanssj4** [comment]
my bad
