### ISSUE TITLE
An error occurs when parentheses and OR are combined in the COUNT function

### ISSUE THREAD

**Issue by kei-katahira** [taozhi8833998/node-sql-parser#1725]
**Describe the bug**
A syntax error occurs when parsing SQL that combines parentheses and OR in the COUNT function in a SELECT statement.

**Database Engine**
MySQL.

**To Reproduce**
-the SQL that be parsed
```sql
SELECT COUNT((A.col_1 = "03" AND A.col_2 ="") OR NULL) FROM sample_table A;
```
-the node-sql-parser version `4.16.0`
-the node version `v18.18.2`

**Screenshots**
error screenshot
![image](https://github.com/taozhi8833998/node-sql-parser/assets/80861809/95337c63-ace2-4024-a56e-3e79b5f4b2f4)

**Additional context**
By adding parentheses to COUNT as in the following SQL, the SQL can be parsed.
```sql
SELECT COUNT(((A.col_1 = "03" AND A.col_2 ="") OR NULL)) FROM sample_table A;
```

**Comment by taozhi8833998** [comment]
@kei-katahira What's the purpose of `OR NULL` in the `count` function.
