### ISSUE TITLE
Transact-SQL Support

### ISSUE THREAD

**Issue by mtriff** [taozhi8833998/node-sql-parser#174]
This looks like a great library! I would like to use this for parsing Transact-SQL (Microsoft SQL Server). How much work would be involved to add basic support?

Some things that would need to be supported:

- [x] Uses `[` and `]` as quote characters, i.e. `[tableName]`
- [x] Allow for `databaseName.schemaName.tableName` format in queries
- [ ] Support for [`MERGE` queries](https://docs.microsoft.com/en-us/sql/t-sql/statements/merge-transact-sql?view=sql-server-ver15)

What's the best way to help out with implementation? I'd be happy to help, but not sure where to start.

**Comment by taozhi8833998** [comment]
It would be much more clear if you could show me the example SQL for the feature you required

**Comment by mtriff** [comment]
Oh, great! Thanks for your work on this.

For the first feature, T-SQL uses those characters instead of \` in MySQL or `"` in Postgres. For example:

```
SELECT [column1], [column2] FROM [exampleSchema].[exampleTable]
```

**Comment by taozhi8833998** [comment]
> Oh, great! Thanks for your work on this.
> 
> For the first feature, T-SQL uses those characters instead of ` in MySQL or `"` in Postgres. For example:
> 
> ```
> SELECT [column1], [column2] FROM [exampleSchema].[exampleTable]
> ```

got it, thanks for ur explanation

**Comment by esetnik** [comment]
@taozhi8833998 how much work is it to implement 

> * [x]  Allow for `databaseName.schemaName.tableName` format in queries

This is used heavily in TSQL and currently not working in v1.10.1.

```sql
CREATE TABLE test (
  id BIGINT NOT NULL PRIMARY KEY IDENTITY(1, 1),
  [name] NVARCHAR(MAX) NOT NULL,
  [status] BIT NOT NULL DEFAULT(1),
);
```

**Comment by taozhi8833998** [comment]
> ```sql
> CREATE TABLE [test] (
>   id BIGINT NOT NULL PRIMARY KEY IDENTITY(1, 1),
>   [name] NVARCHAR(MAX) NOT NULL,
>   [status] BIT NOT NULL DEFAULT(1),
> );
> ```

```SQL
CREATE TABLE test (
  id BIGINT NOT NULL PRIMARY KEY IDENTITY(1, 1),
  name NVARCHAR(MAX) NOT NULL,
  status BIT NOT NULL DEFAULT(1),
);
```
is the same as 

```SQL
CREATE TABLE [test] (
  id BIGINT NOT NULL PRIMARY KEY IDENTITY(1, 1),
  [name] NVARCHAR(MAX) NOT NULL,
  [status] BIT NOT NULL DEFAULT(1),
);
```

am I right???

The parser should parse both syntaxes successfully.

**Comment by esetnik** [comment]
Yes, although the brackets `[]` in TSQL are used if your column or table includes a space or uses a reserved keyword https://docs.microsoft.com/en-us/sql/t-sql/language-elements/reserved-keywords-transact-sql?view=sql-server-ver15

Valid:
```sql
CREATE TABLE [test table] (
  id BIGINT NOT NULL PRIMARY KEY IDENTITY(1, 1),
  [user] NVARCHAR(MAX) NOT NULL,
);
```

Invalid
// space in table name
```sql
CREATE TABLE test table (
  id BIGINT NOT NULL PRIMARY KEY IDENTITY(1, 1),
  [user] NVARCHAR(MAX) NOT NULL,
);
```
// reserved keyword user
```sql
CREATE TABLE [test table] (
  id BIGINT NOT NULL PRIMARY KEY IDENTITY(1, 1),
  user NVARCHAR(MAX) NOT NULL,
);
```

**Comment by taozhi8833998** [comment]
ok，can I add `[]` to all the column and table name when sqlify from the ast??

such as 

```SQL
CREATE TABLE test (
  id BIGINT NOT NULL PRIMARY KEY IDENTITY(1, 1),
  user NVARCHAR(MAX) NOT NULL,
);
```

and after sqlify to 

```SQL
CREATE TABLE [test] (
  [id] BIGINT NOT NULL PRIMARY KEY IDENTITY(1, 1),
  [user] NVARCHAR(MAX) NOT NULL,
);
```
is it ok?

**Comment by esetnik** [comment]
Yes I believe that is the standard behavior for consistency. Can you also generate errors if a reserved keyword from the list is used incorrectly without `[]`?

**Comment by taozhi8833998** [comment]
> Yes I believe that is the standard behavior for consistency. Can you also generate errors if a reserved keyword from the list is used incorrectly without `[]`?

yes, if reserved keywords are used as the normal name of column or table, the parsed could throw an error. I will release a new version for `[]` in ten minutes.

**Comment by taozhi8833998** [comment]
@esetnik try `1.10.2` version

**Comment by esetnik** [comment]
Thank you! I will check it out.

**Comment by zafaralam** [comment]
I also found that the parser throws an error when adding NOLOCK to the table while doing select statements. Below is an example

```sql
SELECT name, phone FROM dbo.Person (NOLOCK)
-- or
SELECT name, phone FROM dbo.Person WITH (NOLOCK)
```

Can someone please help with this?

Thanks :)

**Comment by taozhi8833998** [comment]
@zafaralam will support today

**Comment by zafaralam** [comment]
> @zafaralam I will support [hints](https://docs.microsoft.com/en-us/sql/t-sql/queries/hints-transact-sql?view=sql-server-ver15) asap

Thanks :) and I'm happy to help if you need.

**Comment by taozhi8833998** [comment]
@zafaralam Sorry for keeping u waiting for such a long time, I am developing the parser to support `hints` syntax in SQL. I will notify you when I made any progress.
