### ISSUE TITLE
Single quotes alias should not be valid in PostgreSQL

### ISSUE THREAD

**Issue by dereeno** [taozhi8833998/node-sql-parser#1744]
**Describe the bug**
The following query is invalid, however, the parser is not rejecting it (throwing syntax error)

**Database Engine**
PostgreSQL.

**To Reproduce**
```sql
-- INVALID
select 1 as 'one'

-- VALID
select 1 as "one"
```

**Comment by taozhi8833998** [comment]
@dereeno I can't reproduce the issue. It can be parsed by the module. Can you show me the codes and the module version you are using?

**Comment by dereeno** [comment]
The problem is that this query is NOT valid, but the parser does not throw "Syntax Error"
```sql
SELECT 1 AS 'one'
```
should throw error

**Comment by taozhi8833998** [comment]
@dereeno Sorry for the misunderstanding.

**Comment by taozhi8833998** [comment]
@dereeno fixed it.
