### ISSUE TITLE
Expected [A-Za-z0-9_:] but \")\" found.

### ISSUE THREAD

**Issue by lilong7676** [taozhi8833998/node-sql-parser#1746]
**Describe the bug**
是否命中了关键字的逻辑？
**Database Engine**
mysql

**To Reproduce**
-the SQL that be parsed
`insert into t1 (string, number, boolean) values (123,123,123)`
-the node-sql-parser version
`4.10.0`
-the node version
`16`

**Expected behavior**
string, number, boolean 应该不是 mysql的关键字，但是解析报错了。

**Screenshots**
<img width="1430" alt="image" src="https://github.com/taozhi8833998/node-sql-parser/assets/21004230/9c7c1581-4bde-42bd-8a46-b387277d79ec">

**Additional context**

**Comment by taozhi8833998** [comment]
@lilong7676 `boolean` is a [keyword](https://dev.mysql.com/doc/refman/8.0/en/keywords.html) in MySQL.
