### ISSUE TITLE
Support 'db.schema.table' for Snowflake queries

### ISSUE THREAD

**Issue by dereeno** [taozhi8833998/node-sql-parser#1753]
**Describe the bug**
The following query is a valid Snowflake query but it fails to parse 

**Database Engine**
Snowflake

**To Reproduce**
```sql
SELECT * FROM my_db.my_schema.my_table
```

**Comment by taozhi8833998** [comment]
@dereeno Can you show the codes you are using? I can't reproduce it.

**Comment by atardadi** [comment]
@taozhi8833998 this query is not working. 

```sql
SELECT * FROM my_db.my_schema.my_table
```
`parser.astify()` throws a `SyntaxError` exception
I'm using mySql database

**Comment by taozhi8833998** [comment]
> @taozhi8833998 this query is not working.
> 
> ```sql
> SELECT * FROM my_db.my_schema.my_table
> ```
> 
> `parser.astify()` throws a `SyntaxError` exception I'm using mySql database

In MySQL, you shouldn't have `my_schema`, but you can have it in Snowflake.

In MySQL:

```sql
SELECT * FROM my_db.my_table
```

In Snowflake:
```sql
SELECT * FROM my_db.my_schema.my_table
```

**Comment by atardadi** [comment]
@taozhi8833998 I see.
The problem is, that MySQL is the closest dialect and you don't have Sbowflake. How do you suggest I go about this?

**Comment by taozhi8833998** [comment]
> @taozhi8833998 I see. The problem is, that MySQL is the closest dialect and you don't have Sbowflake. How do you suggest I go about this?

We have, you can set the database options to `snowflake`, and try again.

**Comment by dereeno** [comment]
@taozhi8833998  I was using the following query to test (which fails to parse)
```
SELECT * FROM db.schema.table
```
However, if I change `table` to any other table name it succeeds. I suppose `table` is a reserved keyword? 
Anyway, you can close this issue. 
Thanks!!

**Comment by taozhi8833998** [comment]
@dereeno @atardadi Yes, The `table` word is the reserved keyword in Snowflake currently, if it's not, you can open a new issue for that. Thanks.

**Comment by atardadi** [comment]
Hi @taozhi8833998, I've changed the database to Snowflake, but now other valid queries become invalid.

Opened an [issue](https://github.com/taozhi8833998/node-sql-parser/issues/1757) for Snowflake. 
I can't change MySQL to Snowflake until it's resolved.
