### ISSUE TITLE
Error parsing valid Postgresql insert

### ISSUE THREAD

**Issue by rz-itac** [taozhi8833998/node-sql-parser#176]
hi. thanks for your lib. I'm getting this issue though, feel free to ask for more info (if I can get some spare time I can help):

**Node JS version**: 12.4.0
**Version**: 1.6.13
**What happened**: when I try to parse the following sql script using this code in ts I get an exception:
```typescript
      const opt = {
        database: 'PostgresQL'
      };
      const parser = new Parser();
      this.sqlObj = <AST[]>parser.astify(this.sqlContent, opt);
```

this.sqlContent = 
```sql
insert into servicios(ruta_servicio) values('pagarPrestamo'); --this statement is parsed correctly
insert into servicios_transacciones(servicio_id, index) values((select id from servicios where ruta_servicio='pagarPrestamo'), 0); --this statement is NOT parsed correctly
```

**Exception**:
peg$SyntaxError {message: "Expected [A-Za-z0-9_] but ")" found.", expected: Array(2), found: ")", …}

**Expected result**: this.sqlObj should store the parsed statements.

**Comment by rz-itac** [comment]
Got same results testing with version: 1.6.18

**Comment by taozhi8833998** [comment]
`index` is reversed column name, I have removed it

**Comment by taozhi8833998** [comment]
try `1.6.19` version

**Comment by rz-itac** [comment]
tried 1.6.20, everything is working, thanks!
