### ISSUE TITLE
Postgres: Unable to parse BEGIN, COMMIT, SET search_path TO 

### ISSUE THREAD

**Issue by karanssj4** [taozhi8833998/node-sql-parser#1760]
**Describe the bug**
Unable to parse a few valid Postgres queries

**Database Engine**
PostgreSQL.

**To Reproduce**
-the SQL that be parsed
```js
const sql = `
BEGIN;
SET search_path TO ht_hyt; 
COMMIT;
`;

```
-the node-sql-parser version 4.17.0
-the node version 20

**Expected behavior**
Should be able to parse these 3 queries

**Comment by taozhi8833998** [comment]
@karanssj4 it supports `begin`, `commit`, and `rollback` statements now.

**Comment by karanssj4** [comment]
@taozhi8833998 thanks a lot for acomodating this. !!

4.18.0 is not published to npm. I think your CI job failed

**Comment by taozhi8833998** [comment]
> @taozhi8833998 thanks a lot for accommodating this. !!
> 
> 4.18.0 is not published to npm. I think your CI job failed

e..., I am fixing that now, sorry about that.

**Comment by taozhi8833998** [comment]
@karanssj4 published it manually, you can try it now.
