### ISSUE TITLE
Postgres casting after double quotes on column name is not working 

### ISSUE THREAD

**Issue by LaizaAngrest** [taozhi8833998/node-sql-parser#1764]
**Describe the bug**
The Postgres parser doesn't support queries with double quotes on a column name.

**Database Engine**
PostgreSQL.

**To Reproduce**
`SELECT "created_date"::date
  FROM src_hosts`

-node-sql-parser version: 4.18.0
-the node version: 18.17.0

**Expected behavior**
Double quotes on column names are valid on Postgres.

**Comment by taozhi8833998** [comment]
@LaizaAngrest Perhaps you should specify the database in the option configuration.

```javascript
const { Parser } = require('node-sql-parser')
const parser = new Parser()
const sql  = 'SELECT "created_date"  FROM src_hosts'
const opt = { database: 'postgresql' }
const ast = parser.sqlify(sql, opt)
```

If it's still not working, please show me the codes you are using.

**Comment by LaizaAngrest** [comment]
@taozhi8833998 sorry for the confusion, I forgot to include a casting after the double quotes.
The query that isn't valid is:
`SELECT "created_date"::date
FROM src_hosts`
