### ISSUE TITLE
New version parsing error

### ISSUE THREAD

**Issue by WumaCoder** [taozhi8833998/node-sql-parser#1781]
**Describe the bug**
PostgresQL parser error
```
select count(*) as cc

SyntaxError: Expected "--", "/*", "\"", [ \t\n\r], or [A-Za-z_一-龥] but "`" found.
```
**Database Engine**
PostgresQL

**To Reproduce**
-the SQL that be parsed: 
-the node-sql-parser version v4.18
-the node version

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by WumaCoder** [comment]
There is no problem with the old version

**Comment by taozhi8833998** [comment]
@WumaCoder Please show the original SQL you are using. The error shows **but "`" found.**, while not existing in your SQL, the SQL you provided can be parsed successfully by the latest version.
