### ISSUE TITLE
Issue with `INTERSECT` keyword on `noql` dialect

### ISSUE THREAD

**Issue by eXigentCoder** [taozhi8833998/node-sql-parser#1782]
**Describe the bug**
It seems that I get a syntax error if I don't include a `WHERE` statement in both my `INTERSECT` statements

**Database Engine**
noql

**To Reproduce**
-the SQL that be parsed
This one works:
```sql
SELECT  *
FROM "most-popular-films"
WHERE 1 = 1

INTERSECT

SELECT  *
FROM "top-rated-films"
WHERE 1 = 1
```
This one does not:
```sql
SELECT  *
FROM "most-popular-films"

INTERSECT

SELECT  *
FROM "top-rated-films"
```
But as soon as I don't have the where statements I get the following error:
`Expected "(", ",", "--", "/*", ";", "CROSS", "EXCEPT", "FULL", "GROUP", "HAVING", "INNER", "INTERSECT", "INTO", "JOIN", "LEFT", "LIMIT", "OFFSET", "ORDER", "RIGHT", "UNION", "WHERE", "WINDOW", [ \t\n\r], or end of input but "S" found.`
-the node-sql-parser version
`4.18.0`
-the node version
`v14.21.1`

**Expected behavior**
It should work without having to specify a where statement

**Screenshots**

**Additional context**

**Comment by taozhi8833998** [comment]
@eXigentCoder fixed it.

**Comment by eXigentCoder** [comment]
Thank you so much!
