### ISSUE TITLE
BigQuery SQL Parser Fails to Recognize WEEK Operator in DATE_SUB Function

### ISSUE THREAD

**Issue by marinBlobr** [taozhi8833998/node-sql-parser#1784]
**Describe the bug**
The parser fails to correctly interpret the `WEEK` operator in the `DATE_SUB` function for **BigQuery SQL**. Specifically, the test for parsing `DATE_SUB` with an interval of `1 WEEK` throws a syntax error, indicating that the `WEEK` operator is not recognized.

**Database Engine** 
BigQuery

**To Reproduce**
- node-sql-parser version: **4.18.0**
- node version: **v18.19.0**
- the SQL that be parsed : 
  - ❌` SELECT * WHERE created_at >= DATE_SUB(CURRENT_DATE(), INTERVAL 1 WEEK)`
  - ✅ `SELECT * WHERE created_at >= DATE_SUB(CURRENT_DATE(), INTERVAL 1 MONTH)`

  - Error thrown:
``` bash
SyntaxError: Expected "!=", "#", "%", "&&", "*", "+", "-", "--", "/", "/*", "<", "<=", "<>", "=", ">", ">=", "BETWEEN", "DAY", "HOUR", "IN", "IS", "ISOYEAR", "LIKE", "MINUTE", "MONTH", "NOT", "SECOND", "YEAR", "||", or [ \t\n\r] but "W" found.`
```

**Expected behavior**
The parser should correctly interpret the `DATE_SUB` function with `INTERVAL 1 WEEK`, without throwing a syntax error. The `WEEK` operator should be recognized as a valid interval unit for the `DATE_SUB` function in BigQuery. Documentation reference: [BigQuery DATE_SUB documentation](https://cloud.google.com/bigquery/docs/reference/standard-sql/date_functions#date_sub).

- File path: `./test/bigquery.spec.js`
- Test code:
``` javascript
it('should correctly parse DATE_SUB function with WEEK operator in BigQuery', () => {   
    const sql = "SELECT * WHERE created_at >= DATE_SUB(CURRENT_DATE(), INTERVAL 1 WEEK)";
    const ast = parser.astify(sql, opt);   expect(ast.where.right.args.value[1].unit).to.equal('week'); 
});
```

**Fix Implemented** 
To resolve the issue, modifications were made in `./pegjs/bigquery.pegjs`:

- Added a new line for `WEEK` as a valid date unit line 2950:

``` javascript
KW_UNIT_WEEK = "WEEK"i !ident_start { return 'WEEK'; }
```

> 2949: KW_UNIT_WEEK = "WEEK"i !ident_start { return 'WEEK'; }
> 2950: **KW_UNIT_WEEK = "WEEK"i !ident_start { return 'WEEK'; }**
> 2951: KW_UNIT_WEEK = "WEEK"i !ident_start { return 'WEEK'; }

    
- Included `WEEK` in the valid units parsing rule line 3021:
    
``` javascript
/ KW_UNIT_WEEK
```

> 3020: / KW_UNIT_MONTH
> 3021: **/ KW_UNIT_WEEK**
> 3022: / KW_UNIT_DAY
    

After applying these fixes, the test passed successfully, confirming that the `WEEK` operator is now correctly parsed.

**Additional context**
This fix ensures that SQL queries using the `DATE_SUB` function with a `WEEK` interval are correctly parsed in BigQuery, improving the parser's accuracy and compatibility.

**Comment by taozhi8833998** [comment]
@marinBlobr Thanks for that, fixed it. BTW, PR is welcome, if you can fix it.
