### ISSUE TITLE
PostgreSQL - Error parsing `SELECT FROM function` if quotation marks are used

### ISSUE THREAD

**Issue by antonioorct** [taozhi8833998/node-sql-parser#1789]
**Describe the bug**
I'm trying to parse a query where I'm selecting from a called function. It fails if the function is wrapped in quotation marks (`"`)  
Also, I want to have the schema specified as well but that also fails.  
If the function name is without quotation marks it works, same as specifying the schema and function name without the quotes e.g. (`schema.func`) but that doesn't generate an object with `schema` and `name` fields - it instead generates just the `name` field being equal to `{ "name": "schema.func"}`

**Database Engine**
PostgreSQL

**To Reproduce**
SQL:
```sql
SELECT * FROM "func"("start_time", "end_time")
```
```sql
SELECT * FROM "schema"."func"("start_time", "end_time")
```
node-sql-parser version: v4.17.0
Node version: v20.11.0

**Expected behavior**
I expected the first query to not crash and return the same object as parsing the query without the quotes.  
For the second query I expect it to also parse but also specify the `schema` parameter

**Comment by taozhi8833998** [comment]
@antonioorct working on it, support function name quoted, and prefix with quoted schema.
