### ISSUE TITLE
Unable to get working

### ISSUE THREAD

**Issue by joshcarey1** [taozhi8833998/node-sql-parser#1791]
I have what I would consider a simple script that I am trying to parse and I am unable to get this working.

```
const parser = new Parser();
      console.log(parser.astify(`SELECT   V_RECORD . RECORD_ID   Record ID   ,(SELECT LOGO_CONTENT FROM RSERV_LOGO WHERE 1=1 AND SERV_PROV_CODE = 'SANTABARBARA' AND LOGO_TYPE = 'Report Header') Logo  , V_RECORD . RECORD_STATUS   Record Status   ,BDOCUMENT.DOC_NAME  DOC NAME   ,BDOCUMENT.FILE_UPLOAD_DATE  UPLOAD DATE   ,V_RECORD.RECORD_STATUS_DATE  APPLICATION STATUS DATE   ,(         '<a href=\"' +         DBO.FN_GET_STDCHOICE_VALUEDESC(V_RECORD.AGENCY_ID,'ACA_CONFIGS','V360_WEB_ACTION_URL') +         'cap/capsummary/CapTabSummary.do?mode=activateSpace&serviceProviderCode=' +         V_RECORD.AGENCY_ID +         '&ID1=' + V_RECORD.T_ID1 +         '&ID2=' + V_RECORD.T_ID2 +         '&ID3=' + V_RECORD.T_ID3 +         '&requireNotice=YES&clearForm=clearForm&isGeneralCAP=Y&spaceName=spaces.' +         V_RECORD.AGENCY_ID + '.' +         (SELECT             STRING_AGG(T.value, '') WITHIN GROUP (ORDER BY T.value desc) together         FROM (            SELECT LOWER(value) value FROM STRING_SPLIT(V_RECORD.RECORD_ID, '-')         ) T)         + '\">' + V_RECORD.RECORD_ID + '</a>'     ) Hyperlink  FROM  V_RECORD INNER JOIN  BDOCUMENT ON   1=1  AND BDOCUMENT.SERV_PROV_CODE = V_RECORD.AGENCY_ID  AND BDOCUMENT.B1_PER_ID1 = V_RECORD.T_ID1  AND BDOCUMENT.B1_PER_ID2 = V_RECORD.T_ID2  AND BDOCUMENT.B1_PER_ID3 = V_RECORD.T_ID3  WHERE  1=1  AND V_RECORD.AGENCY_ID = 'SANTABARBARA'  AND V_RECORD.RECORD_TYPE_GROUP IN ('Building','Fire')  AND V_RECORD.RECORD_STATUS IN (  'Corrections Needed',  'Corrections Required',  'Plans Returned to Applicant',  'Returned to Applicant',  'Waiting on Applicant'  )  AND BDOCUMENT.DOC_SEQ_NBR > 0  AND BDOCUMENT.FILE_UPLOAD_DATE > V_RECORD.RECORD_STATUS_DATE  AND BDOCUMENT.FILE_UPLOAD_BY LIKE '%PUBLIC%' ORDER BY V_RECORD.RECORD_ID`));
```

Here is the error I am seeing:

> Uncaught SyntaxError: Expected "#", ",", "--", "/*", ";", "FOR", "FROM", "GO", "GROUP", "HAVING", "INTERSECT", "INTO", "LIMIT", "LOCK", "MINUS", "ORDER", "UNION", "WHERE", "WINDOW", [ \t\n\r], or end of input but "I" found.

version 4.8.0

**Comment by taozhi8833998** [comment]
@joshcarey1 which dialect? BTW, please format the SQL.

**Comment by joshcarey1** [comment]
@taozhi8833998 This is SQL Server TSQL. Does the formatting matter, or just for here?

`SELECT
	[V_RECORD].[RECORD_ID] [Record ID]
	,(SELECT LOGO_CONTENT FROM RSERV_LOGO WHERE 1=1 AND SERV_PROV_CODE = 'SANTABARBARA' AND LOGO_TYPE = 'Report Header') Logo
	,[V_RECORD].[RECORD_STATUS] [Record Status]
	,BDOCUMENT.DOC_NAME [DOC NAME]
	,BDOCUMENT.FILE_UPLOAD_DATE [UPLOAD DATE]
	,V_RECORD.RECORD_STATUS_DATE [APPLICATION STATUS DATE]
	,(
        '<a href="' +
        DBO.FN_GET_STDCHOICE_VALUEDESC(V_RECORD.AGENCY_ID,'ACA_CONFIGS','V360_WEB_ACTION_URL') +
        'cap/capsummary/CapTabSummary.do?mode=activateSpace&serviceProviderCode=' +
        V_RECORD.AGENCY_ID +
        '&ID1=' + V_RECORD.T_ID1 +
        '&ID2=' + V_RECORD.T_ID2 +
        '&ID3=' + V_RECORD.T_ID3 +
        '&requireNotice=YES&clearForm=clearForm&isGeneralCAP=Y&spaceName=spaces.' +
        V_RECORD.AGENCY_ID + '.' +
        (SELECT
            STRING_AGG(T.value, '') WITHIN GROUP (ORDER BY T.value desc) together
        FROM (
           SELECT LOWER(value) value FROM STRING_SPLIT(V_RECORD.RECORD_ID, '-')
        ) T)
        + '">' + V_RECORD.RECORD_ID + '</a>'
    ) Hyperlink

FROM
	V_RECORD
INNER JOIN
	BDOCUMENT ON 
	1=1
	AND BDOCUMENT.SERV_PROV_CODE = V_RECORD.AGENCY_ID
	AND BDOCUMENT.B1_PER_ID1 = V_RECORD.T_ID1
	AND BDOCUMENT.B1_PER_ID2 = V_RECORD.T_ID2
	AND BDOCUMENT.B1_PER_ID3 = V_RECORD.T_ID3

WHERE
	1=1
	AND V_RECORD.AGENCY_ID = 'SANTABARBARA'
	AND V_RECORD.RECORD_TYPE_GROUP IN ('Building','Fire')
	AND V_RECORD.RECORD_STATUS IN (
	'Corrections Needed',
	'Corrections Required',
	'Plans Returned to Applicant',
	'Returned to Applicant',
	'Waiting on Applicant'
	)
	AND BDOCUMENT.DOC_SEQ_NBR > 0
	AND BDOCUMENT.FILE_UPLOAD_DATE > V_RECORD.RECORD_STATUS_DATE
	AND BDOCUMENT.FILE_UPLOAD_BY LIKE '%PUBLIC%'
ORDER BY V_RECORD.RECORD_ID`

**Comment by taozhi8833998** [comment]
@joshcarey1 please specify the database option.

```
const parser = new Parser()
const opt = { database: 'transactsql'  }
const ast = parser.astify(sql, opt)
```

**Comment by joshcarey1** [comment]
@taozhi8833998 Similar error

     const parser = new Parser();
      const opt = { database: 'transactsql'  }      
      console.log(parser.astify(`SELECT   V_RECORD . RECORD_ID   Record ID   ,(SELECT LOGO_CONTENT FROM RSERV_LOGO WHERE 1=1 AND SERV_PROV_CODE = 'SANTABARBARA' AND LOGO_TYPE = 'Report Header') Logo  , V_RECORD . RECORD_STATUS   Record Status   ,BDOCUMENT.DOC_NAME  DOC NAME   ,BDOCUMENT.FILE_UPLOAD_DATE  UPLOAD DATE   ,V_RECORD.RECORD_STATUS_DATE  APPLICATION STATUS DATE   ,(         '<a href=\"' +         DBO.FN_GET_STDCHOICE_VALUEDESC(V_RECORD.AGENCY_ID,'ACA_CONFIGS','V360_WEB_ACTION_URL') +         'cap/capsummary/CapTabSummary.do?mode=activateSpace&serviceProviderCode=' +         V_RECORD.AGENCY_ID +         '&ID1=' + V_RECORD.T_ID1 +         '&ID2=' + V_RECORD.T_ID2 +         '&ID3=' + V_RECORD.T_ID3 +         '&requireNotice=YES&clearForm=clearForm&isGeneralCAP=Y&spaceName=spaces.' +         V_RECORD.AGENCY_ID + '.' +         (SELECT             STRING_AGG(T.value, '') WITHIN GROUP (ORDER BY T.value desc) together         FROM (            SELECT LOWER(value) value FROM STRING_SPLIT(V_RECORD.RECORD_ID, '-')         ) T)         + '\">' + V_RECORD.RECORD_ID + '</a>'     ) Hyperlink  FROM  V_RECORD INNER JOIN  BDOCUMENT ON   1=1  AND BDOCUMENT.SERV_PROV_CODE = V_RECORD.AGENCY_ID  AND BDOCUMENT.B1_PER_ID1 = V_RECORD.T_ID1  AND BDOCUMENT.B1_PER_ID2 = V_RECORD.T_ID2  AND BDOCUMENT.B1_PER_ID3 = V_RECORD.T_ID3  WHERE  1=1  AND V_RECORD.AGENCY_ID = 'SANTABARBARA'  AND V_RECORD.RECORD_TYPE_GROUP IN ('Building','Fire')  AND V_RECORD.RECORD_STATUS IN (  'Corrections Needed',  'Corrections Required',  'Plans Returned to Applicant',  'Returned to Applicant',  'Waiting on Applicant'  )  AND BDOCUMENT.DOC_SEQ_NBR > 0  AND BDOCUMENT.FILE_UPLOAD_DATE > V_RECORD.RECORD_STATUS_DATE  AND BDOCUMENT.FILE_UPLOAD_BY LIKE '%PUBLIC%' ORDER BY V_RECORD.RECORD_ID`,opt));

> Uncaught SyntaxError: Expected "#", ",", "--", "/*", ";", "FOR", "FROM", "GO", "GROUP", "HAVING", "LIMIT", "ORDER", "UNION", "WHERE", [ \t\n\r], or end of input but "I" found.

**Comment by taozhi8833998** [comment]
@joshcarey1 please upgrade to the latest version, and try again.

**Comment by joshcarey1** [comment]
@taozhi8833998 I am on version 4.8.0. I did an update and it says I am on the current version.

**Comment by taozhi8833998** [comment]
@joshcarey1 Can you show me the full codes?
