### ISSUE TITLE
CREATE TYPE does not respect created type.

### ISSUE THREAD

**Issue by Kevin101Zhang** [taozhi8833998/node-sql-parser#1796]
**Describe the bug**
CREATE TYPE does not respect created type. Creation of type succeed but later when using the type as a column it will error.

**Database Engine**
PostgreSQL.

**To Reproduce**
-the SQL that be parsed
-the node-sql-parser version
-the node version

CREATE TYPE access_key_permission_kind AS ENUM ('FULL_ACCESS', 'FUNCTION_CALL');

CREATE TABLE
  access_keys (
    public_key text NOT NULL,
    account_id text NOT NULL,
    permission_kind access_key_permission_kind NOT NULL,
    CONSTRAINT access_keys_pk PRIMARY KEY (public_key, account_id)
  )

**Expected behavior**
access_key_permission_kind exist due to create type as enum.

**Screenshots**
<img width="648" alt="Screenshot 2024-02-12 at 2 46 12 PM" src="https://github.com/taozhi8833998/node-sql-parser/assets/42101107/350aca4f-f3af-45f9-9a68-6c8f44c04983">
<img width="985" alt="Screenshot 2024-02-12 at 2 47 01 PM" src="https://github.com/taozhi8833998/node-sql-parser/assets/42101107/77fa0156-c0bd-4b74-8835-be049cf1c7ff">

**Additional context**
"node-sql-parser": "4.18.0", 

rawschema from log 
'CREATE TYPE
  access_key_permission_kind AS ENUM('FULL_ACCESS', 'FUNCTION_CALL');

CREATE TABLE
  access_keys (
    public_key text NOT NULL,
    account_id text NOT NULL,
    created_by_receipt_id text NULL,
    deleted_by_receipt_id text NULL,
    permission_kind access_key_permission_kind NOT NULL CONSTRAINT access_keys_pk PRIMARY KEY (public_key, account_id)
  )'

TEST:

 **{
      title: 'create type as enum and use type as tablename',
      sql: [
        `CREATE TYPE access_key_permission_kind AS ENUM (
          'A',
          'B'
        );
        CREATE TABLE access_keys(id SERIAL PRIMARY KEY, name VARCHAR, permission_kind access_key_permission_kind);
        `,
        `CREATE TYPE "access_key_permission_kind" AS ENUM ('A', 'B'); CREATE TABLE access_keys(id SERIAL PRIMARY KEY, name VARCHAR, permission_kind access_key_permission_kind);`
      ]
    },**

**Comment by taozhi8833998** [comment]
@Kevin101Zhang supported custom data type now. Sorry for the late reply.

**Comment by Kevin101Zhang** [comment]
Nice! I actually cloned and have been trying to make progress in your repo for the past 2 days. It was my first time learning a pegjs so it was very informative to dig through your code. Thanks you for taking care of it. I also noticed it does not recognize partitions as this was the full schema. If there is a roadmap with this feature It would be great if you could link it here. Also would be happy to learn how you're introducing these changes since they are very informative to look at.

CREATE TYPE access_key_permission_kind AS ENUM ('FULL_ACCESS', 'FUNCTION_CALL');

CREATE TABLE
  access_keys (
    public_key text NOT NULL,
    account_id text NOT NULL,
    created_by_receipt_id text NULL,
    deleted_by_receipt_id text NULL,
    permission_kind access_key_permission_kind NOT NULL,
    last_update_block_height numeric(20) NOT NULL,
    CONSTRAINT access_keys_pk PRIMARY KEY (public_key, account_id)
  )
PARTITION BY HASH (public_key); //**Will fail here after the fix**
CREATE INDEX access_keys_account_id_idx ON access_keys USING btree (account_id);
CREATE INDEX access_keys_last_update_block_height_idx ON access_keys USING btree (last_update_block_height);
CREATE INDEX access_keys_public_key_idx ON access_keys USING btree (public_key);

CREATE TABLE access_keys_hash_p0 PARTITION OF access_keys FOR VALUES WITH (modulus 10, remainder 0);
CREATE TABLE access_keys_hash_p1 PARTITION OF access_keys FOR VALUES WITH (modulus 10, remainder 1);
CREATE TABLE access_keys_hash_p2 PARTITION OF access_keys FOR VALUES WITH (modulus 10, remainder 2);
CREATE TABLE access_keys_hash_p3 PARTITION OF access_keys FOR VALUES WITH (modulus 10, remainder 3);
CREATE TABLE access_keys_hash_p4 PARTITION OF access_keys FOR VALUES WITH (modulus 10, remainder 4);
CREATE TABLE access_keys_hash_p5 PARTITION OF access_keys FOR VALUES WITH (modulus 10, remainder 5);
CREATE TABLE access_keys_hash_p6 PARTITION OF access_keys FOR VALUES WITH (modulus 10, remainder 6);
CREATE TABLE access_keys_hash_p7 PARTITION OF access_keys FOR VALUES WITH (modulus 10, remainder 7);
CREATE TABLE access_keys_hash_p8 PARTITION OF access_keys FOR VALUES WITH (modulus 10, remainder 8);
CREATE TABLE access_keys_hash_p9 PARTITION OF access_keys FOR VALUES WITH (modulus 10, remainder 9);

**Comment by taozhi8833998** [comment]
@Kevin101Zhang supported the `partition by` clause in the create table SQL syntax, check the above pr again.

**Comment by Kevin101Zhang** [comment]
Hey! Take your time here, but I'm curious if there's a release scheduled in the near future. I observed that your release history is somewhat spontaneous, so I'm interested to know when the next release is anticipated.

**Comment by taozhi8833998** [comment]
@Kevin101Zhang You can see the 5.0.0 milestone.
