### ISSUE TITLE
astify throws 'Syntax Error' in TransactSQL on fully-qualiffied column names 

### ISSUE THREAD

**Issue by religiosa1** [taozhi8833998/node-sql-parser#1797]
**Describe the bug**
`new Parser().astify(query,  { database: 'transactsql' })` throws a `Syntax Error`, if some of the columns in the `query`  supplied in fully-qualified form, such as:

- `db.schema.table.column`
- `schema.table.column`
- `[db].[schema].[table].[column]`
- `[schema].[table].[column]`

Only `table.column` or `column` seem to work.

**Database Engine**
Occurs on TransactSQL engine.

**To Reproduce**
The simplest SQL that can be used to reproduce the error:

```sql
SELECT dbo.movie.id FROM dbo.movie
```

Can also be reproduced with a database specified:

```sql
SELECT source.dbo.movie.id FROM source.dbo.movie
```

Or in WHERE clause:

```sql
SELECT * FROM source.dbo.movie WHERE source.dbo.movie.genre_id = 1
```

Removing schema and database will make the query work:

```sql
-- the SQL bellow can be parsed without issues:
SELECT movie.id FROM source.dbo.movie
```

Reproduced on node-sql-parser@4.18.0 on Node 18.16.0 and Node 20.10.0

**Expected behavior**
Correctly parsed `column` object with `schema` and `table` parsed as required.

**Actual behavior**
Throws a syntax error:
```
[SyntaxError]: Expected "!=", "#", "%", "&&", "'", "(", "*", "+", ",", "-", "--", "/", "/*", ";", "<", "<=", "<>", "=", ">", ">=", "AND", "AS", "BETWEEN", "FOR", "FROM", "GO", "GROUP", "HAVING", "IN", "IS", "LIKE", "LIMIT", "NOT", "OR", "ORDER", "UNION", "WHERE", "[", "\"", "`", "||", [ \t\n\r], [A-Za-z0-9_:], [A-Za-z0-9_\-@$], [A-Za-z_@#], or end of input but "." found.
```

```
at no (C:\Users\...\node-sql-parser-test\node_modules\node-sql-parser\index.js:1:1082579)
    at Object.parse [as transactsql] (C:\Users\...\node_modules\node-sql-parser\index.js:1:1216728)
    at r.value (C:\Users\...\node_modules\node-sql-parser\index.js:1:1793421)
    at r.value (C:\Users\...\node_modules\node-sql-parser\index.js:1:1792975)
```

**Additional context**
Schema and [] brackets are automatically added in our application with the query builder we're using. 
SQL server is totally ok with queries like that.

We can probably cut it away with a regex as a workaround, but that seems hacky.

**Comment by taozhi8833998** [comment]
@religiosa1 ok, fixed it.g

**Comment by religiosa1** [comment]
@taozhi8833998 No worries, thank you for the good work.

I tested the branch `fix-column-full-qualified-tsql`, fully-qualified names work fine there.

Looking forward for the release.
