### ISSUE TITLE
Support Redshift QUALIFY

### ISSUE THREAD

**Issue by LaizaAngrest** [taozhi8833998/node-sql-parser#1799]
**Describe the bug**
Currently, there is no support for query with QUALIFY in Redshift (in Postgres it's not a valid syntax)

**Database Engine**
Redshift

**To Reproduce**
`SELECT sf_account_id, date_trunc('week', date_) as week_id, date_trunc('month', date_) as month_id, Last_VALUE(hermes_health_score IGNORE NULLS) OVER ( partition by sf_account_id, week_id ) as hermes_health_score, Last_VALUE(hermes_health_score IGNORE NULLS) OVER ( partition by sf_account_id, month_id ) as hermes_health_score_monthly, 
row_number() OVER ( PARTITION BY sf_account_id, date_trunc('week', date_) ORDER BY date_ desc ) AS o_key_week 
FROM dwh.dwh_health_score_hermes 
WHERE date_trunc('month', date_) >= '2023-01-01' 
Qualify o_key_week = 1`

**Expected behavior**
A valid query

**Comment by taozhi8833998** [comment]
@LaizaAngrest add a new database option redshift now, supporting the QUALIFY syntax. I will open a pr later.
