### ISSUE TITLE
Support for Microsoft SQL Server

### ISSUE THREAD

**Issue by viduni94** [taozhi8833998/node-sql-parser#1807]
Would be great to see support for Microsoft SQL Server to convert SQL to AST.

**Comment by taozhi8833998** [comment]
@viduni94 support Transact SQL, you can specify the database option.

**Comment by viduni94** [comment]
Hi @taozhi8833998 
I tried `transactsql` as the database option, but an error occurs when trying to pass this SQL:

```
SELECT TOP 1000 "production"."categories"."category_name", COUNT("production"."products"."product_id") AS "product_count"\n' +
      'FROM "production"."products"\n' +
      'INNER JOIN "production"."categories" ON "production"."products"."category_id" = "production"."categories"."category_id"\n' +
      'GROUP BY "production"."categories"."category_name"'
```

**Comment by taozhi8833998** [comment]
@viduni94 Sorry about that, you can open a new issue for that, I will fix it asap.

**Comment by viduni94** [comment]
Thanks for the response @taozhi8833998 
I was able to run the query with double quotes on the database. However, I'm able to work with the syntax you suggested. Thank you.
