### ISSUE TITLE
support updating JSON using subscripting

### ISSUE THREAD

**Issue by zcappp** [taozhi8833998/node-sql-parser#1817]
Is there any plan to support updating JSON using subscripting introduced on pgsql version 14? https://www.postgresql.org/docs/14/datatype-json.html#JSONB-SUBSCRIPTING

such as instead of update the whole field data:
`UPDATE blogs SET data = jsonb_set(data, '{author, last_name}', '"Sarah"')`
we can update only part of it:
`UPDATE blogs SET data['author']['first_name'] = '"Sarah"'`

by the way, I noticed the node-sql-parser already well support selecting JSON using subscripting:
`SELECT data['author']['first_name'] as title FROM blogs`

**Comment by taozhi8833998** [comment]
@zcappp supported.
