### ISSUE TITLE
MISSING KEYWORD ILIKE in postgre SQL

### ISSUE THREAD

**Issue by hdlinh1808** [taozhi8833998/node-sql-parser#1819]
**Describe the bug**
Missing keyword ILIKE

**Database Engine**
 PostgreSQL.

**To Reproduce**
when I query: select state_code from aws_ec2_instance where state_code ILIKE '123'
it throws an exception

**Expected behavior**

**Screenshots**
![image](https://github.com/taozhi8833998/node-sql-parser/assets/56437153/496cb4e2-9c7b-4c99-bc14-8128534594fd)

**Comment by taozhi8833998** [comment]
@hdlinh1808 If you are using PostgreSQL, please specify the `database` options, otherwise will be MySQL by default.
