### ISSUE TITLE
Add support for GROUP BY using column numbers

### ISSUE THREAD

**Issue by victorbadila** [taozhi8833998/node-sql-parser#182]
Hi, while it seems standard grouping is supported I have stumbled on errors when trying to parse statements that use column numbers for grouping. Consider the following example:
```
const statement = `
SELECT name, gender
FROM Test.student
GROUP BY 1, 2;
`;

var { Parser } = require("node-sql-parser")
const parser = new Parser()
const ast = parser.astify(statement);
```

**Comment by taozhi8833998** [comment]
try `1.7.0` version

**Comment by victorbadila** [comment]
Does not throw error anymore, thanks!
