### ISSUE TITLE
Support Athena parser

### ISSUE THREAD

**Issue by LaizaAngrest** [taozhi8833998/node-sql-parser#1820]
**Describe the bug**
Currently, there is no Athena parser available, so we use Hive. However, the query below is invalid (indeed invalid for Hive).

**Database Engine**
Athena

**To Reproduce**
```
SELECT
  sessionId session_id,
  organizationName organization,
  appMode note_type,
  rating note_rating,
  therapistId therapist_id,
  distinct_id email,
  FROM_UNIXTIME((mp_processing_time_ms / 1000)) last_updated_ts,
  source,
  CAST(json_parse (selectedSubTags) AS ARRAY (varchar)) note_rating_tags,
  description rating_description
FROM
  events_mp_master_event
WHERE
  (mp_event_name = 'submit feedback clicked')
```

**Expected behavior**
Support Athena parser

**Comment by taozhi8833998** [comment]
@LaizaAngrest I will add it based on hive parser

**Comment by darzIdo** [comment]
@LaizaAngrest @taozhi8833998 If you're using Athena Query edtior, which is using the Trino SQL dialect - what you're looking for is probably here https://github.com/taozhi8833998/node-sql-parser/pull/1680
