### ISSUE TITLE
Add support for BigQuery type casting

### ISSUE THREAD

**Issue by victorbadila** [taozhi8833998/node-sql-parser#183]
This is mainly a syntax coverage extension request, I know BigQuery is not listed among the supported sql syntaxes, but this library is the closest I got to actually parsing complex BigQuery statements properly. Would it be possible to add support for casting to BigQuery types like in the following example?
```
select CAST(1 AS INT64) from mytable;
```
The conversion rules use din big query seem are the following: https://cloud.google.com/bigquery/docs/reference/standard-sql/conversion_rules

**Comment by taozhi8833998** [comment]
try `1.7.0` version

**Comment by victorbadila** [comment]
Does not throw error anymore, thanks

**Comment by mx2323** [comment]
How is this library with bigquery syntax?

**Comment by taozhi8833998** [comment]
I didn't separate it from `MySQL`, but I will do it if required.

**Comment by taozhi8833998** [comment]
> How is this library with bigquery syntax?

I didn't separate it from `MySQL`, but I will do it if required.
