### ISSUE TITLE
Next release date ETA

### ISSUE THREAD

**Issue by eXigentCoder** [taozhi8833998/node-sql-parser#1834]
Hey there, thanks so much for all the improvements!
Not trying to rush you, just wanted to know if you have an ETA for the next release so I can plan around it?

**Comment by taozhi8833998** [comment]
@eXigentCoder will be released in this weekend. Sorry for keep waiting

**Comment by eXigentCoder** [comment]
Not a problem at all, thank you again!

**Comment by taozhi8833998** [comment]
@eXigentCoder `5.0.0` has been released, please check it.

**Comment by eXigentCoder** [comment]
Awesome work, thank you so much!
