### ISSUE TITLE
Add support for INTERVAL with expressions as values

### ISSUE THREAD

**Issue by victorbadila** [taozhi8833998/node-sql-parser#184]
While the standard use of INTERVAL is supported in queries such as:
```
SELECT DATE_ADD(CURRENT_DATE(), INTERVAL 2 MONTH);
```
I get errors when the value for the interval is an expression such as:
```
SELECT DATE_ADD(CURRENT_DATE(), INTERVAL 1+1 MONTH);
```
or (closer to where I actually get the error):
```
SELECT DATE_ADD(CURRENT_DATE(), INTERVAL myaliastable.mycolumn+1 MONTH);
```
While the scripts that I'm parsing are in BigQuery I have tried the examples in MySQL as well and they get executed well.

**Comment by taozhi8833998** [comment]
try `1.7.0` version

**Comment by victorbadila** [comment]
Does not throw error anymore, thanks!
