### ISSUE TITLE
Errors when parsing column modification with before/after in the suffix

### ISSUE THREAD

**Issue by zwallacedev** [taozhi8833998/node-sql-parser#1864]
**Describe the bug**
When using "ALTER TABLE `product` MODIFY COLUMN `type` enum('one','two') NOT NULL AFTER `name`", parser throws error:
SyntaxError: Expected "#", ",", "--", "/*", ";", "AS", "AUTO_INCREMENT", "CHARACTER", "CHECK", "COLLATE", "COLUMN_FORMAT", "COMMENT", "CONSTRAINT", "DEFAULT", "GENERATED", "GO", "KEY", "NOT NULL", "NULL", "ON", "PRIMARY", "REFERENCES", "STORAGE", "UNIQUE", [ \t\n\r], or end of input but "A" found.

**Database Engine**
MySQL

**To Reproduce**
- the SQL that be parsed: "ALTER TABLE `product` MODIFY COLUMN `type` enum('one','two') NOT NULL AFTER `name`"
- node-sql-parser version: 5.0.0
- node version: v20

**Expected behavior**
This should parse correctly, and it should accept "AFTER" as part of the suffix.

**Additional context**
The "After" is not important, but I am using this to run against a large set of migrations that may or may not have before/after column modifications in there.

**Comment by zwallacedev** [comment]
FWIW - I cloned the repo locally, and I was attempting to run the tests on this, but when running `npm install`, I was getting errors as well:

```
npm ERR! code CERT_HAS_EXPIRED
npm ERR! errno CERT_HAS_EXPIRED
npm ERR! request to https://registry.npm.taobao.org/url/download/url-0.11.0.tgz failed, reason: certificate has expired

npm ERR! A complete log of this run can be found in: /Users/nearpoduser/.npm/_logs/2024-04-11T00_14_47_539Z-debug-0.log
```

**Comment by taozhi8833998** [comment]
@zwallacedev Sorry for the expired link. I have fixed the issue and the `npm install` error, you can get the latest codes later.

**Comment by zwallacedev** [comment]
Thank you so much! I will do my best to add some contribution to your project. This has been super useful for me 👍
