### ISSUE TITLE
[QUESTION] What is required for release of 5.1.0?

### ISSUE THREAD

**Issue by zwallacedev** [taozhi8833998/node-sql-parser#1874]
There are changes I need within the release tagged with 5.1.0. Is there a timeline for this?

Side note: have you thought about implementing automatic changelog, automated versioning, and automated package deployment?

- We have done this in a corporate enterprise solution that turned out to be fairly simple with the use of commitlint / github actions. Lmk if this is something you are interested in.

**Comment by taozhi8833998** [comment]
1. `5.1.0` will be released in the next week, you can get it from the milestone
2. when a new tag is released, the change log will be generated automatically and be published to the npm and github registry by github action. 
3. but the version is not automated, how can we do that? can you share it.

**Comment by zwallacedev** [comment]
Yep! I'll submit an MR in the next few days for you.

**Comment by taozhi8833998** [comment]
@zwallacedev Thanks for your help. BTW, you can share the idea first, and code later.
