### ISSUE TITLE
DROP VIEW not supported in build/sqlite

### ISSUE THREAD

**Issue by carloslfu** [taozhi8833998/node-sql-parser#1927]
DROP VIEW statement is not supported by SQLite build. Here is an example:

```sql
DROP VIEW IF EXISTS view_name;
```

The error that appears is:
```
[SyntaxError]: Expected "#", "--", "/*", ":=", "=", "INDEX", "TABLE", or [ \t\n\r] but "V" found.
    at peg$buildStructuredError (/Users/taozhi/Workspaces/OpenSources/node-sql-parser/pegjs/sqlite.pegjs:2548:12)
    at typeCase (/Users/taozhi/Workspaces/OpenSources/node-sql-parser/pegjs/sqlite.pegjs:24598:11)
```

I'd like to help with this one as it looks very similar to #1694 and I could use what you did to solve it via #1695 @taozhi8833998. This seems like a good start for me since I'll be using this library a lot and would like to contribute to it. WDYT?

**Comment by taozhi8833998** [comment]
@carloslfu Thank you for participating. I will release an update today, so I resolved it by myself. Please review the PR codes to ensure alignment with your intended codes.

**Comment by carloslfu** [comment]
This is great! Thank you! I just checked it. It looks good!
