### ISSUE TITLE
DROP TABLE IF EXISTS not supported in build/Postgres

### ISSUE THREAD

**Issue by carloslfu** [taozhi8833998/node-sql-parser#1933]
DROP TABLE IF EXISTS statement is not supported by the Postgres build. Here is an example:

`DROP TABLE IF EXISTS table_name;`

The error that appears is:

![Screenshot 2024-06-03 at 9 11 05 PM](https://github.com/taozhi8833998/node-sql-parser/assets/5993168/7f060950-a7a5-435e-b108-4fb06b2db7db)

**Comment by taozhi8833998** [comment]
@carloslfu Sorry for that, fixed it.
