### ISSUE TITLE
npm run build command fails

### ISSUE THREAD

**Issue by create-new-entity** [taozhi8833998/node-sql-parser#1946]
**Describe the bug**
When attempted to build with the _**npm run build**_ command, it fails.

**Database Engine**
N/A

**To Reproduce**
-the node-sql-parser version: 5.2.0
-the node version: 16.20.2
- run **_npm run build_** command from root of the project.

**Expected behavior**
Build should not fail. It should produce content in the output folder.

**Screenshots**
<img width="751" alt="Screen Shot 2024-06-10 at 12 49 12 AM" src="https://github.com/taozhi8833998/node-sql-parser/assets/9401409/f147d5f2-d169-406f-9703-401275689ad4">

**Additional context**
Probably it has something to do with these changes: https://github.com/taozhi8833998/node-sql-parser/commit/a80e19df879a038ab3cfc59a2044fab8fe2208e4

**Comment by taozhi8833998** [comment]
@create-new-entity Sorry for that, fixed it.
