### ISSUE TITLE
Square brackets not recognized for CREATE DATABASE in t-sql

### ISSUE THREAD

**Issue by 1ilit** [taozhi8833998/node-sql-parser#1992]
**Describe the bug**
Throws syntax error when the name of the database in CREATE DATABASE is in square brackets

**Database Engine**
Transact-SQL.

**To Reproduce**
-the SQL that be parsed
```sql
CREATE DATABASE [MyDatabase];
```
-the node-sql-parser version
v5.2.0
-the node version
v20.11.0

**Expected behavior**
Parse successfully

**Comment by taozhi8833998** [comment]
@1ilit It can parse the sql.

```javascript
const sql = 'CREATE DATABASE [MyDatabase];'
const { Parser } = require('node-sql-parser')
const parser = new Parser()
const ast = parser.astify(sql, { database: 'transactsql'  }) // please specified the database option
console.log(ast)
```
I will close the issue. If you still have problems, please reopen it, and show the codes you use.
