### ISSUE TITLE
Support type casting in postgresql

### ISSUE THREAD

**Issue by 1ilit** [taozhi8833998/node-sql-parser#2020]
It would be great if type casting was recognized when parsing.
 
**Database Engine**
PostgreSQL

**To Reproduce**
-the SQL that be parsed
```sql
CREATE TABLE public.tnotok (
    description text DEFAULT ''::text NOT NULL
);
```
**Expected behavior**
Produce ast

**Comment by taozhi8833998** [comment]
@1ilit fixed it.

**Comment by 1ilit** [comment]
Thanks!
