### ISSUE TITLE
SQLite Issues

### ISSUE THREAD

**Issue by ad-si** [taozhi8833998/node-sql-parser#2024]
- [x] `sqlify()` should use `"` instead of <code>`</code> for keywords as this is not standard SQL. Backticks are used by MySQL and are included in SQLite only for compatibility.
- [x] SQLite allows `==`, but it currently causes an error. E.g.:
    ```js
    parser.astify(
      "SELECT * FROM sqlite_master WHERE name == 'test'",
      { database: "sqlite" }
    )
    ```
- [x] SQLite supports subqueries. This SQL query, however, can't be parsed:
  ```sql
  SELECT SUM("Hours Spent") AS "Total Hours"
  FROM "Work_Records"
  WHERE "Partner ID" =
    (SELECT "Partner ID"
    FROM "Employees"
    WHERE "Firstname" = 'John' AND "Lastname" = 'Smith')
  ```

**Comment by taozhi8833998** [comment]
@ad-si sorry for the bugs and will resolve them promptly.

**Comment by taozhi8833998** [comment]
@ad-si Corrected everything.
