### ISSUE TITLE
Failed to parse when sql param contains OFFSET in front of LIMIT or contains OFFSET without any LIMIT

### ISSUE THREAD

**Issue by fauzialhari** [taozhi8833998/node-sql-parser#203]
I found issue when trying to do parser.astify this valid sql statement:
`SELECT Name, Region FROM table123 offset 1 limit 20`
`SELECT Name, Region FROM table123 offset 1`
it returns undefined and throws error

but it's working fine when parsing this:
`SELECT Name, Region FROM table123 limit 20 offset 1`

**Comment by taozhi8833998** [comment]
Could you specify which database supports the gramma that offset before the limit?  I found it not valid in MySQL. If I am wrong please correct me!

**Comment by taozhi8833998** [comment]
@fauzialhari ？？？

**Comment by fauzialhari** [comment]
Hi, @taozhi8833998 , sorry I 've made mistake I've just found out that we are using MS SQL server instead of MySQL and in MS SQL its a valid statement to use offset in front of limit
