### ISSUE TITLE
When is the next release incoming?

### ISSUE THREAD

**Issue by adamtowerz** [taozhi8833998/node-sql-parser#2033]
There's been a lot of great bug fixes and improvements that we're excited to start using them (& a big thank you for the continued development of this library)! Was wondering when the next release is?

Sorry for making an issue but wasn't sure if there was a better medium.

**Comment by taozhi8833998** [comment]
@adamtowerz Thank you for your patience; I will release it tomorrow.

**Comment by taozhi8833998** [comment]
@adamtowerz Version 5.3.0 has been released.
