### ISSUE TITLE
Parser throws syntax error on custom type in quotes in PostgreSQL

### ISSUE THREAD

**Issue by 1ilit** [taozhi8833998/node-sql-parser#2045]
**Describe the bug**
`astify()` throws syntax error on custom type in quotes in PostgreSQL

**Database Engine**
PostgreSQL

**To Reproduce**
-the SQL that be parsed
This is ok
```sql
CREATE TYPE "Gender" AS ENUM ('F', 'M', 'U');

CREATE TABLE "User" (
    "gender" Gender NOT NULL
);
```
This throws an error
```sql
CREATE TYPE "Gender" AS ENUM ('F', 'M', 'U');

CREATE TABLE "User" (
    "gender" "Gender" NOT NULL
);
```
-the node-sql-parser version
v5.3.0
-the node version
v18.20.3

**Expected behavior**
Produce ast

**Additional context**
https://stackblitz.com/edit/stackblitz-starters-9dpxty?file=index.js

**Comment by taozhi8833998** [comment]
@1ilit fixed
