### ISSUE TITLE
Parser throws syntax error on named primary key constraints in PostgreSQL 

### ISSUE THREAD

**Issue by 1ilit** [taozhi8833998/node-sql-parser#2046]
**Describe the bug**
`astify()` throws syntax error on named primary key constraints in PostgreSQL 

**Database Engine**
PostgreSQL

**To Reproduce**
-the SQL that be parsed
```sql
CREATE TABLE users (
    "id" SERIAL CONSTRAINT users_PK PRIMARY KEY
);
```
-the node-sql-parser version
v5.3.0
-the node version
v18.20.3

**Expected behavior**
Produce ast

**Additional context**
https://stackblitz.com/edit/stackblitz-starters-3nslzy?file=index.js

**Comment by taozhi8833998** [comment]
@1ilit fixed it

**Comment by 1ilit** [comment]
thank you!
