### ISSUE TITLE
Paring BigQuery `CREATE VIEW` ddl parsing does not work

### ISSUE THREAD

**Issue by J4cku** [taozhi8833998/node-sql-parser#2047]
**Describe the bug**
Exception is thrown when trying to astify BigQuery `CREATE VIEW` SQL

**Database Engine**
BigQuery

**To Reproduce**
```
CREATE OR REPLACE VIEW `project`.`database`.`schema` AS (SELECT
    employee_id,
    first_name,
    last_name,
    salary,
    hire_date,
    modified
FROM
    database.table
WHERE salary > 50000.00)
```
-the node-sql-parser version: 5.3.0
-the node version: v18.18.2

**Expected behavior**
Should parse correctly

**Comment by taozhi8833998** [comment]
@J4cku fixed it.
