### ISSUE TITLE
`WHERE` clause JSONB operator should yield a `binary_expr`

### ISSUE THREAD

**Issue by adamtowerz** [taozhi8833998/node-sql-parser#2051]
**Describe the bug**
In a `WHERE` clause I would expect a binary JSONB operator to create a `binary_expr` node instead of being a field on a column reference.

**Database Engine**
PostgreSQL.

**To Reproduce**
```sql
SELECT "company".name AS "company:name"
FROM "company"
WHERE ("company".categories @> '[{"items": ["Fishery"]}]')
```

yields a `where` AST value of 
```json
{
  "type": "column_ref",
  "table": "company",
  "column": {
    "expr": {
      "type": "default",
      "value": "categories"
    }
  },
  "jsonb": [
    {
      "type": "jsonb",
      "op": "@>",
      "right": {
        "type": "expr",
        "expr": {
          "type": "single_quote_string",
          "value": "[{\"items\": [\"Fishery\"]}]"
        }
      }
    }
  ],
  "parentheses": true
}
```

**Expected behavior**
I would expect a binary_expr node to match the general convention of comparison fields within `WHERE` clauses. Although if there's a reason I don't quite understand for why it is like this do let me know.

**Comment by adamtowerz** [comment]
Also this column ref doesn't have a `loc` even when includeLocations is true. It would be super helpful if it did!

**Comment by adamtowerz** [comment]
@taozhi8833998, if this is a bug fix is it possible to get a patch release for it? This parsing is pretty important in our workflow as we use a lot of JSONB columns for names/dates. Otherwise, is it possible to get an eta on 5.4.0? Really appreciate your hard work here, the PR looks like magic so I appreciate it a lot.

**Comment by taozhi8833998** [comment]
@adamtowerz I will release it today.

**Comment by taozhi8833998** [comment]
@adamtowerz You can now upgrade to the latest version 5.3.1. If you have any problems, please don't hesitate to let me know. Thanks.

**Comment by taozhi8833998** [comment]
@adamtowerz You can open a new issue for the 'loc' field and I will address it in the next release.

**Comment by taozhi8833998** [comment]
@karanssj4 fixed it in your new opened issue.
