### ISSUE TITLE
Postgres function loc support

### ISSUE THREAD

**Issue by adamtowerz** [taozhi8833998/node-sql-parser#2072]
**Describe the bug**
Postgres function nodes don't have `loc` support, which is super helpful.

**Database Engine**
PostgreSQL

**To Reproduce**
```sql
SELECT * FROM "company"
WHERE NOT(company._id IS NULL)
```

Obviously this query could be expressed differently, but its a simple repro.

**Expected behavior**
The node's `loc` property is filled with the information about what characters were parsed to become this node.

**Comment by PrasanthVijayy** [comment]
Hi @adamtowerz

I noticed this issue and would like to contribute by working on it. Is anyone already working on this? If not, I'd be happy to start looking into it. Please let me know if there are any specific guidelines or things I should consider while addressing this issue.
