### ISSUE TITLE
Anyway to disable scalar functions?

### ISSUE THREAD

**Issue by sm373373** [taozhi8833998/node-sql-parser#21]
I'm trying to use this parser to parse spark sql.

I've run across a situation where my spark sql select clause contains one of the scalar functions which then throws an error.

Example:

current_date() is a valid spark sql function but it is throwing an error in the parser because the parser thinks current_date is a scalar function and shouldn't have the parenthesis attached to the end.

https://spark.apache.org/docs/2.3.0/api/sql/#current_date

If there's a way to just disable the scalar functions built in, then it would work.

Thanks.

**Comment by taozhi8833998** [comment]
@sm373373 Sorry for later reply. It supports scalar function with optional parentheses in 1.2.0 version now, you could read more in this commit 1f0a3708ac4ee2635ae5f237a123cc91e629e3cd. Thanks for using the parser

**Comment by sm373373** [comment]
works good. thanks
