### ISSUE TITLE
Issue with 'type'

### ISSUE THREAD

**Issue by giacomoronconiobda** [taozhi8833998/node-sql-parser#210]
I have an SQL table with a column named type. Something like:

```
SELECT book_view.code
FROM book_view
WHERE book_view.type = 'A'
```

The parser expect something after type I think because it could be a keyword.

**Comment by taozhi8833998** [comment]
Yeah,`type` is a keyword in MySQL. I have removed the keyword check on the column name, you could try new version `1.7.1`

**Comment by taozhi8833998** [comment]
I will close this issue since inactive if you still have it, you can reopen it. Thanks for ur usage.
