### ISSUE TITLE
astify throw error with column name `key`

### ISSUE THREAD

**Issue by zackshen** [taozhi8833998/node-sql-parser#2117]
**Describe the bug**
```javascript
const { Parser } = require('node-sql-parser');
const parser = new Parser();
const ast = parser.astify('SELECT * FROM xxxxx WHERE key = "value1"'); // mysql sql grammer parsed by default
```

error
```
[SyntaxError]: Expected "#", "(", "--", ".", "/*", or [ \t\n\r] but "=" found.
```

if i changed `key` to `ky` , `key1` , astify successfully.

**Database Engine**
MySQL

**To Reproduce**
-the SQL that be parsed: SELECT * FROM xxxxx WHERE key = "value1"
-the node-sql-parser: 5.3.2
-the node version: 20.3.1

**Expected behavior**
astify successfully.

**Screenshots**
no screenshot.

**Additional context**
no context.

**Comment by taozhi8833998** [comment]
@zackshen `key` is a reserved keyword in MySQL, so please wrap it by ` in MySQL.
```sql
SELECT * FROM xxxxx WHERE `key` = "value1"
```

**Comment by zackshen** [comment]
thanks @zackshen

**Comment by zackshen** [comment]
thanks @taozhi8833998
