### ISSUE TITLE
Trino queries cannot parse a.b.c

### ISSUE THREAD

**Issue by npmccauslin** [taozhi8833998/node-sql-parser#2118]
**Describe the bug**
In trino, it is valid to access a table like a.b.c, however, the Trino parser reports a syntax error.

a  --> is the name of the catalog (like hive, mysql, or another catalog available in your Trino instance)
b --> is the schema (like a database or namespace)
c --> is the table name

```
Received: {"expected": [{"ignoreCase": false, "inverted": false, "parts": [["A", "Z"], ["a", "z"], ["0", "9"], "_", "$", ["", "￿"]], "type": "class"}, {"ignoreCase": false, "inverted": false, "parts": [" ", "	", "
"], "type": "class"}, {"ignoreCase": false, "text": "/*", "type": "literal"}, {"ignoreCase": false, "text": "--", "type": "literal"}, {"ignoreCase": false, "text": "//", "type": "literal"}, {"ignoreCase": false, "text": ";", "type": "literal"}, {"type": "end"}], "found": ".", "location": {"end": {"offset": 7}, "start": {"offset": 6}}, "message": "Expected \"--\", \"/*\", \"//\", \";\", [ \\t\\n\\r], [A-Za-z0-9_$\\x80-￿], or end of input but \".\" found.", "name": "SyntaxError"}

```

**Database Engine**
Trino

**To Reproduce**
-the SQL that be parsed
-the node-sql-parser version
-the node version
This query incorrectly throws the error:

```
SELECT *
FROM a.b.c
LIMIT 10;
```
Node version: v18.20.4
node-sql-version: v5.3.2

**Expected behavior**

Parser should not throw a syntax error with that query.

**Screenshots**

**Additional context**

**Comment by taozhi8833998** [comment]
@npmccauslin please specify the `database` option to `trino`
