### ISSUE TITLE
use new sqlParser.Parser().tableList(sql) ,but no return ,maybe timeout...

### ISSUE THREAD

**Issue by HUxiaoAlinNG** [taozhi8833998/node-sql-parser#216]
const sql = `SELECT COUNT(*) FROM \`s_opportunity\` \`opp\` LEFT JOIN \`s_customer\` \`cst\` ON cst.s_customerId=opp.cst_id LEFT JOIN \`s_opp_ext_field\` \`oppext\` ON oppext.opp_id=opp.s_opportunityId WHERE (((((((((((((((((((\`opp\`.\`proj_id\`='39efc060-d7aa-f39d-5e54-fcce4f7a28d5') AND ((\`opp\`.\`is_conflict\`=0) AND (\`opp\`.\`is_repeat\`=0) AND (\`opp\`.\`status\`=1) AND (\`opp\`.\`is_rubbish\`=0))) AND (EXISTS (SELECT 1 FROM s_opp2gjjl WHERE opp_id=opp.s_opportunityId  AND gjfs IN ('1','3','4','5','2','7') AND \`gj_date\` >= '2019-11-01 00:00:00' AND \`gj_date\` <= '2019-12-01 23:59:59' AND gj_from NOT IN (4,9,99,98)))) AND (opp.follow_level IN ('1','2','4','3'))) AND (\`opp\`.\`last_date\` >= '2019-12-01 00:00:00')) AND (\`opp\`.\`last_date\` <= '2019-12-19 23:59:59')) AND (opp.s_opportunityId in (select opp_id from s_opp2erp as opp2erp where opp2erp.yx_proj_guid in('56d2480d-f296-e911-80f1-d7a3653423fe')
                           and status = 1 ))) AND ((opp.area_wishe_ids IN ('1','2','5','3','4')) OR (FIND_IN_SET('1', opp.area_wishe_ids) OR FIND_IN_SET('2', opp.area_wishe_ids) OR FIND_IN_SET('5', opp.area_wishe_ids) OR FIND_IN_SET('3', opp.area_wishe_ids) OR FIND_IN_SET('4', opp.area_wishe_ids)))) AND (opp.price_wishe_ids IN ('1','2','3'))) AND ((opp.attention_ids IN ('1','10','12','5','3','6','14','18','16','15','22','21','17','23','19','9','7','8','13','11','20')) OR (FIND_IN_SET('1', opp.attention_ids) OR FIND_IN_SET('10', opp.attention_ids) OR FIND_IN_SET('12', opp.attention_ids) OR FIND_IN_SET('5', opp.attention_ids) OR FIND_IN_SET('3', opp.attention_ids) OR FIND_IN_SET('6', opp.attention_ids) OR FIND_IN_SET('14', opp.attention_ids) OR FIND_IN_SET('18', opp.attention_ids) OR FIND_IN_SET('16', opp.attention_ids) OR FIND_IN_SET('15', opp.attention_ids) OR FIND_IN_SET('22', opp.attention_ids) OR FIND_IN_SET('21', opp.attention_ids) OR FIND_IN_SET('17', opp.attention_ids) OR FIND_IN_SET('23', opp.attention_ids) OR FIND_IN_SET('19', opp.attention_ids) OR FIND_IN_SET('9', opp.attention_ids) OR FIND_IN_SET('7', opp.attention_ids) OR FIND_IN_SET('8', opp.attention_ids) OR FIND_IN_SET('13', opp.attention_ids) OR FIND_IN_SET('11', opp.attention_ids) OR FIND_IN_SET('20', opp.attention_ids)))) AND (opp.ex_opp02 IN ('1','5','2','3','4'))) AND ((opp.ex_opp12 IN ('1','5','6','2','3','7','8','4','9','10','11')) OR (FIND_IN_SET('1', opp.ex_opp12) OR FIND_IN_SET('5', opp.ex_opp12) OR FIND_IN_SET('6', opp.ex_opp12) OR FIND_IN_SET('2', opp.ex_opp12) OR FIND_IN_SET('3', opp.ex_opp12) OR FIND_IN_SET('7', opp.ex_opp12) OR FIND_IN_SET('8', opp.ex_opp12) OR FIND_IN_SET('4', opp.ex_opp12) OR FIND_IN_SET('9', opp.ex_opp12) OR FIND_IN_SET('10', opp.ex_opp12) OR FIND_IN_SET('11', opp.ex_opp12)))) AND (opp.ex_opp07 IN ('1','5','9','13','17','14','10','6','2','3','7','11','15','12','8','4','16'))) AND (opp.known_id IN ('5','6','2','3','7','4','8'))) AND (cst.profession IN ('1','4','8','9','5','10','2','6','7','3'))) AND (cst.home_id IN ('1','3','4','5','6','7','8','9','10','11','12','13','14','15','16','20','17','19','18','21','22','23'))) AND (cst.ages IN ('1','5','6','2','3','7','4','8','9','10','11'))) AND (cst.work_area_id IN ('1','5','2','3','4'))) AND ((oppext.ex_opp_field26 IN ('1','5','6','2','3','7','8','4')) OR (FIND_IN_SET('1', oppext.ex_opp_field26) OR FIND_IN_SET('5', oppext.ex_opp_field26) OR FIND_IN_SET('6', oppext.ex_opp_field26) OR FIND_IN_SET('2', oppext.ex_opp_field26) OR FIND_IN_SET('3', oppext.ex_opp_field26) OR FIND_IN_SET('7', oppext.ex_opp_field26) OR FIND_IN_SET('8', oppext.ex_opp_field26) OR FIND_IN_SET('4', oppext.ex_opp_field26)))) AND (oppext.ex_opp_field23 IN ('1','5','6','2','3','4'))`

**Comment by HUxiaoAlinNG** [comment]
the original sql is 

SELECT COUNT(*) FROM `s_opportunity` `opp` LEFT JOIN `s_customer` `cst` ON cst.s_customerId=opp.cst_id LEFT JOIN `s_opp_ext_field` `oppext` ON oppext.opp_id=opp.s_opportunityId WHERE (((((((((((((((((((`opp`.`proj_id`='39efc060-d7aa-f39d-5e54-fcce4f7a28d5') AND ((`opp`.`is_conflict`=0) AND (`opp`.`is_repeat`=0) AND (`opp`.`status`=1) AND (`opp`.`is_rubbish`=0))) AND (EXISTS (SELECT 1 FROM s_opp2gjjl WHERE opp_id=opp.s_opportunityId  AND gjfs IN ('1','3','4','5','2','7') AND `gj_date` >= '2019-11-01 00:00:00' AND `gj_date` <= '2019-12-01 23:59:59' AND gj_from NOT IN (4,9,99,98)))) AND (opp.follow_level IN ('1','2','4','3'))) AND (`opp`.`last_date` >= '2019-12-01 00:00:00')) AND (`opp`.`last_date` <= '2019-12-19 23:59:59')) AND (opp.s_opportunityId in (select opp_id from s_opp2erp as opp2erp where opp2erp.yx_proj_guid in('56d2480d-f296-e911-80f1-d7a3653423fe')
                           and status = 1 ))) AND ((opp.area_wishe_ids IN ('1','2','5','3','4')) OR (FIND_IN_SET('1', opp.area_wishe_ids) OR FIND_IN_SET('2', opp.area_wishe_ids) OR FIND_IN_SET('5', opp.area_wishe_ids) OR FIND_IN_SET('3', opp.area_wishe_ids) OR FIND_IN_SET('4', opp.area_wishe_ids)))) AND (opp.price_wishe_ids IN ('1','2','3'))) AND ((opp.attention_ids IN ('1','10','12','5','3','6','14','18','16','15','22','21','17','23','19','9','7','8','13','11','20')) OR (FIND_IN_SET('1', opp.attention_ids) OR FIND_IN_SET('10', opp.attention_ids) OR FIND_IN_SET('12', opp.attention_ids) OR FIND_IN_SET('5', opp.attention_ids) OR FIND_IN_SET('3', opp.attention_ids) OR FIND_IN_SET('6', opp.attention_ids) OR FIND_IN_SET('14', opp.attention_ids) OR FIND_IN_SET('18', opp.attention_ids) OR FIND_IN_SET('16', opp.attention_ids) OR FIND_IN_SET('15', opp.attention_ids) OR FIND_IN_SET('22', opp.attention_ids) OR FIND_IN_SET('21', opp.attention_ids) OR FIND_IN_SET('17', opp.attention_ids) OR FIND_IN_SET('23', opp.attention_ids) OR FIND_IN_SET('19', opp.attention_ids) OR FIND_IN_SET('9', opp.attention_ids) OR FIND_IN_SET('7', opp.attention_ids) OR FIND_IN_SET('8', opp.attention_ids) OR FIND_IN_SET('13', opp.attention_ids) OR FIND_IN_SET('11', opp.attention_ids) OR FIND_IN_SET('20', opp.attention_ids)))) AND (opp.ex_opp02 IN ('1','5','2','3','4'))) AND ((opp.ex_opp12 IN ('1','5','6','2','3','7','8','4','9','10','11')) OR (FIND_IN_SET('1', opp.ex_opp12) OR FIND_IN_SET('5', opp.ex_opp12) OR FIND_IN_SET('6', opp.ex_opp12) OR FIND_IN_SET('2', opp.ex_opp12) OR FIND_IN_SET('3', opp.ex_opp12) OR FIND_IN_SET('7', opp.ex_opp12) OR FIND_IN_SET('8', opp.ex_opp12) OR FIND_IN_SET('4', opp.ex_opp12) OR FIND_IN_SET('9', opp.ex_opp12) OR FIND_IN_SET('10', opp.ex_opp12) OR FIND_IN_SET('11', opp.ex_opp12)))) AND (opp.ex_opp07 IN ('1','5','9','13','17','14','10','6','2','3','7','11','15','12','8','4','16'))) AND (opp.known_id IN ('5','6','2','3','7','4','8'))) AND (cst.profession IN ('1','4','8','9','5','10','2','6','7','3'))) AND (cst.home_id IN ('1','3','4','5','6','7','8','9','10','11','12','13','14','15','16','20','17','19','18','21','22','23'))) AND (cst.ages IN ('1','5','6','2','3','7','4','8','9','10','11'))) AND (cst.work_area_id IN ('1','5','2','3','4'))) AND ((oppext.ex_opp_field26 IN ('1','5','6','2','3','7','8','4')) OR (FIND_IN_SET('1', oppext.ex_opp_field26) OR FIND_IN_SET('5', oppext.ex_opp_field26) OR FIND_IN_SET('6', oppext.ex_opp_field26) OR FIND_IN_SET('2', oppext.ex_opp_field26) OR FIND_IN_SET('3', oppext.ex_opp_field26) OR FIND_IN_SET('7', oppext.ex_opp_field26) OR FIND_IN_SET('8', oppext.ex_opp_field26) OR FIND_IN_SET('4', oppext.ex_opp_field26)))) AND (oppext.ex_opp_field23 IN ('1','5','6','2','3','4'))

**Comment by taozhi8833998** [comment]
Sorry for the bad case,  but the SQL is too ugly to read by a human. I hope you could split it into pieces of simple code for easy reading and understanding, besides, you need to follow instruction to open an issue with detailed and formatted info.

**Comment by HUxiaoAlinNG** [comment]
Can I speak Chinese？
我知道这sql看起来很不友好，么办法，框架内部处理的代码。我只是很纳闷，解析不了，为啥不报错，而是无限等待...

**Comment by jingsam** [comment]
我觉得您应自己先动手排查下，把语句精简到最小复现，这样便于作者诊断问题。毕竟，作者没有义务去解决您框架的问题。

**Comment by taozhi8833998** [comment]
> Can I speak Chinese？
> 我知道这sql看起来很不友好，么办法，框架内部处理的代码。我只是很纳闷，解析不了，为啥不报错，而是无限等待...

ok,  I am also Chinese. I split the SQL into small pieces of codes and founded a keyword that was used in the long SQL, **status**. I have fixed it, you could try to parse the SQL using **1.7.4** version. However, it took about 3 or 4 minutes to get the result since the complexity of the SQL, you need to be more patient, and I am sorry for that. I will take the parser speed for long SQL into consideration for future improvement. 

The code is as follows:

```javascript
const sql = `SELECT
COUNT(*)
FROM s_opportunity opp
LEFT JOIN s_customer cst ON cst.s_customerId = opp.cst_id
LEFT JOIN s_opp_ext_field oppext ON oppext.opp_id = opp.s_opportunityId
WHERE
(
  (
    (
      (
        (
          (
            (
              (
                (
                  (
                    (
                      (
                        (
                          (
                            (
                              (
                                (
                                  (
                                    (
                                      opp.proj_id = '39efc060-d7aa-f39d-5e54-fcce4f7a28d5'
                                    )
                                    AND (
                                      (opp.is_conflict = 0)
                                      AND (opp.is_repeat = 0)
                                      AND (opp.status = 1)
                                      AND (opp.is_rubbish = 0)
                                    )
                                  )
                                  AND (
                                    EXISTS (
                                      SELECT
                                        1
                                      FROM
                                        s_opp2gjjl
                                      WHERE
                                        opp_id = opp.s_opportunityId
                                        AND gjfs IN ('1', '3', '4', '5', '2', '7')
                                        AND gj_date >= '2019-11-01 00:00:00'
                                        AND gj_date <= '2019-12-01 23:59:59'
                                        AND gj_from NOT IN (4, 9, 99, 98)
                                    )
                                  )
                                )
                                AND (
                                  opp.follow_level IN ('1', '2', '4', '3')
                                )
                              )
                              AND (
                                opp.last_date >= '2019-12-01 00:00:00'
                              )
                            )
                            AND (
                              opp.last_date <= '2019-12-19 23:59:59'
                            )
                          )
                          AND (
                            opp.s_opportunityId in (
                              select
                                opp_id
                              from
                                s_opp2erp as opp2erp
                              where
                                opp2erp.yx_proj_guid in(
                                  '56d2480d-f296-e911-80f1-d7a3653423fe'
                                )
                                and status = 1
                            )
                          )
                        )
                        AND (
                          (
                            opp.area_wishe_ids IN ('1', '2', '5', '3', '4')
                          )
                          OR (
                            FIND_IN_SET('1', opp.area_wishe_ids)
                            OR FIND_IN_SET('2', opp.area_wishe_ids)
                            OR FIND_IN_SET('5', opp.area_wishe_ids)
                            OR FIND_IN_SET('3', opp.area_wishe_ids)
                            OR FIND_IN_SET('4', opp.area_wishe_ids)
                          )
                        )
                      )
                      AND (
                        opp.price_wishe_ids IN ('1', '2', '3')
                      )
                    )
                    AND (
                      (
                        opp.attention_ids IN (
                          '1', '10', '12', '5', '3', '6', '14',
                          '18', '16', '15', '22', '21', '17',
                          '23', '19', '9', '7', '8', '13', '11',
                          '20'
                        )
                      )
                      OR (
                        FIND_IN_SET('1', opp.attention_ids)
                        OR FIND_IN_SET('10', opp.attention_ids)
                        OR FIND_IN_SET('12', opp.attention_ids)
                        OR FIND_IN_SET('5', opp.attention_ids)
                        OR FIND_IN_SET('3', opp.attention_ids)
                        OR FIND_IN_SET('6', opp.attention_ids)
                        OR FIND_IN_SET('14', opp.attention_ids)
                        OR FIND_IN_SET('18', opp.attention_ids)
                        OR FIND_IN_SET('16', opp.attention_ids)
                        OR FIND_IN_SET('15', opp.attention_ids)
                        OR FIND_IN_SET('22', opp.attention_ids)
                        OR FIND_IN_SET('21', opp.attention_ids)
                        OR FIND_IN_SET('17', opp.attention_ids)
                        OR FIND_IN_SET('23', opp.attention_ids)
                        OR FIND_IN_SET('19', opp.attention_ids)
                        OR FIND_IN_SET('9', opp.attention_ids)
                        OR FIND_IN_SET('7', opp.attention_ids)
                        OR FIND_IN_SET('8', opp.attention_ids)
                        OR FIND_IN_SET('13', opp.attention_ids)
                        OR FIND_IN_SET('11', opp.attention_ids)
                        OR FIND_IN_SET('20', opp.attention_ids)
                      )
                    )
                  )
                  AND (
                    opp.ex_opp02 IN ('1', '5', '2', '3', '4')
                  )
                )
                AND (
                  (
                    opp.ex_opp12 IN (
                      '1', '5', '6', '2', '3', '7', '8', '4',
                      '9', '10', '11'
                    )
                  )
                  OR (
                    FIND_IN_SET('1', opp.ex_opp12)
                    OR FIND_IN_SET('5', opp.ex_opp12)
                    OR FIND_IN_SET('6', opp.ex_opp12)
                    OR FIND_IN_SET('2', opp.ex_opp12)
                    OR FIND_IN_SET('3', opp.ex_opp12)
                    OR FIND_IN_SET('7', opp.ex_opp12)
                    OR FIND_IN_SET('8', opp.ex_opp12)
                    OR FIND_IN_SET('4', opp.ex_opp12)
                    OR FIND_IN_SET('9', opp.ex_opp12)
                    OR FIND_IN_SET('10', opp.ex_opp12)
                    OR FIND_IN_SET('11', opp.ex_opp12)
                  )
                )
              )
              AND (
                opp.ex_opp07 IN (
                  '1', '5', '9', '13', '17', '14', '10',
                  '6', '2', '3', '7', '11', '15', '12',
                  '8', '4', '16'
                )
              )
            )
            AND (
              opp.known_id IN ('5', '6', '2', '3', '7', '4', '8')
            )
          )
          AND (
            cst.profession IN (
              '1', '4', '8', '9', '5', '10', '2', '6',
              '7', '3'
            )
          )
        )
        AND (
          cst.home_id IN (
            '1', '3', '4', '5', '6', '7', '8', '9',
            '10', '11', '12', '13', '14', '15',
            '16', '20', '17', '19', '18', '21',
            '22', '23'
          )
        )
      )
      AND (
        cst.ages IN (
          '1', '5', '6', '2', '3', '7', '4', '8',
          '9', '10', '11'
        )
      )
    )
    AND (
      cst.work_area_id IN ('1', '5', '2', '3', '4')
    )
  )
  AND (
    (
      oppext.ex_opp_field26 IN (
        '1', '5', '6', '2', '3', '7', '8', '4'
      )
    )
    OR (
      FIND_IN_SET('1', oppext.ex_opp_field26)
      OR FIND_IN_SET('5', oppext.ex_opp_field26)
      OR FIND_IN_SET('6', oppext.ex_opp_field26)
      OR FIND_IN_SET('2', oppext.ex_opp_field26)
      OR FIND_IN_SET('3', oppext.ex_opp_field26)
      OR FIND_IN_SET('7', oppext.ex_opp_field26)
      OR FIND_IN_SET('8', oppext.ex_opp_field26)
      OR FIND_IN_SET('4', oppext.ex_opp_field26)
    )
  )
)
AND (
  oppext.ex_opp_field23 IN ('1', '5', '6', '2', '3', '4')
)
`
const Parser = require('node-sql-parser').Parser
const parser = new Parser()
console.time('parser')
const tableList = parser.tableList(sql)
console.timeEnd('parser')
console.log(tableList)
```

It printed as below:

```javascript
parser: 3:00.127 (m:ss.mmm)
[
  'select::null::s_opp2gjjl',
  'select::null::s_opp2erp',
  'select::null::s_opportunity',
  'select::null::s_customer',
  'select::null::s_opp_ext_field'
]
```

**Comment by taozhi8833998** [comment]
> 我觉得您应自己先动手排查下，把语句精简到最小复现，这样便于作者诊断问题。毕竟，作者没有义务去解决您框架的问题。

Yeah, thanks for your kindness to explain what I want,  I hold the same view as you.  Nevertheless, my codes have a silent error that made @HUxiaoAlinNG confuse about the issue. Maybe HUxiaoAlinNG could try to take jingsam's advice into account.

**Comment by taozhi8833998** [comment]
@HUxiaoAlinNG I'm gonna close this issue since the inactive status. If it's still annoying u, you're welcomed to open a new issue. Thanks for ur feedback.
