### ISSUE TITLE
Bug: Subquery in LIMIT Clause Not Parsed by node-sql-parser

### ISSUE THREAD

**Issue by sambit04126** [taozhi8833998/node-sql-parser#2236]
**Describe the bug**

The node-sql-parser library is unable to parse SQL queries that include a subquery in the LIMIT clause. The query is valid in PostgreSQL but fails to parse in node-sql-parser.

**Database Engine**
PostgreSQL.

**To Reproduce**

SELECT * 
FROM user 
LIMIT (SELECT COUNT(*) / 2 FROM user);

-the node-sql-parser version - 5.3.4
-the node version -18.17.1

**Expected behavior**

The parser should correctly handle queries with subqueries in the LIMIT clause, as it is valid in PostgreSQL. It should parse without errors and produce an appropriate Abstract Syntax Tree (AST) for the query.

**Screenshots**

**Additional context**

**Comment by taozhi8833998** [comment]
@sambit04126 fixed it.
