### ISSUE TITLE
[Athena] Support REAL data type

### ISSUE THREAD

**Issue by tobiasheldring** [taozhi8833998/node-sql-parser#2238]
**Describe the bug**
`REAL` [is supported in Athena](https://docs.aws.amazon.com/athena/latest/ug/data-types.html) but not by the parser

**Database Engine**
Athena

**To Reproduce**
Add the following test to `Athena.spec.js`

```javascript
  describe('data types', () => {
    it('should support the REAL data type', () => {
      const sql = `SELECT
      CAST(my_column AS real) AS "my_number"
    FROM
      "my_table"`
      expect(getParsedSql(sql)).to.be.equal('SELECT CAST(`my_column` AS REAL) AS `my_number` FROM `my_table`')
    })
  })
```

**Proposed solution**
https://github.com/tobiasheldring/node-sql-parser/pull/2/files

**Comment by taozhi8833998** [comment]
@tobiasheldring Your pull request looks good to me. You can open a pull request for the project next time so I can review and merge it. Thanks for fixing the issues.
