### ISSUE TITLE
Potential regression in 5.3.4

### ISSUE THREAD

**Issue by mgagliardo91** [taozhi8833998/node-sql-parser#2248]
**Describe the bug**

We rely on `node-sql-parser` for being able to extract fully qualified columns from a postgres expression. A change, as of 5.3.4, has broken our assumptions and we are unsure of how to resolve without some manual parsing.

**Database Engine**
PostgreSQL

**To Reproduce**
- `sqlParser.columnList('SELECT SUM("source"."point" + "other_source"."other_point") FROM foo')`
- `5.3.4`
- `v22.9.0`

**Expected behavior**
In versions prior to 5.3.4, there would be two results, correctly including only the columns `source.point` and `other_source.other_point`:

```
[
  'select::source::point',
  'select::other_source::other_point'
]
```

In 5.3.4+, there are three results, as the column parser calls out the aggregate function `sum` as a column.

```
[
  'select::null::SUM',
  'select::source::point',
  'select::other_source::other_point'
]
```

**Additional context**

Thanks for looking into this, we are pinned at 5.3.3 until we can get this resolved!

**Comment by taozhi8833998** [comment]
@mgagliardo91 Sorry for the new bug. I will work on fixing it as soon as possible.

**Comment by mgagliardo91** [comment]
no worries, thanks for looking into it @taozhi8833998 !
