### ISSUE TITLE
PARTITION BY fails to parse when using EXTRACT or some other function

### ISSUE THREAD

**Issue by dannflor** [taozhi8833998/node-sql-parser#2258]
**Describe the bug**
PARTITION BY works when pointed directly at a column reference, but not when the column is being consumed by a function e.g. EXTRACT

**Database Engine**
PostgreSQL, though I believe this is relevant to all flavors of SQL

**To Reproduce**
```
SELECT Year, Title, ROW_NUMBER() OVER (PARTITION BY EXTRACT(YEAR FROM CreationDate)) AS rn FROM yearly_views;
```
**Expected behavior**
It should parse correctly as it would if I did 
```
SELECT Year, Title, ROW_NUMBER() OVER (PARTITION BY CreationDate) AS rn FROM yearly_views;
```
**Additional context**
5.3.5

**Comment by taozhi8833998** [comment]
@dannflor fixed it.
