### ISSUE TITLE
Create query syntax error

### ISSUE THREAD

**Issue by Alaa-Joukhadar** [taozhi8833998/node-sql-parser#233]
```CREATE TABLE `Person` (
  `id_Person` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `id_person_gender` int(11) NOT NULL,
  `id_person_origin` int(11) NOT NULL,
  `age` int(11) NOT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `is_alive` tinyint(1) DEFAULT NULL,
  `updated_by` varchar(48) DEFAULT NULL,
  PRIMARY KEY (`id_Person`),
  UNIQUE KEY `pft_ge_or` (`id_person_gender`, `id_person_origin`)
);```

getting error: ```SyntaxError: Expected "#", ")", ",", "--", "/*", "AUTO_INCREMENT", "COLLATE", "COLUMN_FORMAT", "COMMENT", "DEFAULT", "KEY", "NOT NULL", "NULL", "PRIMARY", "REFERENCES", "STORAGE", "UNIQUE", or [ \t\n\r] but "u" found.```

**Comment by taozhi8833998** [comment]
supported in version `1.7.7`, give it a shot!

**Comment by kanishk-J** [comment]
@taozhi8833998 mediumtext, text and such data types also not supported in create query. Getting following error:
SyntaxError: Expected "#", "--", ".", "/*", "BIGINT", "CHAR", "DATE", "DECIMAL", "INT", "INTEGER", "JSON", "NUMERIC", "SMALLINT", "TIME", "TIMESTAMP", "TINYINT", "VARCHAR", or [ \t\n\r] but "t" found.

**Comment by taozhi8833998** [comment]
> @taozhi8833998 mediumtext, text and such data types also not supported in create query. Getting following error:
> SyntaxError: Expected "#", "--", ".", "/*", "BIGINT", "CHAR", "DATE", "DECIMAL", "INT", "INTEGER", "JSON", "NUMERIC", "SMALLINT", "TIME", "TIMESTAMP", "TINYINT", "VARCHAR", or [ \t\n\r] but "t" found.

ok, got it. Could you show me the original SQL?

**Comment by kanishk-J** [comment]
@taozhi8833998 Sorry for late reply. Here is the query
CREATE TABLE `manager_access` (
 `id` int(11) NOT NULL AUTO_INCREMENT,
 `manager_id` int(11) NOT NULL,
 `drivers_elements` mediumtext NOT NULL,
 `subordinates` mediumtext,
 `created` int(11) NOT NULL,
 `modified` int(11) NOT NULL,
 `unsubscribe_weekly_report` tinyint(4) NOT NULL DEFAULT '0',
 `unsubscribe_quarterly_report` tinyint(4) NOT NULL DEFAULT '0',
 PRIMARY KEY (`id`)
)

**Comment by taozhi8833998** [comment]
it has been supported in `1.7.10` version.

**Comment by kanishk-J** [comment]
@taozhi8833998 I tried it. Worked like a charm. Thanks a ton. But now I found that FLOAT is not supported.

**Comment by taozhi8833998** [comment]
ok, you can open a new issue for that. I will fix it today as well.

**Comment by kanishk-J** [comment]
Ok sure. Thanks

**Comment by taozhi8833998** [comment]
it has been supported, and I am gonna close it.
