### ISSUE TITLE
Support for JSON query syntax in MySQL

### ISSUE THREAD

**Issue by ymhr** [taozhi8833998/node-sql-parser#238]
In MySQL there are some shorthand properties to select JSON data, e.g. `SELECT jsonCol->>'$.test.path' from 'items';`

Currently this query will fail to parse throwing this error:

```SyntaxError: Expected "#", "$", "'", "(", "+", "-", "--", "/*", ":", "@", "@@", "AVG", "CASE", "CAST", "COUNT", "CURRENT_DATE", "CURRENT_TIME", "CURRENT_TIMESTAMP", "CURRENT_USER", "DATE", "FALSE", "INTERVAL", "MAX", "MIN", "NULL", "SESSION_USER", "SUM", "SYSTEM_USER", "TIME", "TIMESTAMP", "TRUE", "USER", "\"", "`", [ \t\n\r], [0-9], or [A-Za-z_] but ">" found.```

I believe it could be related to this issue:https://github.com/taozhi8833998/node-sql-parser/issues/156

**Comment by taozhi8833998** [comment]
oh, god! I don't even know that MySQL supports the JSON syntax like pg, sorry for that. I will support this tomorrow.

**Comment by taozhi8833998** [comment]
published a new version, `1.7.8`, you can give it a shot.

**Comment by ymhr** [comment]
@taozhi8833998 that's awesome, thanks for getting it out so quickly!

There is still an issue though, `data->>'$.path'` works fine, but `item.data->>'$.path'` still throws an error.

Also there is a different issue, using COLLATE will also cause an error - this is necessary for some interactions with JSON, as it makes it behave more like a normal text column. E.g. 
`data->>'$.type' COLLATE utf8mb4_unicode_ci AS "type"`
Please let me know if you would like me to make a new issue for this.

I have created a code sandbox reproducing both issues here:
https://codesandbox.io/s/node-sql-parser-issues-96evt

**Comment by taozhi8833998** [comment]
gotcha, I will support it today.  The `COLLATE ` issue is related to this one, so it's ok to put them in one issue.

**Comment by taozhi8833998** [comment]
test passed, I will publish a new version later.

**Comment by taozhi8833998** [comment]
Travis ci is under maintenance, so the merge request didn't pass the check. I will publish a new version when it been merged.

**Comment by ymhr** [comment]
Thanks for the quick update, looking forward to the new release.

**Comment by taozhi8833998** [comment]
try `1.7.9`

**Comment by taozhi8833998** [comment]
if the issue has been solved, please close it at your convenience.

**Comment by ymhr** [comment]
Works perfectly! Thank you so much for the quick responses.
