### ISSUE TITLE
sql parsing issue with select *

### ISSUE THREAD

**Issue by sm373373** [taozhi8833998/node-sql-parser#24]
Found an issue when selecting * and then another field when * doesn't have an alias.

Ex.

The following sql fails but is really valid sql:

`select *, 'a' as col2 from table1`

This only fails when * has no alias/table prefix.

`select table1.*, 'a' as col2 from table1`

works fine.

**Comment by taozhi8833998** [comment]
fixed in 1.2.2 version, read more in commit fade9fb52fbc3af83c97e9bbbae417d3ecdc64e7. BTW, `*` could not hava alias as far as I know. If I am wrong, please correct me

**Comment by sm373373** [comment]
Yeah, works fine and your test cases look good.

Thanks.
