### ISSUE TITLE
How do I support a ${value} placeholder like this

### ISSUE THREAD

**Issue by liuxingang** [taozhi8833998/node-sql-parser#240]
```
SELECT customer_name
FROM customer_info
WHERE name = ${customer}
```

I thought this would resolve ${customer} directly as a parameter, but the parse reported an error
`error:peg$SyntaxError {message: "Expected [A-Za-z_] but "{" found.", expected: Array(2), found: "{", location: {…}, name: "SyntaxError", …}`

```
SELECT customer_name
FROM customer_info
WHERE name = '${customer}'
```
If I wrap ${customer} in quotation marks as value, it's resolvable, but a bit ugly, how do I directly resolve such `placeholders`
**thanks for help**

**Comment by taozhi8833998** [comment]
```SQL
SELECT customer_name
FROM customer_info
WHERE name = ${customer}
```

I don't think it's a valid SQL. `${customer}` is your template string, you need to replace it with the variable value, then it would be a valid SQL. The parser could only parse the valid SQL syntax that could be executed by a database engine.

You should parse the SQL without any placeholders that don't supported in the database.

**Comment by taozhi8833998** [comment]
I will label it as `won't fix` at this time. But, if you have more to comment on this, you can always do that.
