### ISSUE TITLE
support functions in GROUP BY

### ISSUE THREAD

**Issue by egbertc** [taozhi8833998/node-sql-parser#249]
```
let sql = "SELECT date_format(neat_timestamp,'yyyyMM'), COUNT(*) FROM neat_table GROUP BY date_format(neat_timestamp,'yyyyMM')"

const opt = {
    database: 'Hive'
}
var parser = new Parser()
var tableList = parser.tableList(sql, opt)
```

**error:**
`Expected "#", ",", "--", ".", "/*", ";", "HAVING", "LIMIT", "ORDER", "UNION", [ \t\n\r], [A-Za-z0-9_:], [A-Za-z0-9_], or end of input but "(" found.`

Can functions within GROUP BY be supported?

Thanks!

**Comment by taozhi8833998** [comment]
Thank you for your sample codes, it helps a lot. I will support this feature today

**Comment by taozhi8833998** [comment]
ok, I have finished the developing, it supported this feature now, you could try new version `1.7.9` later.

**Comment by taozhi8833998** [comment]
Travis ci is under maintenance, so the merge request didn't pass the check. I will publish a new version when it merged.

**Comment by taozhi8833998** [comment]
try `1.7.9`

**Comment by egbertc** [comment]
Working great. Thanks!

**Comment by taozhi8833998** [comment]
ok, I will close the issue, thank you for the help to improve my project.
