### ISSUE TITLE
Create Query Syntax does not support FLOAT data type

### ISSUE THREAD

**Issue by kanishk-J** [taozhi8833998/node-sql-parser#257]
I am getting the following error while astifying a create table query:

Expected "#", "--", "->", "->>", ".", "/*", "BIGINT", "CHAR", "DATE", "DECIMAL", "INT", "INTEGER", "JSON", "LONGTEXT", "MEDIUMTEXT", "NUMERI
C", "SMALLINT", "TEXT", "TIME", "TIMESTAMP", "TINYINT", "TINYTEXT", "VARCHAR", or [ \t\n\r] but "f" found.

I pin pointed out the issue by removing keys that used float in the query.

**Comment by taozhi8833998** [comment]
ok, I will fix it in minutes. it could be more clear if you show your original SQL when you open an issue.

**Comment by kanishk-J** [comment]
@taozhi8833998 Here is the query

CREATE TABLE `action_plans` (
 `id` int(11) NOT NULL AUTO_INCREMENT,
 `title` varchar(200) NOT NULL,
 `manager_id` int(11) NOT NULL,
 `employee_driver_id` int(11) NOT NULL,
 `engagement_element_id` int(11) NOT NULL,
 `initial_score` float NOT NULL,
 `score` float DEFAULT NULL,
 `created` int(11) NOT NULL,
 `modified` int(11) NOT NULL,
 `status` int(11) NOT NULL DEFAULT '1' COMMENT '1: to start, 2: in progress, 3: completed',
 `completion_time` int(11) NOT NULL,
 PRIMARY KEY (`id`)
)

**Comment by taozhi8833998** [comment]
ok, I have published a new version, `1.7.10`, give it a shot
