### ISSUE TITLE
Error in Node.js when requiring the package

### ISSUE THREAD

**Issue by schl3ck** [taozhi8833998/node-sql-parser#270]
**Describe the bug**
When I want to load the package, I get an error:

```
> const {Parser} = require("node-sql-parser")
Thrown:
TypeError: Cannot set property 'NodeSQLParser' of undefined
    at Object.<anonymous> (.\node_modules\node-sql-parser\index.js:9:29)
```

**Database Engine**
None

**To Reproduce**
-the SQL that be parsed: None
-the node-sql-parser version: 1.8.1
-the node version: 12.13.0
Windows 10 Enterprise 64-bit

**Expected behavior**
I expected to be able to load the package without problems.

**Screenshots**
Not needed.

**Additional context**
The commit 3355f46f010ea34aadb6175fd954da4ccfa4aecf adds unnecessary code in `index.js`, because a UMD module is built for the browser.

You could also include the build result in the repository and specify the UMD entry as the entry file for node.js.

**Comment by taozhi8833998** [comment]
Sorry for that. I have already fixed it in new release `1.8.2` , try it.
