### ISSUE TITLE
Parsing UUID in PostgreSQL

### ISSUE THREAD

**Issue by meh** [taozhi8833998/node-sql-parser#275]
**Describe the bug**
Got tables with UUID types, and the parser barfs on them, not sure if `UUID` is an extension type or something tho.

**Database Engine**
PostgreSQL

**To Reproduce**
- `CREATE TABLE foo (id UUID)`
- 1.8.2
- 13.13.0

**Comment by taozhi8833998** [comment]
I have released a new version `1.8.3`, give it a shot.

**Comment by meh** [comment]
Everything works, thanks a bunch!

**Comment by meh** [comment]
Well, now I'm getting a syntax error somewhere else, this is the entire statement:

```sql
CREATE TABLE accounts (
	id UUID DEFAULT uuid_generate_v4() NOT NULL,
	email TEXT NOT NULL,
	password TEXT NOT NULL,

	created_at TIMESTAMP NOT NULL DEFAULT NOW(),
	updated_at TIMESTAMP NULL,

	PRIMARY KEY (id)
);

CREATE TRIGGER set_updated_at
	BEFORE UPDATE ON accounts
	FOR EACH ROW
	EXECUTE PROCEDURE set_updated_at();
```

Not sure how much of SQL this module is meant to parse, but it's being used by `coc-sql`, so I'm getting linting errors :P

**Comment by taozhi8833998** [comment]
ok, I will fix it today

**Comment by taozhi8833998** [comment]
@meh released `1.8.4` version to support `create trigger` syntax in PostgreSQL. Try it.

**Comment by lucasholder** [comment]
Also using this extension through [coc-sql](https://github.com/fannheyward/coc-sql). Can we get `CREATE EXTENSION` too? :)

<img width="670" alt="Screen Shot 2020-04-26 at 3 20 03 PM" src="https://user-images.githubusercontent.com/62086489/80317380-78092000-87d1-11ea-95cc-5e71579ce369.png">

**Comment by lucasholder** [comment]
Also, might be worth to consider using [pg-query-parser](https://github.com/zhm/pg-query-parser) for parsing PostgreSQL... It's a wrapper for the actual C parser that PosgreSQL uses internally.

**Comment by lucasholder** [comment]
FWIW, I [sent a PR to coc-sql](https://github.com/fannheyward/coc-sql/pull/88) to instead use `pg-query-parser` with postgresql. @meh

**Comment by meh** [comment]
@lucasholder neat, thanks!

**Comment by taozhi8833998** [comment]
support `create extension` in `1.9.0` version. I will close this issue and take using the`pg-query-parser` module to parse pg in my module into account. Thanks a bunch.
