### ISSUE TITLE
Postgresql json syntax not recognized

### ISSUE THREAD

**Issue by kristijanhusak** [taozhi8833998/node-sql-parser#280]
**Describe the bug**
Postgresql json syntax is not recognized and it throws syntax error for valid query.

**Database Engine**
Postgresql

**To Reproduce**
-sql: `select * from my_table where jsonfield @> '{"mykey": "myvalue"}'`
- node-sql-parser version: latest
-node version: 12.2.0

**Expected behavior**
Expect to be properly parsed and not throw a syntax error

**Additional context**
I'm not sure about other json syntax, but my assumption is that it's also not working as this one.

**Comment by taozhi8833998** [comment]
ok, I will support the jsonb syntax as soon as possible.

**Comment by taozhi8833998** [comment]
I have released `1.9.1` version to fix the issue, try it.

**Comment by kristijanhusak** [comment]
Looks good, thanks!
