### ISSUE TITLE
INSERT SET syntax (MySQL)

### ISSUE THREAD

**Issue by ya-saka** [taozhi8833998/node-sql-parser#288]
Is there no support for parsing the INSERT SET syntax in MySQL?
https://dev.mysql.com/doc/refman/8.0/en/insert.html

```sql
INSERT INTO tbl_name SET col_a = 'hoge', col_b = 'huga';
```

It's a valid SQL, so even if you just parse...

**Comment by taozhi8833998** [comment]
fix that, try the new release `1.9.2` version

**Comment by ya-saka** [comment]
Thank you very much.
I used PayPal for the first time.

**Comment by taozhi8833998** [comment]
> Thank you very much.
> I used PayPal for the first time.

Thank u for ur support!!!  Working harder, hhhh
