### ISSUE TITLE
TSQL UNIQUEIDENTIFIER not supported

### ISSUE THREAD

**Issue by esetnik** [taozhi8833998/node-sql-parser#296]
**Describe the bug**
Failure on `UNIQUEIDENTIFIER` https://docs.microsoft.com/en-us/sql/t-sql/data-types/uniqueidentifier-transact-sql?view=sql-server-ver15

**Database Engine**
transactsql

**To Reproduce**
-the SQL that be parsed
```sql
CREATE TABLE test (
  uuid UNIQUEIDENTIFIER NOT NULL DEFAULT(NEWID()) UNIQUE,
);
```

-the node-sql-parser version
1.10.0
-the node version
12.16.3

**Expected behavior**
No error as this is valid TSQL

Related to #174

**Comment by taozhi8833998** [comment]
I will fix it today

**Comment by taozhi8833998** [comment]
try `1.10.1`

**Comment by esetnik** [comment]
Working well, thanks!
