### ISSUE TITLE
TSQL NVARCHAR not supported

### ISSUE THREAD

**Issue by esetnik** [taozhi8833998/node-sql-parser#301]
**Describe the bug**
Error when parsing NVARCHAR. https://docs.microsoft.com/en-us/sql/t-sql/data-types/nchar-and-nvarchar-transact-sql?view=sql-server-ver15

**Database Engine**
transactsql

**To Reproduce**
-the SQL that be parsed
```
CREATE TABLE test (
  test NVARCHAR(MAX) NOT NULL,
);
```

-the node-sql-parser version
1.10.1
-the node version
12.16.3

**Expected behavior**
No error since it's valid TSQL

Related to #174

**Comment by taozhi8833998** [comment]
gotcha, it will be supported today

**Comment by taozhi8833998** [comment]
I have released `1.10.2` version, give it a shot!!

**Comment by esetnik** [comment]
Thanks works perfectly.
