### ISSUE TITLE
TSQL CHECK not supported

### ISSUE THREAD

**Issue by esetnik** [taozhi8833998/node-sql-parser#304]
**Describe the bug**
https://docs.microsoft.com/en-us/sql/relational-databases/tables/create-check-constraints?view=sql-server-ver15

**Database Engine**
transactsql

**To Reproduce**
-the SQL that be parsed
```sql
CEATE TABLE test (
  passing_score INT NOT NULL CHECK (passing_score >= 0 AND passing_score <= 100),
);
```
-the node-sql-parser version
1.10.2
-the node version
12.16.3

**Expected behavior**
No error

**Comment by esetnik** [comment]
Related to #174

**Comment by taozhi8833998** [comment]
under developing

**Comment by taozhi8833998** [comment]
oh god, it took me half a day to support the constraint check type in Transact-SQL and MySQL, but it works finally, you could try the new version `1.11.0` later.

**Comment by esetnik** [comment]
> oh god, it took me half a day to support the constraint check type in Transact-SQL and MySQL, but it works finally, you could try the new version `1.11.0` later.

Wow. Thanks for your effort!

**Comment by taozhi8833998** [comment]
> > oh god, it took me half a day to support the constraint check type in Transact-SQL and MySQL, but it works finally, you could try the new version `1.11.0` later.
> 
> Wow. Thanks for your effort!

if it works, close the issue when it's convenient for u.
