### ISSUE TITLE
TSQL DATETIME not supported

### ISSUE THREAD

**Issue by esetnik** [taozhi8833998/node-sql-parser#305]
**Describe the bug**
https://docs.microsoft.com/en-us/sql/t-sql/data-types/datetime-transact-sql?view=sql-server-ver15

**Database Engine**
transactsql

**To Reproduce**
-the SQL that be parsed
```sql
CREATE TABLE test (
  created_at DATETIME NOT NULL DEFAULT GETDATE(),
);
```
-the node-sql-parser version
1.10.2
-the node version
12.16.3

**Expected behavior**
No error

**Comment by esetnik** [comment]
Related to #174

**Comment by taozhi8833998** [comment]
fixed, will be supported in the next version.

**Comment by taozhi8833998** [comment]
try `1.11.0`

**Comment by taozhi8833998** [comment]
I will close it since it has been supported.
