### ISSUE TITLE
SQLite support

### ISSUE THREAD

**Issue by wballard** [taozhi8833998/node-sql-parser#307]
Would be great to have SQLite support as well for two projects I'm doing. Let me know if this is in your plan, otherwise I'll go at it.

**Comment by taozhi8833998** [comment]
@wballard SQLite is on the way. I will develop it next week after I finished the BigQuery. Further notice, you could also make a pr to the project to support SQLite.

**Comment by wballard** [comment]
Oh fantastic -- I'll keep a look for it -- and give it a thorough test and PR any issues I find. I'll see if I can recycle SQLite's tests itself to see if we can parse everything!

**Comment by taozhi8833998** [comment]
ok, any progress I made will be described here.

**Comment by fcsonline** [comment]
Is there any plan to have this? Can we help?

**Comment by taozhi8833998** [comment]
@fcsonline @wballard Sorry for the slow progress that caused by myself, I will post it late.

**Comment by taozhi8833998** [comment]
- remove righe and full join
- support analyze

**Comment by jchnxu** [comment]
<img width="885" alt="image" src="https://user-images.githubusercontent.com/4531670/206866663-80dd285f-2b17-492a-82c7-a1466eed4102.png">

still not available in 4.6.1? 

But I actually build the sqlite.pegjs file myself and it seems working?

**Comment by taozhi8833998** [comment]
@jchnxu it can parse SQLite now, but not 100% percent. if you have any issues, please let me know.

**Comment by jchnxu** [comment]
Sorry I didn't present it clearly enough.

In version 4.6.1, when I try to parse sqlite ( a really simple `select * from table_name` ) the following errors are shown.

```
Error: Cannot find module './expr'
Require stack:
- /path/to/project/node_modules/node-sql-parser/build/sqlite.js
- /path/to/project/build/server/index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at /path/to/project/node_modules/node-sql-parser/build/sqlite.js:5:22
    at Object.<anonymous> (/path/to/project/node_modules/node-sql-parser/build/sqlite.js:13:3)
    ...
```

1. I checked build/sqlite.js. Like in my screenshot in the above comment shows, it's not a generated peg.js parser file like build/mysql.js
2. I manually build sqlite.pegjs file and replaced build/sqlite.js, it works.

I guess we need to build sqlite.pegjs and put it in the npm package?

**Comment by taozhi8833998** [comment]
@jchnxu sorry for the build failed for SQLite, You can do it manually as you said. I will fix it in the next version, thanks.

**Comment by taozhi8833998** [comment]
@jchnxu try the latest version `4.6.2`. Sorry for that again.
