### ISSUE TITLE
TSQL Trailing comma on CREATE TABLE not supported

### ISSUE THREAD

**Issue by esetnik** [taozhi8833998/node-sql-parser#308]
**Describe the bug**
Technically a trailing comma is ignored in CREATE TABLE statements (at least in TSQL). I couldn't find any documentation to confirm this, but it works without issue when you actually run those queries.

**Database Engine**
transactsql

**To Reproduce**
-the SQL that be parsed
```sql
CREATE TABLE test (
  [test_col] BIT NOT NULL DEFAULT(1),
);
```
-the node-sql-parser version
1.11.0
-the node version
12.16.3

**Expected behavior**
No error in this case, as it's technically valid. But `,,` should error in the example below.

```sql
CREATE TABLE test (
  [test_col] BIT NOT NULL DEFAULT(1),,
);
```

**Additional context**
https://stackoverflow.com/questions/20961185/why-doesnt-a-trailing-comma-after-the-last-field-matter-when-creating-a-table-u/20961244

**Comment by taozhi8833998** [comment]
fixed it, will be published in `2.0.1-beta` version

**Comment by taozhi8833998** [comment]
published

**Comment by taozhi8833998** [comment]
I will close the issue since it has been supported. if not, you can reopen it or open another issue.
