### ISSUE TITLE
TSQL NONCLUSTERED INDEX not supported

### ISSUE THREAD

**Issue by esetnik** [taozhi8833998/node-sql-parser#309]
**Describe the bug**
https://docs.microsoft.com/en-us/sql/t-sql/statements/create-index-transact-sql?view=sql-server-ver15

**Database Engine**
transactsql

**To Reproduce**
-the SQL that be parsed
```sql
CREATE NONCLUSTERED INDEX ix_test ON [test] ([test_col]);
```

-the node-sql-parser version
1.11.0
-the node version
12.16.3

**Expected behavior**
No error

**Comment by taozhi8833998** [comment]
@esetnik I am working on it

**Comment by taozhi8833998** [comment]
@esetnik parsed successfully, and I am adding more test cases on it. I will release a new version today.

**Comment by taozhi8833998** [comment]
try `2.0.3-beta` version
