### ISSUE TITLE
TSQL 'AS' computed column not supported

### ISSUE THREAD

**Issue by esetnik** [taozhi8833998/node-sql-parser#310]
**Describe the bug**
https://docs.microsoft.com/en-us/sql/relational-databases/tables/specify-computed-columns-in-a-table?view=sql-server-ver15#TsqlProcedure

**Database Engine**
transactsql

**To Reproduce**
-the SQL that be parsed
```sql
CREATE TABLE test (
  id BIGINT NOT NULL PRIMARY KEY IDENTITY(1, 1),
  questions_correct BIGINT NOT NULL DEFAULT(0),
  questions_total BIGINT NOT NULL,
  score AS questions_correct * 100 / questions_total
);
```
-the node-sql-parser version
1.11.0
-the node version
12.16.3

**Expected behavior**
No error

**Comment by taozhi8833998** [comment]
it has been supported in `2.0.1-beta` version.

**Comment by taozhi8833998** [comment]
published

**Comment by taozhi8833998** [comment]
I will close the issue since it has been supported. if not, you can reopen it or open another issue.
