### ISSUE TITLE
Parser unable to handle valid Postgres single quote

### ISSUE THREAD

**Issue by arana3** [taozhi8833998/node-sql-parser#314]
**Describe the bug**

When using the parser under 'postgresql' mode, an AST fails to form due inability to parse " '' " two single quotes.

**Database Engine**
PostgreSQL.

**To Reproduce**
-the SQL that be parsed : 

`insert into my_table(business_unit_name, business_unit_description, client_id) values('My Hotel''s Name','Hotel ABC was founded in 1980. The company''s investors include ABC, XYZ', 999);`

-the node-sql-parser version : 1.10.2
-the node version: v12.16.1

**Expected behavior**
I expect the parser to generate AST with correct columns.

**Screenshots**
![image](https://user-images.githubusercontent.com/4266851/82612165-39784280-9b90-11ea-9a6c-6df437e9fa31.png)

**Additional context**
None at this time

**Comment by taozhi8833998** [comment]
I think the `'` is required to be escaped when it appears in another string, which quoted by the same symbol `'`.

```SQL
insert into my_table(business_unit_name, business_unit_description, client_id) values('My Hotel\'\'s Name','Hotel ABC was founded in 1980. The company\'\'s investors include ABC, XYZ', 999);
```
the parsed result is as below:

```json
{
    "type":"insert",
    "table":[
        {
            "db":null,
            "table":"my_table",
            "as":null
        }
    ],
    "columns":[
        "business_unit_name",
        "business_unit_description",
        "client_id"
    ],
    "values":[
        {
            "type":"expr_list",
            "value":[
                {
                    "type":"single_quote_string",
                    "value":"My Hotel''s Name"
                },
                {
                    "type":"single_quote_string",
                    "value":"Hotel ABC was founded in 1980. The company''s investors include ABC, XYZ"
                },
                {
                    "type":"number",
                    "value":999
                }
            ]
        }
    ],
    "partition":null,
    "returning":null
}
```
Correct me if I am wrong.
