### ISSUE TITLE
TSQL ALTER COLUMN not supported

### ISSUE THREAD

**Issue by esetnik** [taozhi8833998/node-sql-parser#317]
**Describe the bug**
https://docs.microsoft.com/en-us/sql/t-sql/statements/alter-table-transact-sql?view=sql-server-ver15

**Database Engine**
transactsql

**To Reproduce**
-the SQL that be parsed
```sql
ALTER TABLE [test] ALTER COLUMN [a] NVARCHAR(MAX) NOT NULL;
```
-the node-sql-parser version
v2.0.3-beta
-the node version
v12.16.3

**Comment by taozhi8833998** [comment]
supported it, try `2.0.4-beta`
