### ISSUE TITLE
TSQL DROP PROCEDURE not supported

### ISSUE THREAD

**Issue by esetnik** [taozhi8833998/node-sql-parser#318]
**Describe the bug**
https://docs.microsoft.com/en-us/sql/t-sql/statements/drop-procedure-transact-sql?view=sql-server-ver15

**Database Engine**
transactsql

**To Reproduce**
-the SQL that be parsed
```sql
DROP PROCEDURE [test];
```
-the node-sql-parser version
v2.0.3-beta
-the node version
v12.16.3

**Comment by taozhi8833998** [comment]
supported it. I will release a new version today.

**Comment by esetnik** [comment]
@taozhi8833998 when will you release v2.0 non-beta version? I am waiting to upgrade `[coc-sql](https://github.com/fannheyward/coc-sql)` until this package is considered stable. I haven't seen any issues in v2.0 which would warrant the beta status.

**Comment by taozhi8833998** [comment]
> @taozhi8833998 when will you release v2.0 non-beta version? I am waiting to upgrade [coc-sql](https://github.com/fannheyward/coc-sql) until this package is considered stable. I haven't seen any issues in v2.0 which would warrant the beta status.

@esetnik `BigQuery` syntax is stable now without more issues, I will publish a stable new version `2.0.5` now.
