### ISSUE TITLE
support commands like Alter, Rename, Drop, Truncate etc

### ISSUE THREAD

**Issue by taozhi8833998** [taozhi8833998/node-sql-parser#33]
- support commands like Alter, Rename, Drop, Truncate etc

**Comment by taozhi8833998** [comment]
- support rename, drop and truncate in commit f9ab2c4c7ba875c38c6464d915705b454587abe3

**Comment by Quinncuatro** [comment]
Thanks for this @taozhi8833998 - I'm going to use your code to try and add CALL as well.

**Comment by taozhi8833998** [comment]
closed this issue since it has been solved in *1.3.1* version
