### ISSUE TITLE
TSQL DECLARE not supported

### ISSUE THREAD

**Issue by esetnik** [taozhi8833998/node-sql-parser#331]
**Describe the bug**
https://docs.microsoft.com/en-us/sql/t-sql/language-elements/declare-local-variable-transact-sql?view=sql-server-ver15

**Database Engine**
transactsql

**To Reproduce**
-the SQL that be parsed
```
DECLARE @QuizID BIGINT;
INSERT INTO quiz 
(name, max_attempts, num_questions, passing_score)
VALUES ('Class Quiz', 3, 10, 70);
SELECT @QuizID = (SELECT SCOPE_IDENTITY());
```
-the node-sql-parser version
v2.0.5
-the node version
v12.17.0

**Comment by taozhi8833998** [comment]
got it

**Comment by taozhi8833998** [comment]
@esetnik supported in `2.0.6` version.

**Comment by esetnik** [comment]
Thank you!
