### ISSUE TITLE
DB2 Support

### ISSUE THREAD

**Issue by brad55590** [taozhi8833998/node-sql-parser#332]
Firstly I would like to say great job so far. 
Secondly, would you be able to create a DB2 parser?

Regards

**Comment by taozhi8833998** [comment]
I haven't use db2 for now, but I can do it if you show me the detailed SQL syntax.

**Comment by brad55590** [comment]
So far the mysql parser seems to work well. I have found that it does not to lateral joins though.

I will find more details around db2 queries and post them here. Thank you for the rapid response.

**Comment by taozhi8833998** [comment]
> So far the mysql parser seems to work well. I have found that it does not to lateral joins though.
> 
> I will find more details around db2 queries and post them here. Thank you for the rapid response.

ok, it's my pleasure.

**Comment by taozhi8833998** [comment]
> https://www.ibm.com/developerworks/data/tutorials/dm0608cao2/index.html
> Syntax very similar to SQL and MySQL, I have found that there are some issues with using the MySQL Parser, where if i need to use a "tool" like "SYSTOOLS.BSON2JSON(columnName)" i get an error saying its expecting special chars, but got "."

it could be more helpful if you can show me the original SQL.

**Comment by brad55590** [comment]
Hi

Below are 3 simple examples of queries that we use. The first example works 100%.

select col1, col2 from library.table where col1 = 'foo' limit 5 - Works
select col1, col2 from library.table where col1 = 'foo' fetch first 5 rows - Does not work due to FETCH FIRST 5 ROWS. Error: Expected "#", ",", "--", "/*", ";", "LIMIT", "UNION", [ \t\n\r], or end of input but "F" found.
select col1, SYSTOOLS.BSON2JSON(col2) from library.table - Not Working due to SYSTOOLS.BSON2JSON(col2) complains: Expected "!=", "#", "%", "&&", ")", "*", "+", ",", "-", "--", "->", "->>", "/", "/*", "<", "<=", "<>", "=", ">", ">=", "AND", "AS", "BETWEEN", "IN", "IS", "LIKE", "NOT", "OR", "||", [ \t\n\r], or [A-Za-z0-9_:] but "(" found.

**Comment by taozhi8833998** [comment]
> Hi
> 
> Below are 3 simple examples of queries that we use. The first example works 100%.
> 
> select col1, col2 from library.table where col1 = 'foo' limit 5 - Works
> select col1, col2 from library.table where col1 = 'foo' fetch first 5 rows - Does not work due to FETCH FIRST 5 ROWS. Error: Expected "#", ",", "--", "/_", ";", "LIMIT", "UNION", [ \t\n\r], or end of input but "F" found. select col1, SYSTOOLS.BSON2JSON(col2) from library.table - Not Working due to SYSTOOLS.BSON2JSON(col2) complains: Expected "!=", "#", "%", "&&", ")", "_", "+", ",", "-", "--", "->", "->>", "/", "/*", "<", "<=", "<>", "=", ">", ">=", "AND", "AS", "BETWEEN", "IN", "IS", "LIKE", "NOT", "OR", "||", [ \t\n\r], or [A-Za-z0-9_:] but "(" found.

got it. I will add it as soon as possible.

**Comment by taozhi8833998** [comment]
try `2.1.0` the new release

```javascript
const { Parser } = require('node-sql-parse')
const parser = new Parser()
const opt = {
  database: 'db2'
}
const sql = "select col1, col2 from library.table where col1 = 'foo' fetch first 5 rows only"

console.log(parser.astify(sql))
```

**Comment by brad55590** [comment]
Good Day,
Thank you very much, the changes are working well.

I am happy to close this ticket and will reopen a new one if any more changes are required.

Great Job.

**Comment by taozhi8833998** [comment]
> Good Day,
> Thank you very much, the changes are working well.
> 
> I am happy to close this ticket and will reopen a new one if any more changes are required.
> 
> Great Job.

ok, it's my pleasure.
