### ISSUE TITLE
Over partition is not supported in Hive

### ISSUE THREAD

**Issue by damilaufer** [taozhi8833998/node-sql-parser#341]
**Describe the bug**
I try to parse with the { database: 'Hive' } option the SQL statement below, and it throws an error.

**Database Engine**
Hive

**To Reproduce**
-the SQL that be parsed
SELECT max( ST.ppwc_elig_amt_high )
FROM "PitHive.Horton.edw.dim_cust_extn_odm" as ST
INNER JOIN
(SELECT * FROM "PitHive.Horton.edw.dim_cust" AS JT_1 )
ON ST.cust_id = JT_1.cust_id
LEFT JOIN
(SELECT * FROM "PitHive.Horton.edw.cdim_country" AS JT_2 WHERE 1=row_number() over (partition by JT_2.cntry_code , JT_2.cntry_curr_code order by JT_2.cntry_code , JT_2.cntry_curr_code ))
ON JT_1.prmry_reside_cntry_code = JT_2.cntry_code
WHERE ( ST.ppwc_actv_flag ='1' and lower( ST.ppwc_mkt_supp_y_n )='n')
GROUP BY ST.cust_id

-the node-sql-parser version
^1.10.2
-the node version
v10.16.3

**Expected behavior**
The SQL statement should have been parsed

**Screenshots**

**Additional context**

**Comment by taozhi8833998** [comment]
I will fix it later.

**Comment by damilaufer** [comment]
Thank you.

**Comment by taozhi8833998** [comment]
@damilaufer try `2.1.1` version, which I have published

**Comment by damilaufer** [comment]
That was fast, but the version in npm is still 2.0.6.

**Comment by taozhi8833998** [comment]
> That was fast, but the version in npm is still 2.0.6.

Hmm, Sorry for that, republished it successfully. check it again.

**Comment by damilaufer** [comment]
Thank you, it's working.
