### ISSUE TITLE
Error with nested select query

### ISSUE THREAD

**Issue by anton164** [taozhi8833998/node-sql-parser#343]
I get an error when parsing a nested Select, but would expect this to work.

**Database Engine:** MySQL
**node-sql-parser version:** 2.0.6
**node version:** 13.8.0

SQL: 
```
select distinct org_label, org_id from (
              select distinct org_label, org_id from organizations.features where org_label is not null
              union all
              select distinct org_label, org_id from organizations.metrics where org_label is not null
              select distinct org_label, org_id from organizations.subscription where org_label is not null
              union all
          )
```

```
Expected "#", "%", ")", "*", "+", "-", "--", "/", "/*", "AND", "GROUP", "HAVING", "LIMIT", "OR", "ORDER", "UNION", or [ \t\n\r] but "s" found.
```

**Comment by damilaufer** [comment]
1. Every derived table must have its own alias, like:
    select id from (select * from myTable) **_as m_**
2. You've got a "union all" at the end of your query.

**Comment by anton164** [comment]
Hmm, I see, this is a generated query from a tool I use, so apologies! I should have ran this through an SQL validator first
