### ISSUE TITLE
for update parse error

### ISSUE THREAD

**Issue by adminy** [taozhi8833998/node-sql-parser#351]
**Describe the bug**
Missing syntax, parse error for mysql "FOR UPDATE" at the end of query.

**Database Engine**
MySQL

**To Reproduce**
```
select SOME_COLUMN from TABLE_NAME where ID_COLUMN = 0  for update
                                                        ^^^^^^^^^^

```

**Comment by taozhi8833998** [comment]
@adminy please open an issue based on the template for more info.

**Comment by taozhi8833998** [comment]
@adminy  I will close it if you couldn't update the issue based on the template.

**Comment by adminy** [comment]
Updated

**Comment by taozhi8833998** [comment]
try `2.2.3` version

**Comment by adminy** [comment]
Yes that did it, sorry for the late testing, thank you very much!
