### ISSUE TITLE
Type column parse error

### ISSUE THREAD

**Issue by adminy** [taozhi8833998/node-sql-parser#352]
**Describe the bug**
TYPE cannot be used as a column name

**Database Engine**
MySQL

**To Reproduce**
```
update TABLE_NAME set TYPE = 'something'  where ID_COLUMN = 0
                      ^^^^

```

**Comment by taozhi8833998** [comment]
@adminy please open an issue based on the template for more info.

**Comment by taozhi8833998** [comment]
`type` is a keyword, I can remove it, but I don't know which DB you are using.

**Comment by adminy** [comment]
mysql

**Comment by taozhi8833998** [comment]
@adminy you should open an issue based on the template that I provided next time. I will remove `type` in MySQL as keyword in `2.2.2` version.
