### ISSUE TITLE
EXTRACT() parse error

### ISSUE THREAD

**Issue by thomaspiller** [taozhi8833998/node-sql-parser#354]
First of all, thanks for this great parser!

**Describe the bug**
I get an error when the EXTRACT() function is used in a query.

**Database Engine**
PostgreSQL

**To Reproduce**
Here is an minimal example to reproduce this error:
https://runkit.com/thomaspiller/5efb170e7d79d4001b95b057

**Comment by taozhi8833998** [comment]
I will support `EXTRACT` function in pg as soon as possible.

**Comment by thomaspiller** [comment]
Thanks!

**Comment by taozhi8833998** [comment]
@thomaspiller `2.2.1` version has been released, you can give it a shot.

**Comment by thomaspiller** [comment]
The example provided above is functional with version 2.2.1.
Unfortunately, support for the EXTRACT() function is only partial as an error is returned when a CTE is used.
Basic example: https://runkit.com/thomaspiller/5efb5016ebfc13001a9d9644

**Comment by taozhi8833998** [comment]
@thomaspiller ok, I thought it can only extract from a string rather than a column before, I will add it later.

**Comment by taozhi8833998** [comment]
@thomaspiller sorry for that, you could try the new release `2.2.2` .

**Comment by thomaspiller** [comment]
I just tested my code with version 2.2.2 and everything works well.
Many thanks.
