### ISSUE TITLE
Cannot parse PostgresDB dot concatenated table names

### ISSUE THREAD

**Issue by Samlinxia** [taozhi8833998/node-sql-parser#356]
**Describe the bug**
In PostgresDB, table names are <db-name>.<schema>.<table-name>.  When using parser.parse('select id from db-name.public.table-name'), throw this error:
```
  ● SqlParser › select table and column list › encountered a declaration exception

    SyntaxError: Expected "'", ",", "--", "/*", ";", "AS", "FULL", "GROUP", "HAVING", "INNER", "JOIN", "LEFT", "LIMIT", "ORDER", "RIGHT", "UNION", "WHERE", "\"", "`", [ \t\n\r], [A-Za-z0-9_], [A-Za-z_], or end of input but "." found.
```
I think it's because the table name doesn't allow more than one dots concatenation.  Do 

**Database Engine**
PostgreSQL.

**To Reproduce**
parser.parse('select id from db-name.public.table-name')

**Comment by taozhi8833998** [comment]
@Samlinxia It has been supported in `2.2.2`, try it.

**Comment by Samlinxia** [comment]
@taozhi8833998 , it works! 非常感谢！

**Comment by taozhi8833998** [comment]
> @taozhi8833998 , it works! 非常感谢！

u r welcome, it's my pleasure.
