### ISSUE TITLE
[FeatureRequest] Support typescript types

### ISSUE THREAD

**Issue by Samlinxia** [taozhi8833998/node-sql-parser#366]
Do you have any plans to support Typescript?  It's trending popular in the companies using NodeJS.  By typing the interface, the program is more robust and developers are more productive.  This library is awesome, but one of my frustrating experiences is that there seems no clue about the structure of the returned `ast` in ` const {ast} = parser.parse()`.  If you don't have a plan to support, can you point me to the docs or code about the type structure of parameters?  Thanks!

**Comment by taozhi8833998** [comment]
@Samlinxia the module has [types](https://github.com/taozhi8833998/node-sql-parser/blob/master/index.d.ts) file, I have deprecated `@types/node-sql-parser`.

**Comment by Samlinxia** [comment]
Thanks @taozhi8833998. That's very helpful.  There is a typo here where `columnsList` should be `columnList`
https://github.com/taozhi8833998/node-sql-parser/blob/master/index.d.ts#L19

**Comment by taozhi8833998** [comment]
> Thanks @taozhi8833998. That's very helpful. There is a typo here where `columnsList` should be `columnList`
> https://github.com/taozhi8833998/node-sql-parser/blob/master/index.d.ts#L19

ok, I will update it later

**Comment by Samlinxia** [comment]
@taozhi8833998 : do you have plan to open the permission of this project to let others commit?  I tried to send out a PR to fix it but hits a permission error.

**Comment by taozhi8833998** [comment]
> @taozhi8833998 : do you have plan to open the permission of this project to let others commit? I tried to send out a PR to fix it but hits a permission error.

maybe some settings goes wrong?? Others could open PR for this project before, I will check it later. Sorry for that.

**Comment by taozhi8833998** [comment]
@Samlinxia  I have invited you as a collaborator for this project, you can agree with it, and try again. I will find the corresponding setting in Github for anyone can open PR for it later.

**Comment by taozhi8833998** [comment]
> @taozhi8833998 : do you have plan to open the permission of this project to let others commit? I tried to send out a PR to fix it but hits a permission error.

@Samlinxia maybe you need fork this project, and push code to ur fork repository, then open PR for ur commits
