### ISSUE TITLE
Hive false positive parsing sql without spaces

### ISSUE THREAD

**Issue by damilaufer** [taozhi8833998/node-sql-parser#368]
**Describe the bug**
The parser returns "valid" for an invalid SQL

**Database Engine**
HIVE

**To Reproduce**
-the SQL that be parsed
SELECT * FROM table WHERE col1 =1and col2 = 3
-the node-sql-parser version
2.1.1
-the node version
10.16.3

**Expected behavior**
The parser should indicate an invalid SQL near "=1and"

**Screenshots**

**Additional context**

**Comment by taozhi8833998** [comment]
it has been fixed in `2.2.6`. Thank you for finding the bug.

**Comment by damilaufer** [comment]
Thank you, it is working!
