### ISSUE TITLE
cannot parse `real` in transact-sql

### ISSUE THREAD

**Issue by shusson** [taozhi8833998/node-sql-parser#370]
**Describe the bug**
Cannot parse [real](https://docs.microsoft.com/en-us/sql/t-sql/data-types/float-and-real-transact-sql?view=sql-server-ver15) in transactsql

**Database Engine**
SQL server 2019

**To Reproduce**

```sql
CREATE TABLE [dbo].[foo]
(
    [test] [real] NULL
);
```

```
peg$SyntaxError: Expected "#", ")", ",", "--", ".", "/*", "AS", "BIGINT", "BIT", "CHAR", "DATE", "DATETIME", "DECIMAL", "DOUBLE", "FLOAT", "INT", "INTEGER", "JSON", "LONGTEXT", "MEDIUMTEXT", "MONEY", "NCHAR", "NUMERIC", "NVARCHAR", "SMALLINT", "SMALLMONEY", "TEXT", "TIME", "TIMESTAMP", "TINYINT", "TINYTEXT", "UNIQUEIDENTIFIER", "VARCHAR", or [ \t\n\r] but "r" found
```

- node-sql-parser 2.2.3
- node 12.14

**Expected behavior**
can parse `real`

**workaround**
use float(24)

**Comment by taozhi8833998** [comment]
@shusson try `2.2.5`

**Comment by shusson** [comment]
👍 tested with 2.2.6

**Comment by taozhi8833998** [comment]
thx
