### ISSUE TITLE
"create index on mytable(mycolumn);" => syntax error.

### ISSUE THREAD

**Issue by oguimbal** [taozhi8833998/node-sql-parser#383]
**Describe the bug**: Create index statements are throwing parse errors.
**Database Engine**:  All ?  (fails on PostgreSQL...)

**To Reproduce**
```javascript
const p = new Parser();
p.astify('create index on test(value)', { { database: 'PostgresQL' }); // <== throws an error
```

**Expected behavior**: This statement is valid SQL... i would expect it to work :)

Thanks for this nice lib :)

**Comment by taozhi8833998** [comment]
@oguimbal I will add it today.

**Comment by oguimbal** [comment]
Wow, thanks :)

**Comment by taozhi8833998** [comment]
@oguimbal `2.3.0` version has been published to support it, try it.

**Comment by oguimbal** [comment]
I have :) Works like a charm. Thank you !
