### ISSUE TITLE
Cannot astify pg SQL with columns like "t1"."col1" (column name quoted by "")

### ISSUE THREAD

**Issue by deeper-thought** [taozhi8833998/node-sql-parser#389]
**Describe the bug**
Cannot astify pg SQL with columns like  "t1"."col1" (column name quoted by "")
such as:
SELECT "t1"."uid", "t1"."username" FROM "t1"

such error is thrown:
peg$SyntaxError {message: "Expected "*", "--", "/*", or [ \t\n\r] but "\"" found.", expected: Array(8), found: """, location: {…}, name: "SyntaxError", …}

**Database Engine**
PostgreSQL

**To Reproduce**
-the SQL that be parsed
SELECT "t1"."uid", "t1"."username" FROM "t1"
-the node-sql-parser version
2.3.0
-the node version
Chrome 83

**Expected behavior**
Astify the SQL successfully.

**Screenshots**
![image](https://user-images.githubusercontent.com/36871982/87891303-14a72b00-ca6c-11ea-8983-b04497dbe166.png)

**Additional context**
It cannot even astify pg SQL successfully sqlified by the lib itself.

**Comment by taozhi8833998** [comment]
@deeper-thought It has been supported and will be released in the next version.

**Comment by taozhi8833998** [comment]
@deeper-thought try `3.0.1` version.
