### ISSUE TITLE
support for prepared statements 

### ISSUE THREAD

**Issue by lolopinto** [taozhi8833998/node-sql-parser#396]
**Describe the bug**
cannot parse prepared statements

**Database Engine**
mysql or postgres

**To Reproduce**
`const ast = parser.parse("SELECT bar, baz, foo FROM tablename WHERE bar = 1");`
works

`const ast = parser.parse("SELECT bar, baz, foo FROM tablename WHERE bar = ?");  // mysql` 
`const ast = parser.parse("SELECT bar, baz, foo FROM tablename WHERE bar = $1");  // postgres` 

doesn't

**Expected behavior**
sql statement to be parsed and `where` should reflect the prepared statement values

**Screenshots**
![image](https://user-images.githubusercontent.com/10857143/88226601-2978ef80-cc21-11ea-81b3-c7be910da547.png)

**Comment by taozhi8833998** [comment]
@lolopinto got it, I will support it asap. Thanks for ur issue.

**Comment by lolopinto** [comment]
thanks!

**Comment by taozhi8833998** [comment]
@lolopinto try `3.0.2` version.

**Comment by lolopinto** [comment]
@taozhi8833998 it seems to work when there's one field but not multiple e.g.

`const ast = parser.parse("SELECT bar, baz, foo FROM tablename WHERE bar = ?");` works

but not 

`const ast = parser.parse("SELECT bar, baz, foo FROM tablename WHERE bar = ? AND baz = ?");`

![image](https://user-images.githubusercontent.com/10857143/88318128-22a8b600-cccf-11ea-8ac8-43ad9bbec000.png)

**Comment by taozhi8833998** [comment]
@lolopinto sorry for that, my bad. I have fixed it in `3.0.3` version, please give it a shot.

**Comment by lolopinto** [comment]
awesome, thanks so much!

**Comment by taozhi8833998** [comment]
@lolopinto if it has been fixed, close the issue when it's convenient for u.
