### ISSUE TITLE
double-quoted label should be column or table identifier, not literal string

### ISSUE THREAD

**Issue by jingsam** [taozhi8833998/node-sql-parser#402]
**Describe the bug**

Both PostgreSQL and ANSI SQL standard treate double-quoted label as column or table identifier. literal string should be single-quoted.

Althrough double quotes are supported by MySQL for string values as well, but single quotes are more widely accepted by other RDBMS, so it is a good habit to use single quotes instead of double.

**Database Engine**
which database engine does your SQL running on? such as MySQL, PostgreSQL.
PostgreSQL

**To Reproduce**
-the SQL that be parsed
```
select "a" from t;
```
-the node-sql-parser version 
3

-the node version
10

**Expected behavior**

should parse `a` as a column identifier

**Screenshots**

parse `a` as a string

```
{
      "with": null,
      "type": "select",
      "options": null,
      "distinct": null,
      "columns": [
        {
          "type": "expr",
          "expr": {
            "type": "string",
            "value": "a"
          },
          "as": null
        }
      ],
      "from": [
        {
          "db": null,
          "table": "t1",
          "as": null
        }
      ],
      "where": null,
      "groupby": null,
      "having": null,
      "orderby": null,
      "limit": null
    }
```

**Additional context**

**Comment by taozhi8833998** [comment]
@jingsam Thanks for pointing it out, I will check it later, and update any progress I made here.
