### ISSUE TITLE
ident_name should not be limited with letters and digits

### ISSUE THREAD

**Issue by jingsam** [taozhi8833998/node-sql-parser#403]
**Describe the bug**
Currently `ident_name` follows such rules:

https://github.com/taozhi8833998/node-sql-parser/blob/1992d7e449ef7896ca4e50cd90f524415a0f0d96/pegjs/postgresql.pegjs#L2245-L2253

There are two kinds of identifiers. Ordinary identifiers are identifiers not surrounded by double quotation marks. Delimited identifiers are identifiers surrounded by double quotation marks.

According to the [Rules for SQL92 identifiers](https://docs.oracle.com/javadb/10.8.3.0/ref/crefsqlj1003454.html):
> An ordinary identifier must begin with a letter and contain only letters, underscore characters (_), and digits. The permitted letters and digits include all Unicode letters and digits. (Note that the letters are not limited to `[a-zA-z]`, all Unicode letters are permitted)
A delimited identifier can contain any characters within the double quotation marks.

Other databases have similar rules, references links are:
https://docs.microsoft.com/en-us/sql/relational-databases/databases/database-identifiers?view=sql-server-ver15#rules-for-regular-identifiers
https://dev.mysql.com/doc/refman/8.0/en/identifier-qualifiers.html
https://www.postgresql.org/docs/12/sql-syntax-lexical.html#SQL-SYNTAX-IDENTIFIERS
 
**Database Engine**
which database engine does your SQL running on? such as MySQL, PostgreSQL.
PostgreSQL

**To Reproduce**
-the SQL that be parsed
```
select 中文 from t1;
select "中文" from t1;
```

-the node-sql-parser version
3

-the node version
10

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by jingsam** [comment]
PostgreSQL identifier rules:
## Ordinary identifier:
1. begin with a letter (a-z, but also letters with diacritical marks and non-Latin letters) or an underscore (_). 
2.Subsequent characters in an identifier can be letters, underscores, digits (0-9), or dollar signs ($).

## Delimited identifier:
can contain any character, except the character with code zero.

link: https://www.postgresql.org/docs/12/sql-syntax-lexical.html#SQL-SYNTAX-IDENTIFIERS

**Comment by jingsam** [comment]
SQL Server  identifier rules:

## Ordinary identifier:
1. The first character must be one of the following:
- a through z, from A through Z, and also letter characters from other languages.
- The underscore (_), at sign (@), or number sign (#).

2. Subsequent characters can include the following:
- Letters as defined in the Unicode Standard 3.2.
- Decimal numbers from either Basic Latin or other national scripts.
- The at sign, dollar sign ($), number sign, or underscore.

## Delimited identifier:
the identifiers that do not comply with Ordinary identifier rules must be delimited by double quotation marks or brackets.

**Comment by jingsam** [comment]
MySQL identifier rules:

## Ordinary identifier:
- ASCII: [0-9,a-z,A-Z$_] (basic Latin letters, digits 0-9, dollar, underscore)
- Extended: U+0080 .. U+FFFF

## Delimited identifier:
- ASCII: U+0001 .. U+007F
- Extended: U+0080 .. U+FFFF

link: https://dev.mysql.com/doc/refman/8.0/en/identifiers.html

**Comment by taozhi8833998** [comment]
@jingsam Thanks for getting my knowledge up, I will check it in detail later.
