### ISSUE TITLE
Support date/time operations with INTERVAL

### ISSUE THREAD

**Issue by thomaspiller** [taozhi8833998/node-sql-parser#404]
**Describe the bug**
When INTERVAL is used for a date operation, the following sequence generates an invalid SQL statement:
1. create an AST from SQL
2. convert the AST back to SQL
SQL input: `SELECT NOW() - INTERVAL '7 DAY'`
SQL output: ``SELECT NOW() - "INTERVAL" AS  `7 DAY` ``

**Database Engine**
PostgreSQL

**To Reproduce**
See example: https://runkit.com/thomaspiller/interval-node-sql-parser 

**Expected behavior**
Converting the AST back to SQL should generate the initial statement.

**Comment by taozhi8833998** [comment]
@thomaspiller `3.0.4` version has fixed that. See [example](https://runkit.com/taozhi8833998/5df6fe8f21d6b8001be36cb7)

**Comment by thomaspiller** [comment]
It is working fine now. Thank you very much!
