### ISSUE TITLE
WHERE clause: numeric values must be quoted to be parsed to AST

### ISSUE THREAD

**Issue by thomaspiller** [taozhi8833998/node-sql-parser#406]
**Describe the bug**
In the WHERE clause, if a condition is specified on a column of numeric type (tested with integer, smallint, bigint, double precision) and the value is **NOT** single or double quoted, the creation of AST returns this error: `ReferenceError: BigInt is not defined`

**Database Engine**
PostgreSQL

**To Reproduce**
- SQL statement: SELECT AVG(population) FROM < table > WHERE population > 10000
- node-sql-parser 3.0.4
- node v12.16.3

**Expected behavior**
In PostgreSQL, numeric values don't have to be quoted in the WHERE clause. It works if we use single quotes but not with doubles which are reserved to refer to columns by their name.

**Comment by taozhi8833998** [comment]
@thomaspiller I can't reproduce it, can you give me a runkit link to reproduce it.

**Comment by thomaspiller** [comment]
After some tests, I noticed that this bug is reproducible with version 8 of Node.js, which is no longer maintained: https://runkit.com/thomaspiller/where-clause-numeric-condition

Everything works as expected from Node.js v10.
So the problem is on our side, we need to update Node.js in our project. Sorry for that.
