### ISSUE TITLE
sqlify() does not format column names correctly

### ISSUE THREAD

**Issue by vvlookman** [taozhi8833998/node-sql-parser#407]
**Describe the bug**
sqlify(select * from t where a=1) => select * from t where "a"=1
sqlify(select * from t where "a"=1) => select * from t where 'a'=1

**Database Engine**
PostgreSQL

**To Reproduce**
-node-sql-parser version: 3.0.1
-node version: 10.21.0

const parser = new Parser();
const ast = parser.astify(`SELECT * FROM T WHERE "a"=1`, {database: 'PostgreSQL'});
const sql = parser.sqlify(ast, {database: 'PostgreSQL'});

const parser = new Parser();
const ast = parser.astify(`SELECT * FROM T WHERE a=1`, {database: 'PostgreSQL'});
const sql = parser.sqlify(ast, {database: 'PostgreSQL'});

**Expected behavior**
Column names should be wrapped with double-quote.

**Comment by wshart** [comment]
Also having this problem with an accompanying error:
`Unhandled Rejection (Error): undefined statements not supported at the moment`

**Comment by wshart** [comment]
> **Expected behavior**
> Column names **should be** wrapped with double-quote.

Typo? Column names should _not_ be wrapped in ""

**Comment by oguimbal** [comment]
@wshart Yes they should...  if you want to be able to use protected names. For instance 

```sql
insert into table values (42)
```  
is **NOT** a valid statement, while 

```sql
insert into "table" values (42);
```
is valid. Same for column names.

**Comment by wshart** [comment]
@oguimbal You are absolutely right - not sure how I didn't know that!

**Comment by oguimbal** [comment]
I cant blame you, I didnt notice it either before I had to write a parser :)

**Comment by wshart** [comment]
Possibly related, if I astify a query that selects columns with double-quotes, the returned object's columns are given type 'string', rather than 'column_ref'

To reproduce:
`const ast = parser.astify('SELECT "a" FROM "b"', options);
console.log(ast.columns)`

Output:
`[ { type: 'expr', expr: { type: 'string', value: 'a' }, as: null } ]`

**Comment by taozhi8833998** [comment]
@vvlookman fixed, try the latest version.
