### ISSUE TITLE
Support commands like CALL

### ISSUE THREAD

**Issue by Quinncuatro** [taozhi8833998/node-sql-parser#42]

**Comment by Quinncuatro** [comment]
Using a previous issue from @taozhi8833998 to try and add in CALL functionality.

**Comment by Quinncuatro** [comment]
@taozhi8833998 - I created a new pegjs-parser file using https://pegjs.org/online that works for a given CALL command I'm looking to parse.

I changed the beginning and the end of the file to match the one provided in your package (like matching your 'module.exports' object).

However, the changes don't seem to be working when I try to run your example parser script against it.

```javascript
const { Parser } = require('node-sql-parser')
const parser = new Parser()
const ast = parser.astify("CALL whatever and stuff")

console.log(ast)
```

Any idea why that is?

**Comment by Quinncuatro** [comment]
I've tried playing with it myself a few different ways.

How do you go from having a valid and working `sql.pegjs` file to having everything work after `npm run build`? I feel like I'm missing something.

**Comment by taozhi8833998** [comment]
Sorry for the late reply. I have supported for `call` command in *1.3.1* version, you could read more about that in 99085b7d8accfcd439cbf45359eef52eccbbc543

**Comment by Quinncuatro** [comment]
@taozhi8833998 - You're the best! Do you have a Venmo or something so I can send you $5 for a coffee?

**Comment by taozhi8833998** [comment]
> I've tried playing with it myself a few different ways.
> 
> How do you go from having a valid and working `sql.pegjs` file to having everything work after `npm run build`? I feel like I'm missing something.

you need build `sql.pegjs` with [pegjs](https://www.npmjs.com/package/pegjs) module by command like `pegjs -o pegjs-parser.js sql.pegjs`.

**Comment by Quinncuatro** [comment]
I mean that's what I was doing. It just hasn't been working correctly when I run it locally.

Got all of the pegjs working correctly in the online tester, but I was getting a handful of different errors when I tried to build and implement locally.

**Comment by taozhi8833998** [comment]
> @taozhi8833998 - You're the best! Do you have a Venmo or something so I can send you $5 for a coffee?

Thanks for your kindness! I am very happy that my project could help you. You could give a star on this project If it's convenient for you.

**Comment by taozhi8833998** [comment]
> I mean that's what I was doing. It just hasn't been working correctly when I run it locally.
> 
> Got all of the pegjs working correctly in the online tester, but I was getting a handful of different errors when I tried to build and implement locally.

It would be much more clear if you could show me the error msg

**Comment by Quinncuatro** [comment]
Star'd!

> It would be much more clear if you could show me the error msg

Sure thing, just might not be until tomorrow.

**Comment by taozhi8833998** [comment]
> Star'd!
> 
> > It would be much more clear if you could show me the error msg
> 
> Sure thing, just might not be until tomorrow.

it's ok, I'm back from vacations and online for most time
