### ISSUE TITLE
Big Query parser not working on ARRAY(

### ISSUE THREAD

**Issue by MeCode4Food** [taozhi8833998/node-sql-parser#423]
**Describe the bug**
Parser for bigquery breaks on function ARRAY()

**Database Engine**
BigQuery

**To Reproduce**
-the SQL that be parsed
```
SELECT a, b, c, ANY_VALUE(ARRAY(SELECT * FROM UNNEST(JSON_EXTRACT_ARRAY(d)))) AS d
  FROM
    e WHERE LOWER(f)='123'
  GROUP BY
    a,
    b,
    c
```

-the node-sql-parser version
2.3.0

-the node version
12.18.0

**Expected behavior**
Parser works without throwing errors

**Screenshots**
![image](https://user-images.githubusercontent.com/25502412/89879678-df6aa480-dbf5-11ea-997f-59dd69ff1205.png)

Here is the extra information of where the error is located
![image](https://user-images.githubusercontent.com/25502412/89880149-7f283280-dbf6-11ea-8f7c-be0697a9e321.png)

**Additional context**
```javascript
const opt = {
  database: 'BigQuery'
}

const { Parser } = require('node-sql-parser');
const parser = new Parser()
let ast
try {
  ast = parser.astify(`SELECT a, b, c, ANY_VALUE(ARRAY(SELECT * FROM UNNEST(JSON_EXTRACT_ARRAY(d)))) AS d
  FROM
    e WHERE LOWER(f)='123'
  GROUP BY
    a,
    b,
    c`, opt);
} catch (error) {
  console.log(error)
}
console.log('ast', ast)
```
Here is the code that I used to reproduce this error

**Comment by goliatone** [comment]
This issue seems to be similar to [#420](https://github.com/taozhi8833998/node-sql-parser/issues/420).
