### ISSUE TITLE
No support for PostgreSQL ILIKE operators

### ISSUE THREAD

**Issue by wshart** [taozhi8833998/node-sql-parser#424]
**Describe the bug**
Astify does not support the ILIKE operator (the case-insensitive version of LIKE)

**Database Engine**
PostgreSQL.

**To Reproduce**
SELECT * FROM table WHERE 'a' ILIKE 'A'
-the node-sql-parser version: 3.0.4
-the node version: v10.17.0

**Expected behavior**
The above should parse.

**Additional context**
Instead the parser throws a SyntaxError.

**Comment by taozhi8833998** [comment]
@wshart supported in next version.
