### ISSUE TITLE
Get prepared columns only

### ISSUE THREAD

**Issue by Josnic** [taozhi8833998/node-sql-parser#428]
Hi.
First, I want to say this library is excellent. This is not a problem with the library, but its mine. I need get only the prepared columns (?) in a list. Is possible this new functionality?
Thanks.

**Comment by taozhi8833998** [comment]
@Josnic I can't get u clearly. sorry about that. You could show examples of what you want.

**Comment by Josnic** [comment]
Hi @taozhi8833998 

My case is next. I have a prepared query:

`SELECT * FROM tabla WHERE id = ? AND name LIKE '%jos%' AND city_id = ?`

I want only extract columns with ? (as PDO) in frontend. It is not up to the library to fix it, but to the developer. I want to share my solution:

`getPrepared(obj, result = []) {
        let value;
        Object.keys(obj).forEach(key => {
            
          value = obj[key];
          if (key == "right" && obj[key].value && obj[key].value == "?"){
              if (!result.includes(obj))
            result.push(obj);
          }else if (key == "right" && obj[key].type && obj[key].type == "expr_list"){
            if (obj.operator == "BETWEEN"){
               
                var hasParemeter = false;
                for (var i = 0; i < obj[key].value.length; i++){
                    if (obj[key].value[i].value == "?"){
                        hasParemeter = true;
                        i = obj[key].value.length
                    }
                }
                if (hasParemeter){
                    if (!result.includes(obj))
                    result.push(obj);
                }
            }else if (obj.operator == "IN"){
                if (obj[key].value.length == 1 && obj[key].value[0].value == "?"){
                    if (!result.includes(obj))
                    result.push(obj);
                }
            }
          }
          if (value instanceof Object) {
            getPrepared(value, result);
          } 
        });
        return result;
      },` 

Maybe it can be improved and optimized, but it was what I used. I appreciate your attention and it would be great if you extend support to create, alter instructions.
