### ISSUE TITLE
Support concatenation operator (||)

### ISSUE THREAD

**Issue by sergiogiogio** [taozhi8833998/node-sql-parser#43]
Currently an error is reported for statement "SELECT 'a'||'b' FROM t"

{ SyntaxError: Expected "!=", "%", "'", "*", "+", ",", "-", "--", ".", "/", "/*", ";", "<", "<=", "<>", "=", ">", ">=", "AND", "AS", "BETWEEN", "FROM", "GROUP", "HAVING", "IN", "IS", "LIKE", "LIMIT", "NOT", "OR", "ORDER", "UNION", "WHERE", "\"", "`", [ \t\n\r], [A-Za-z_], or end of input but "|" found.
[snip]
name: 'SyntaxError' }

**Comment by Quinncuatro** [comment]
Noticed you put in a couple issues, too. Have you had any luck modifying this?

**Comment by sergiogiogio** [comment]
I have not explored modifying the code, i hope @taozhi8833998 vsn help us out :)

**Comment by Quinncuatro** [comment]
@sergiogiogio - He just added in my request. Might be moving to yours next!

**Comment by taozhi8833998** [comment]
> @sergiogiogio - They just added in my request. Might be moving to yours next!

working on it now

**Comment by taozhi8833998** [comment]
@sergiogiogio It supports `||`(for concatenation in Oracle) and `&&` now, you could read the test cases in 81ff726c24802cdcf4d0b6d38340377a60d2a36a. I will publish new version when another issue unary operators have been developed and tested.
