### ISSUE TITLE
Support unary operators (-x, +x)

### ISSUE THREAD

**Issue by sergiogiogio** [taozhi8833998/node-sql-parser#44]
Currently an error is reported for statement "SELECT -a FROM t"

{ SyntaxError: Expected [0-9] but "a" found.
[snip]
name: 'SyntaxError' }

**Comment by taozhi8833998** [comment]
It can parse unary operators by  commit ce09422e9eb0eb576c736818945f22ecc8087351, you could using it in **1.3.2** version now. If you have any problems with this issue, please let me know it.
