### ISSUE TITLE
Error while parsing multiple LIKE operators in postgres

### ISSUE THREAD

**Issue by thegnuu** [taozhi8833998/node-sql-parser#444]
**Describe the bug**
When using multiple `LIKE` operators the following error occurs:

```
Expected "!=", "#-", "#>", "#>>", "%", "*", "+", "-", "--", "/", "/*", ";", "<", "<=", "<>", "<@", "=", ">", ">=", "?", "?&", "?|", "@>", "BETWEEN", "GROUP", "HAVING", "IN", "IS", "LIKE", "LIMIT", "NOT", "ORDER", "UNION", "||", [ \t\n\r], or end of input but "A" found.
```

**Database Engine**
PostgreSQL

**To Reproduce**
node-sql-parser: 3.0.4
nodejs: 12.13.0

```typescript
import { Parser } from 'node-sql-parser';

const parser = new Parser();

console.log(
  JSON.stringify(
    parser.astify(
      'SELECT "contact"."_id" FROM "contact" WHERE LOWER("contact"."name.givenName") LIKE \'yan%\' AND LOWER("contact"."name.familyName") LIKE \'ei%\';',
      {
        database: 'PostgreSQL',
      },
    ),
    null,
    2,
  ),
);

```

**Expected behavior**
The provided SQL is correct and can be executed by Postgres, therefore this error should not be thrown :)

![Screenshot 2020-09-03 at 11 22 28](https://user-images.githubusercontent.com/5129086/92097055-f147fd80-edd7-11ea-82dd-710802d41ae0.png)

**Comment by taozhi8833998** [comment]
@thegnuu It has been fixed, will be supported in next version.

**Comment by thegnuu** [comment]
Thanks a lot @taozhi8833998
