### ISSUE TITLE
Parse failure

### ISSUE THREAD

**Issue by kpeters-cbsi** [taozhi8833998/node-sql-parser#465]
The query "select id, foo, id AS message_id, author_id, subject, author_name, unix_timestamp(created) AS created, deleted, is_private, unix_timestamp(modified) AS modified, parent_id, data, body, type, views, (select group_concat(id) from content cr where cr.foo=c.foo and cr.parent_id=c.id) AS replies, cp.content_id as pinned from content c LEFT JOIN content_pinned cp ON c.foo = cp.bar AND c.id = cp.content_id AND cp.baz = '1234567890abcdef' where ( not is_private or ( is_private and ( author_id='1234567890abcdef' or JSON_CONTAINS( `data`, 'FFFFFFF-1234-5678-9012-1234567890AB', '$.to' ) ) ) ) and foo = 'quux' and not deleted and not type='reply' and type in ('type1','type2','type3','type4') order by pinned desc,created desc LIMIT 1;" fails to parse. 

Exception: `SyntaxError: Expected "!=", "#", "%", "(", ")", "*", "+", ",", "-", "--", "->", "->>", ".", "/", "/*", "<", "<=", "<>", "=", ">", ">=", "BETWEEN", "IN", "IS", "LIKE", "NOT", or [ \t\n\r] but "o" found.`

I think the problem lies in the WHERE clause, specifically in `where ( not is_private or ( is_private ... )) ...`. The query `'SELECT foo FROM bar WHERE (not quux and 1=1)` works (note "AND"). The query `'SELECT foo FROM bar WHERE (not quux or 1=1)` fails (note "OR").

**Comment by taozhi8833998** [comment]
@kpeters-cbsi The parser could parse it successfully, you can try to upgrade it to the latest version 3.3.0 currently.
