### ISSUE TITLE
TRANSLATE function with an expression argument 

### ISSUE THREAD

**Issue by mlapenna7** [taozhi8833998/node-sql-parser#500]
**Describe the bug**
I supplied a SQL stmt to the parser and I received an error from the parser.astify(sq).
It seems that supplying an expression inside a TRANSLATE causes an error.
For example
select ....
cast(TRANSLATE(substr(a.report_timestamp as string),0,10), ' |-|:','') as decimal(8,0) as report_date,
...
.
If I remove this line, the astify call works.
If replace the substr function with a literal string, it works
![s1](https://user-images.githubusercontent.com/16414318/98827538-fe4f2180-2404-11eb-8e06-e033a91fd4ff.jpg)

**Database Engine**
PostgreSQL 12.3.

**To Reproduce**
-the SQL that be parsed  (attached)
-the node-sql-parser version  v3.1.0
-the node version  v12.18.4

**Expected behavior**
I expected the parsing to go work, not complain at the TRANSLATE

**Screenshots**
(attached( - showing error indicating TRANSLATE
![s1](https://user-images.githubusercontent.com/16414318/98827568-060ec600-2405-11eb-9ba8-2276f275f476.jpg)
![e1](https://user-images.githubusercontent.com/16414318/98827590-0b6c1080-2405-11eb-9b8a-66aa7fe1f10d.jpg)

**Additional context**

**Comment by taozhi8833998** [comment]
@mlapenna7 string is not a valid data type in PostgreSQL, according to [data type](https://www.postgresql.org/docs/9.2/datatype.html). Correct me if I am wrong.
