### ISSUE TITLE
Does this Package Work with Angular 5?

### ISSUE THREAD

**Issue by TommyHubbard** [taozhi8833998/node-sql-parser#532]
Does this package work with Angular?   I don't see a reason why it shouldn't, but it breaks my application when I import it into a component.   I've searched the web and couldn't find any content related to this.   There also isn't a lot of documentation to help with getting started.

When I import the parser into a component, it gives me the following error:

./node_modules/node-sql-parser/build/transactsql.js
Module parse failed: Unexpected token (1:33406)
You may need an appropriate loader to handle this file type.

-----------------------
About my application
-----------------------
Angular Version: 5
Angular Command Line Interface (CLI): 1.7.4
TypeScript: 2.5.3
ECMAScript: ES5

**Comment by TommyHubbard** [comment]
UPDATE:  It looks like the issue might be the typescript file in the build directory.   If I specify **transactsql.d** in the import statement, I get the following error:

Failed to compile.

./node_modules/node-sql-parser/build/transactsql.d.ts
Module build failed: Error: C:\Users\...\node_modules\node-sql-parser\build\transactsql.d.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).

**Comment by taozhi8833998** [comment]
@TommyHubbard got it, I will check it lately

**Comment by taozhi8833998** [comment]
@TommyHubbard It has been fixed.
