### ISSUE TITLE
Is this still active and supported?

### ISSUE THREAD

**Issue by labs20** [taozhi8833998/node-sql-parser#533]
Hi. 

I'm aware about the hard work involved in keep a lib like that up and running, but as I'm using it as a core lib on my project and some very concerning issues had no response for a quite amount of time now, I'd like to gently ask if this lib is still going to see updates and fixes.

I thank you for your hard and nice work so far and for sharing it. It would be really nice to get some light about the future of this amazing project.

Thanks!

**Comment by taozhi8833998** [comment]
@labs20 Thanks for ur concerns, I have been sick for a long time, and now I am better. I will solve the issue one by one.

**Comment by labs20** [comment]
Thank you very much. Its a great lib you have here and your work is much appreciated.

Hope you've sorted all of your personal things in a good way.

Thanks!

**Comment by taozhi8833998** [comment]
@labs20 Got it. Start solving issues now.
