### ISSUE TITLE
Output for `parser.astify("${DELETE_QUERY}")` shows `tables: null`

### ISSUE THREAD

**Issue by Quinncuatro** [taozhi8833998/node-sql-parser#54]
```
const { Parser } = require('node-sql-parser');
const parser = new Parser();

const ast1 = parser.astify("DELETE FROM whatever WHERE Feels = 'Forever';");

console.log(ast1);
```

outputs

```
{ type: 'delete',
  tables: null,
  from: [ { db: null, table: 'ben', as: null } ],
  where:
   { type: 'binary_expr',
     operator: '=',
     left: { type: 'column_ref', table: null, column: 'Feels' },
     right: { type: 'string', value: 'Forever' } } }
```

I feel like I shouldn't have to dig into `ast.from.table` when `ast.tables` works for other types of queries.

**Comment by taozhi8833998** [comment]
it looks like the same issue as #53, `ast.tables` is only working in multiple delete or you specified the deleted table. I can't determine which tables you want to delete. I have supported single table delete SQL, But you have to specified table you want to delete when in multiple delete. Read more about that in [delete](https://dev.mysql.com/doc/refman/8.0/en/delete.html), the commit codes c9bf34f2d0063054d100482fddbb8191afa3b2a8 in

**Comment by taozhi8833998** [comment]
I will publish it in `1.3.4` version later

**Comment by Quinncuatro** [comment]
The way we're using the `DELETE FROM whatever WHERE Feels = 'Forever';` query, it defaults to the same action as `DELETE * FROM whatever WHERE Feels = 'Forever';`
