### ISSUE TITLE
Columns starting with numbers throw error in GROUP BY

### ISSUE THREAD

**Issue by damilaufer** [taozhi8833998/node-sql-parser#574]
**Describe the bug**
Columns starting with numbers are valid in GROUP BY Hive. 
If I write it with backticks it's ok.
When I write the SQL below, I get this error: Syntax error in SQL
Expected [A-Za-z0-9_:] or [A-Za-z0-9_] but " " found. in line 3, around char #13

**Database Engine**
HIVE

**To Reproduce**
-the SQL that be parsed: 
SELECT min(salary)
FROM "MyTable" as ST
WHERE (`ST.3_year_base_employee_count`= 390)
GROUP BY ST.bankruptcy_date,ST.3_year_base_employee_count

the node-sql-parser version: ^2.2.6
-the node version: 10.16.3

**Expected behavior**
No error. Columns starting with numbers are valid in Hive.

**Comment by taozhi8833998** [comment]
@damilaufer I will solve it today, I am working on it now.

**Comment by taozhi8833998** [comment]
@damilaufer it has been fixed.

**Comment by damilaufer** [comment]
Thank you.
I'll check it later today.
You rock.
