### ISSUE TITLE
Does not support ALTER TABLE ... ADD CONSTRAINT ... FOREIGN KEY

### ISSUE THREAD

**Issue by skorolev-tjc** [taozhi8833998/node-sql-parser#581]
Hello!
**Describe the bug**
Tried to parse the following SQL Query:
```
ALTER TABLE `CSEHistory` ADD CONSTRAINT `CSEHistoryDel` FOREIGN KEY ( `SystemUUID` ) REFERENCES `Systems` (`UUID`)
ON UPDATE RESTRICT ON
DELETE CASCADE
```
Recieved error: 
**_Expected "#", "--", "/*", "CHECK", or [ \\t\\n\\r] but "F" found._**

**Database Engine**
MySQL

**To Reproduce**
```
ALTER TABLE `CSEHistory` ADD CONSTRAINT `CSEHistoryDel` FOREIGN KEY ( `SystemUUID` ) REFERENCES `Systems` (`UUID`)
ON UPDATE RESTRICT ON
DELETE CASCADE
```
"node-sql-parser": "^3.1.0"
node --version v12.20.1

**Expected behavior**
Ast expected

**Screenshots**
No

**Additional context**
No

Thank you.

**Comment by taozhi8833998** [comment]
@skorolev-tjc got it.
