### ISSUE TITLE
Does not properly parse this simple(-ish) WHERE clause

### ISSUE THREAD

**Issue by stevendesu** [taozhi8833998/node-sql-parser#586]
I have the following query:

```sql
SELECT * FROM messages WHERE (year = 2012 AND month >= 9) OR (year = 2021 AND month <= 4) OR (year > 2012 AND year < 2021)
```

The goal is to find all messages between September 2012 and April 2021:
 * If the year is between 2012 and 2021 (e.g. "2015") then every month is a valid month
 * If the year is equal to 2012 then only September (9), October (10), November (11), and December (12) are valid months
 * If the year is equal to 2021 then only January (1), February (2), March (3), and April (4) are valid months

When I run the following code:

```js
const Parser = require("node-sql-parser");
const parser = new Parser();
const ast = parser.astify("SELECT * FROM messages WHERE (year = 2012 AND month >= 9) OR (year = 2021 AND month <= 4) OR (year > 2012 AND year < 2021)");
```

The following error is thrown:

```
UnhandledPromiseRejectionWarning: SyntaxError: Expected "!=", "#", "%", "&&", "*", "+", "-", "--", "/", "/*", ";", "<", "<=", "<>", "=", ">", ">=", "BETWEEN", "FOR", "GROUP", "HAVING", "IN", "IS", "LIKE", "LIMIT", "NOT", "ORDER", "UNION", "||", [ \t\n\r], or end of input but "O" found.
```

**Comment by stevendesu** [comment]
Related (as it seems like the issue stems from a lack of understanding parentheses):

I created an AST by hand and there were no parentheses in the output, causing the order of operations to be worng:

```js
ast.where = {
    type: "binary_expr",
    operator: "AND",
    left: {
        type: "binary_expr",
        operator: "OR",
        left: {
            type: "binary_expr",
            operator: "=",
            left: { type: "number", value: 1 },
            right: { type: "number", value: 1 },
        },
        right: {
            type: "binary_expr",
            operator: "=",
            left: { type: "number", value: 2 },
            right: { type: "number", value: 2 },
        }
    },
    right: {
        type: "binary_expr",
        operator: "OR",
        left: {
            type: "binary_expr",
            operator: "=",
            left: { type: "number", value: 3 },
            right: { type: "number", value: 3 },
        },
        right: {
            type: "binary_expr",
            operator: "=",
            left: { type: "number", value: 4 },
            right: { type: "number", value: 4 },
        }
    }
};

console.log(parser.sqlify(ast));
```

```sql
SELECT * FROM table WHERE 1 = 1 OR 2 = 2 AND 3 = 3 OR 4 = 4
```

In SQL the `AND` operator has precedence over the `OR` operator so this will compute:

```
(1 = 1) OR (2 = 2 AND 3 = 3) OR (4 = 4)
```

However the AST clearly shows that what was intended was:

```
(1 = 1 OR 2 = 2) AND (3 = 3 OR 4 = 4)
```

Proper support for parentheses and operator grouping is, unfortunately, a necessity for my use case. Unless there's a way to handle parentheses properly, I can't move forward with this library.

**Comment by stevendesu** [comment]
After further experimenting I've figured out two things:

1. WHERE clauses are properly parsed so long as they don't _**start**_ with a parenthesis
2. In my AST I can add `parentheses: true` to fix the grouping

Although I'd like to see a fix to the starting parentheses bug, I can at least work with this

**Comment by electric-al** [comment]
Just hit the same issue. This query fails to pass (Mysql dialect):

```
SELECT a,b,c FROM t WHERE (a = 1) AND (b >= 2 AND b < 3)
```

Error:
```
u [SyntaxError]: Expected "#", "%", "&&", "*", "+", "-", "--", "/", "/*", "||", or [ \t\n\r] but "A" found.
```

Whereas this query works:
```
SELECT a,b,c FROM t WHERE a = 1 AND (b >= 2 AND b < 3)
```
Despite being the same logically. Its a problem as the source of the SQL I am parsing inserts brackets around all predicates.

**Comment by taozhi8833998** [comment]
@electric-al @stevendesu it has been fixed, I will publish a new version later.

**Comment by electric-al** [comment]
Many thanks!
