### ISSUE TITLE
BigQuery Support

### ISSUE THREAD

**Issue by potatozerg** [taozhi8833998/node-sql-parser#587]
1. `SELECT (aaa + bbb / ccc) FROM xxx;` works. But `SELECT ((aaa + bbb) / ccc) FROM xxx;`  doesn't work.
2. Some functions for Bigquery are not working. Here are some queries that can't be parsed:
    1. `SELECT CURRENT_DATE('America/New_York')FROM table1;`
    2. `SELECT EXTRACT(DAY FROM DATE '2013-12-25') as the_day FROM table1;`
    3. `SELECT REGEXP_EXTRACT(CAST(date AS String), r"^[0-9]+") AS regexp FROM table1;`
I think there are a lot more functions that can't be parsed, if you need, I can get you a list of them later.

**Comment by taozhi8833998** [comment]
@potatozerg got it, I will try to support that later.

**Comment by potatozerg** [comment]
@taozhi8833998 
Here is a part of BigQuery functions in case you need it.
`[
    "CONCAT",
    "CURRENT_DATE",
    "CURRENT_DATETIME",
    "CURRENT_TIMESTAMP",
    "CURRENT_TIME",
    "DATE",
    "DATETIME",
    "TIMESTAMP",
    "TIME",
    "EXTRACT",
    "DATE_ADD",
    "DATE_SUB",
    "DATETIME_ADD",
    "DATETIME_SUB",
    "TIMESTAMP_ADD",
    "TIMESTAMP_SUB",
    "TIME_ADD",
    "TIME_SUB",
    "DATE_DIFF",
    "DATETIME_DIFF",
    "TIMESTAMP_DIFF",
    "TIME_DIFF",
    "DATE_TRUNC",
    "DATETIME_TRUNC",
    "TIMESTAMP_TRUNC",
    "TIME_TRUNC",
    "DATE_FROM_UNIX_DATE",
    "FORMAT_DATE",
    "FORMAT_DATETIME",
    "FORMAT_TIMESTAMP",
    "FORMAT_TIME",
    "PARSE_DATE",
    "PARSE_DATETIME",
    "PARSE_TIMESTAMP",
    "PARSE_TIME",
    "LAST_DAY",
    "UNIX_DATE",
    "TIMESTAMP_SECONDS",
    "TIMESTAMP_MILLIS",
    "TIMESTAMP_MICROS",
    "UNIX_SECONDS",
    "UNIX_MILLIS",
    "UNIX_MICROS",
    "ASCII",
    "ENDS_WITH",
    "INITCAP",
    "INSTR",
    "LEFT",
    "LENGTH",
    "LOWER",
    "LTRIM",
    "REGEXP_CONTAINS",
    "REGEXP_EXTRACT",
    "REPLACE",
    "RIGHT",
    "RTRIM",
    "STARTS_WITH",
    "STRPOS",
    "SUBSTR",
    "TRIM",
    "UPPER",
    "ABS",
    "SIGN",
    "IS_INF",
    "IS_NAN",
    "IEEE_DIVIDE",
    "RAND",
    "SQRT",
    "POWER",
    "EXP",
    "LN",
    "LOG",
    "LOG10",
    "GREATEST",
    "LEAST",
    "DIV",
    "SAFE_DIVIDE",
    "SAFE_MULTIPLY",
    "SAFE_NEGATE",
    "SAFE_ADD",
    "SAFE_SUBSTRACT",
    "MOD",
    "ROUND",
    "TRUNC",
    "CEIL",
    "FLOOR",
    "COS",
    "ACOS",
    "SIN",
    "ASIN",
    "TAN",
    "ATAN",
    "ATAN2",
    "CASE",
    "IF",
    "IFNULL",
    "NULLIF",
    "ROW_NUMBER",
    "LAG",
    "CAST",
    "SAFE_CAST"
]`

**Comment by taozhi8833998** [comment]
@potatozerg Thanks for the function list.

**Comment by potatozerg** [comment]
Added 4 more common functions: 
REGEXP_SUBSTR(value, regexp, [position], [occurrence])
LPAD(original_value, return_length, [pattern])
RPAD(original_value, return_length, [pattern])
FORMAT(format_string, value)

**Comment by potatozerg** [comment]
And do you think these two can be supported? With partition:
LAG(column1, [n_lags]) OVER(PARTITION BY column1 ORDER BY column2)
ROW_NUMBER() OVER(PARTITION BY  column1 ORDER BY column2)

**Comment by taozhi8833998** [comment]
@potatozerg try the `3.6.0` version.
