### ISSUE TITLE
Postgres Doesn't support Window functions

### ISSUE THREAD

**Issue by OTooleMichael** [taozhi8833998/node-sql-parser#589]
**Describe the bug**
Postgres Parsing doesn't support window functions

**Database Engine**
PostgreSQL.

**To Reproduce**
- node-sql-parse version 3.2.0
- Node v14.15.5
-the SQL that be parsed
```sql
     SELECT
            FIRST_VALUE(user_name IGNORE NULLS) OVER (
                PARTITION BY user_city
                ORDER BY created_at
            ) AS age_window
          FROM roster;
          
        SELECT
            LAG(user_name) OVER (
                PARTITION BY user_city
                ORDER BY created_at
            ) AS age_window
          FROM roster;
          
         SELECT
            SUM(user_age) OVER (
                PARTITION BY user_city
                ORDER BY created_at
                ROW BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
            ) AS age_window
          FROM roster
  ```

**Expected behaviour**
Happily parses Window functions etc

**Additional context**
I actually got this working and was going to make a PR but can't:

- Tests - Passing (+)
- Coverage - 100% (+)
- SQL added for new functions in a variety of contexts
- Functions added:
 -- `SUM_MAX_MIN_AVG` & `COUNT`: extended to have Frame clause
 -- `FIRST_VALUE LAST_VALUE` & `LAG & LEAD` & `ROW_NUMBER (etc)` 

** In particular I'd be happy to help out to add support for Redshift & the missing functionality of Postgres

**Comment by taozhi8833998** [comment]
@OTooleMichael You could fork this project, and push the commit to your repository, and create PR.

**Comment by taozhi8833998** [comment]
@OTooleMichael I will review your pull request, and then publish it today.
