### ISSUE TITLE
Add support for ignoring comments

### ISSUE THREAD

**Issue by Quinncuatro** [taozhi8833998/node-sql-parser#59]
Right now I need to use some regex magic to strip out comments (both one liners and block comments) before I push SQL through your parser.

The parser should be able to just ignore comments.

**Comment by taozhi8833998** [comment]
ok, I will add it later

**Comment by taozhi8833998** [comment]
the feature has been supported in 5f770a9c5fc4f64581727efd989d20ff3f4d637b, I will publish new version later.
