### ISSUE TITLE
MySQL SyntaxError for "SHOW GRANTS"

### ISSUE THREAD

**Issue by Badestrand** [taozhi8833998/node-sql-parser#608]
First, thank you for this great project, I love it!

**Describe the bug**
Parser throws a syntax error for the MySQL query `SHOW GRANTS`.

**Database Engine**
MySQL

**To Reproduce**
SQL: `SHOW GRANTS` or `SHOW GRANTS FOR user@host`

node-sql-parser version 3.3.0

node version 14.15.0

**Expected behavior**
Parse query.

**Comment by Badestrand** [comment]
Oh sorry, I didn't see in the description that only some commands are supported

**Comment by taozhi8833998** [comment]
@Badestrand I can add it if it's necessary for u.

**Comment by Badestrand** [comment]
@taozhi8833998 yes, that would be great, thank you!
