### ISSUE TITLE
Postgres fails to parse column using parentheses and cast shorthand

### ISSUE THREAD

**Issue by hle-skillz** [taozhi8833998/node-sql-parser#612]
**Describe the bug**
Combining a parentheses and cast shorthand fails to parse, but individually parse fine.

**Database Engine**
Postgres

**To Reproduce**
[node-sql-parser 3.3.0 from UMD](https://unpkg.com/browse/node-sql-parser@3.3.0/umd/)

SQL
* Pass, standalone parens:
```sql
select
(salary) as comp
from employee
```
* Pass, standalone cast shorthand
```sql
select
salary::bigint as comp
from employee
```
* Pass, parens with expr
```sql
select
(salary + bonus) as total_comp
from employee
```
* Pass, cast longhand:
```sql
select
cast(salary + bonus as bigint) as total_comp
from employee
```
* Fail, parens + cast shorthand:
```sql
select
(salary + bonus)::bigint as comp
from employee
```
error: 
```
Expected "!=", "#", "%", "&&", "'", "*", "+", ",", "-", "--", "/", "/*", ";", "<", "<=", "<>", "=", ">", ">=", "AS", "BETWEEN", "FOR", "FROM", "GROUP", "HAVING", "IN", "IS", "LIKE", "LIMIT", "NOT", "ORDER", "UNION", "WHERE", "\"", "`", "||", [ \t\n\r], [A-Za-z_], or end of input but ":" found.
```
* Fail:

**Expected behavior**
Parens around expression should not cause failure of shorthand cast (`::bigint`)

**Comment by taozhi8833998** [comment]
@hle-skillz it has been supported.

**Comment by HenonoaH** [comment]
@taozhi8833998 Still I'm getting this issue any idea? I'm using version 3.6.0 I'm having this line in a query `round((event_attendees_count::numeric / event_registrants_count::numeric) * 100::numeric,1) as "attendance_rate"` and getting error `Expected "!=", "#", "%", ")", "*", "+", ",", "-", "--", ".", "/", "/*", "<", "<=", "<>", "=", ">", ">=", "BETWEEN", "IN", "IS", "LIKE", "NOT", "REGEXP", "RLIKE", [ \t\n\r], [0-9], or [eE] but ":" found.`

**Comment by taozhi8833998** [comment]
> @taozhi8833998 Still I'm getting this issue any idea? I'm using version 3.6.0 I'm having this line in a query `round((event_attendees_count::numeric / event_registrants_count::numeric) * 100::numeric,1) as "attendance_rate"` and getting error `Expected "!=", "#", "%", ")", "*", "+", ",", "-", "--", ".", "/", "/*", "<", "<=", "<>", "=", ">", ">=", "BETWEEN", "IN", "IS", "LIKE", "NOT", "REGEXP", "RLIKE", [ \t\n\r], [0-9], or [eE] but ":" found.`

@HenonoaH  If the SQL is PostgreSQL syntax, please use the `database` option to specify it, MySQL is the default database.

```javascript
const { Parser } = require('node-sql-parser')
const parser = new Parser()
const ast = parser.astify('select round((event_attendees_count::numeric / event_registrants_count::numeric) * 100::numeric,1) as "attendance_rate" from abc',  { database: 'postgresql' } )
```

**Comment by HenonoaH** [comment]
@taozhi8833998 Thanks. Got it working.
