### ISSUE TITLE
Postgres fails on literals in where clauses

### ISSUE THREAD

**Issue by hle-skillz** [taozhi8833998/node-sql-parser#613]
**Describe the bug**
Using a standalone constant placeholder in a WHERE expression does not parse.  Similar to leading commas, this pattern is used frequently during debugging to allow disabling groups without commenting.

**Database Engine**
Postgres

**To Reproduce**
[node-sql-parser 3.3.0 from UMD](https://unpkg.com/browse/node-sql-parser@3.3.0/umd/)

SQL
* Pass, AND:
```sql
select
age
from employee
where
age < 100
and
age > 10

```
* Pass, constant-only
```sql
select
age
from employee
where
true
```
* Fail, AND + constant:
```sql
select
age
from employee
where
true
and age > 10```
error: 
```
```
Expected "#", "%", "&&", "*", "+", "-", "--", "/", "/*", "||", or [ \t\n\r] but "a" found.```
{
    "start": {
        "offset": 36,
        "line": 6,
        "column": 1
    },
    "end": {
        "offset": 37,
        "line": 6,
        "column": 2
    }
}
```

**Expected behavior**
Constants should work in logical expressions.

**Comment by taozhi8833998** [comment]
@hle-skillz it has been fixed
