### ISSUE TITLE
Support "a REGEXP b", "a REGEXP BINARY b" (MariaDB) syntax

### ISSUE THREAD

**Issue by pixelspark** [taozhi8833998/node-sql-parser#634]
**Describe the bug**

Parsing `SELECT ('a' REGEXP 'A') AS x` fails with ` SyntaxError: Expected "!=", "#", "%", "&&", ")", "*", "+", ",", "-", "--", "/", "/*", "<", "<=", "<>", "=", ">", ">=", "BETWEEN", "IN", "IS", "LIKE", "NOT", "||", or [ \t\n\r] but "R" found.` on 3.4.0.

**Database Engine**
MariaDB (MySQL has the same syntax iirc)

**To Reproduce**
See above. NodeJS=v12

**Expected behavior**
I expect this to parse and lead to an AST similar to "a LIKE b".

**Screenshots**
n/a

**Additional context**
Other than this the parser's been working great in our app for quite a while, thank you!

**Comment by taozhi8833998** [comment]
supported in the `3.5.0` version, try it.

**Comment by pixelspark** [comment]
Awesome, thanks a lot!
