### ISSUE TITLE
Parsing a valid query returns error

### ISSUE THREAD

**Issue by kt65** [taozhi8833998/node-sql-parser#636]
**Describe the bug**
Query "SELECT * FROM `product` WHERE (name LIKE "dummy" AND sku = "dummy") LIMIT 0, 1000000000"

**Database Engine**
MySQL

**To Reproduce**
-Parse this query 'SELECT * FROM `product` WHERE (name LIKE "dummy" AND sku = "dummy") LIMIT 0, 1000000000'
```javascript
parser.astify('SELECT * FROM `product` WHERE (name LIKE "dummy" AND sku = "dummy") LIMIT 0, 1000000000');
```

**Expected result**
Return the array of tokens

**Actual result**
That code returns an SyntaxError
"SyntaxError: Expected "!=", "#", "%", ")", "*", "+", ",", "-", "--", "/", "/*", "<", "<=", "<>", "=", ">", ">=", "BETWEEN", "IN", "IS", "LIKE", "NOT", or [ \t\n\r] but "A" found"

That query should be treated as a valid query

Thanks

**Comment by taozhi8833998** [comment]
@kt65 try `3.5.0` version.
