### ISSUE TITLE
Hex values are not supported

### ISSUE THREAD

**Issue by idangozlan** [taozhi8833998/node-sql-parser#644]
**Describe the bug**
When trying to parse insert query with hexed values, the module is crashing.

**Database Engine**
MySQL

**To Reproduce**
```
const { Parser } = require('node-sql-parser/build/mysql');

const parser = new Parser();
// opt is optional
const opt = {
  database: 'MySQL',
};

const columnList = parser.columnList(`INSERT INTO \`t\` 
(\`a\`) VALUES
 (X'ax')`, opt); // <---------------- X'something'
```

**Expected behavior**
to parse it as a buffer

**Comment by taozhi8833998** [comment]
@idangozlan it has been supported, I will publish a new version this week.

**Comment by idangozlan** [comment]
Nice, thanks!
