### ISSUE TITLE
FROM clause | Misinterpreted non-aliased table 

### ISSUE THREAD

**Issue by chriswijaya** [taozhi8833998/node-sql-parser#650]
Given query input below:
```sql
select
  person.first_name,
  department.dept_name
from
  person 
  left join department on person.dept_id = department.dept_id
```

AST object product of `astify` function interprets `left` part of the `left join` term as the alias name, the output generated is:
`... person AS LEFT INNER JOIN person ...`

My code:
```javascript
const { Parser } = require( 'node-sql-parser' );
const parser = new Parser()
const pgOpt = { database: 'PostgresQL' }
const bqOpt = { database: 'BigQuery' }

query = `
select
  person.first_name,
  department.dept_name
from
  person 
  left join department on person.dept_id = department.dept_id`
  
const ast = parser.astify( query, pgOpt );
const sql = parser.sqlify( ast, bqOpt );
console.log( sql );
```

**Comment by taozhi8833998** [comment]
@chriswijaya fixed, I will publish a new version this week.

**Comment by yangge24926** [comment]
I have upgraded to the latest version 3.6.1, but this problem still occurs. Have you thought about solving this problem in the near future?

`

let kSql = `
SELECT "Join1"."user_nickname",
       "Join1"."anonymous_flag1",
       "ccc"."reply_count" AS "reply_count2"
FROM   (SELECT "aaa"."user_nickname",
               "bbb"."anonymous_flag" AS "anonymous_flag1"
        FROM   "aaa"
               LEFT JOIN "bbb"
                      ON "aaa"."product_id" = "bbb"."product_id") AS "Join1"
       LEFT JOIN "ccc"
              ON "Join1"."user_nickname" = "ccc"."product_id"
`

console.log(kParser.astify(kSql, {database: 'PostgresQL'}))
`
