### ISSUE TITLE
Slow astify() for postgresSql

### ISSUE THREAD

**Issue by thfai2000** [taozhi8833998/node-sql-parser#658]
Hi

I've a project which is something like ORM. It has to support `sqlite`,` mysql`, `postgres`.
Thank `node-sql-parser`. It is great! I used it for parsing the SQL statement to detect some column names and reconstructing a new sql statement before execution. 
But it come to me a big issue that is the speed performance (it is important to an ORM).
I found that the Parser for `postgresql` is very slow comparing to Mysql Parser, almost ***10x slower***

Here is an example. Parsing same (almost the same) sql:
```javascript
const {Parser: PgParser} = require('node-sql-parser/build/postgresql')
const {Parser: MysqlParser} = require('node-sql-parser/build/mysql')

let mySqlQuery = "SELECT coalesce(JSON_ARRAYAGG(JSON_OBJECT('id', id,'productId', productId,'colorId', colorId,'type', type)), JSON_ARRAY()) FROM abc"

console.time('mysql')
new MysqlParser().astify(mySqlQuery)
console.timeEnd('mysql') //mysql: 29.8ms

let pgQuery = `SELECT coalesce(JSON_AGG(JSON_BUILD_OBJECT('id', id,'productId', productId,'colorId', colorId,'type', "type")), '[]'::json) FROM abc`

console.time('pg')
new PgParser().astify(pgQuery)
console.timeEnd('pg')  // pg: 215.493ms
```

mysql: 29.8ms
pg: 215.493ms

approx. ***10x slower***.

I found that once the query included any function call, it become much slower.
Is there any advice?

If some parts are eliminated (like remove some columns), the time is reduced half
```javascript
let pgQuery 2= `SELECT coalesce(JSON_AGG(JSON_BUILD_OBJECT('id', id)), '[]'::json) FROM abc`

console.time('pg')
new PgParser().astify(pgQuery2)
console.timeEnd('pg')   // pg 98.282ms
```

**Comment by taozhi8833998** [comment]
@thfai2000 I will check it out asap.

**Comment by thfai2000** [comment]
> @thfai2000 I will check it out asap.

Thanks @taozhi8833998 
Just let you know this issue is not urgent to me. I can use another approach to tackle this. 😄

**Comment by taozhi8833998** [comment]
@thfai2000 ok, It may take some time to solve it.
