### ISSUE TITLE
MySQL Parser cannot read datatype enum

### ISSUE THREAD

**Issue by myyrakle** [taozhi8833998/node-sql-parser#682]
**Describe the bug**
It seems that the current MySQL parser does not support enum types. Is it possible to add a function for this?

**Database Engine**
MySQL

**To Reproduce**
-the SQL that be parsed
```
CREATE TABLE `action` (
  `id` int NOT NULL AUTO_INCREMENT,
  `platform` enum('IOS','ANDROID','PC_WEB','MOBILE_WEB','ETC') NOT NULL DEFAULT 'PC_WEB',
  `date` datetime NOT NULL,
  PRIMARY KEY (`id`)
);
```
-the node-sql-parser version: 3.6.0
-the node version: v14.17.0

**Expected behavior**
Since the enum type is a valid mysql type, I think it should be parsed normally.

**Screenshots**
![image](https://user-images.githubusercontent.com/16988115/126038274-16b9f691-5345-4b05-a72c-4ab11b658fef.png)

**Additional context**

**Comment by taozhi8833998** [comment]
@myyrakle try the `3.6.1` version
