### ISSUE TITLE
UNSUPORT MYSQL DATETIME(6),TIME(6),TIMESTAMP(6)

### ISSUE THREAD

**Issue by fuzi1996** [taozhi8833998/node-sql-parser#683]
### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ecstatic-framework-k7pll?file=/index.html)

MySql Doc:[11.7 Data Type Storage Requirements](https://dev.mysql.com/doc/refman/8.0/en/storage-requirements.html)

**Database Engine**
MySQL

**To Reproduce**
```sql
CREATE TABLE `test`  ( 
`date` date NULL DEFAULT NULL, 
`datetime` datetime(6) NULL DEFAULT NULL 
);

CREATE TABLE `test`  ( 
`date` date NULL DEFAULT NULL, 
`datetime` datetime NULL DEFAULT NULL, 
`time` time(6) NULL DEFAULT NULL 
);

CREATE TABLE `test`.`Untitled`  ( 
`date` date NULL DEFAULT NULL, 
`datetime` datetime NULL DEFAULT NULL, 
`time` time NULL DEFAULT NULL, 
`timestamp` timestamp(6) NULL DEFAULT NULL 
);
```

**Expected behavior**
no error,astify success

**Comment by taozhi8833998** [comment]
@fuzi1996 it has been fixed!

**Comment by taozhi8833998** [comment]
@fuzi1996 try the `3.6.0` version
