### ISSUE TITLE
MySQL: Cannot parse CREATE TABLE statement with BOOLEAN type

### ISSUE THREAD

**Issue by tbantle22** [taozhi8833998/node-sql-parser#696]
**Describe the bug**

**Database Engine**
MySQL

**To Reproduce**
-the SQL that be parsed
```sql
CREATE TABLE dev_company (
company_id INT,
company_name VARCHAR(255),
is_buildable BOOLEAN,
PRIMARY KEY(company_id)
);
```
-the node-sql-parser version
3.6.0
-the node version
v12.19.0

**Expected behavior**
Expect no error `SyntaxError: Expected "#", "--", "->", "->>", ".", "/*", "BIGINT", "BIT", "CHAR", "DATE", "DATETIME", "DECIMAL", "DOUBLE", "FLOAT", "INT", "INTEGER", "JSON", "LONGTEXT", "MEDIUMTEXT", "NUMERIC", "SMALLINT", "TEXT", "TIME", "TIMESTAMP", "TINYINT", "TINYTEXT", "VARCHAR", or [ \t\n\r] but "B" found.`

**Screenshots**

**Additional context**

**Comment by taozhi8833998** [comment]
@tbantle22 it has been supported, I will publish a new version tomorrow.

**Comment by tbantle22** [comment]
Thank you!
