### ISSUE TITLE
PostgresQL parsing error

### ISSUE THREAD

**Issue by yangge24926** [taozhi8833998/node-sql-parser#697]
let kSql = `
SELECT "Join1"."user_nickname",
       "Join1"."anonymous_flag1",
       "ccc"."reply_count" AS "reply_count2"
FROM   (SELECT "aaa"."user_nickname",
               "bbb"."anonymous_flag" AS "anonymous_flag1"
        FROM   "aaa"
               LEFT JOIN "bbb"
                      ON "aaa"."product_id" = "bbb"."product_id") AS "Join1"
       LEFT JOIN "ccc"
              ON "Join1"."user_nickname" = "ccc"."product_id"
`

console.log(kParser.astify(kSql, {database: 'PostgresQL'}))

![image](https://user-images.githubusercontent.com/40169135/128317330-5542a7e0-fce7-46d4-b4fc-2be8210a9800.png)

我看有人报过这个bug，看记录已经合并到master了，但是我已经升级到最新的3.6.1版本，这个bug还是存在。

**Comment by yangge24926** [comment]
因为我现在做的是一个树和sql互转的功能，所以我对转换后的AST结构进行了覆盖修复，不过仍是期待你能修复这个问题，毕竟这种覆盖的代码不好看。

**Comment by taozhi8833998** [comment]
@yangge24926 `node-sql-parser` works well with the SQL you provided as show in [link](https://runkit.com/taozhi8833998/5df6fe8f21d6b8001be36cb7)

**Comment by yangge24926** [comment]
What's the version of your app? @taozhi8833998

**Comment by taozhi8833998** [comment]
> What's the version of your app? @taozhi8833998

it shows in the above link, the `node-sql-parser` module with version 3.6.1

![image](https://user-images.githubusercontent.com/7252180/128469802-2420d978-c307-481d-8d85-272a57e88200.png)

**Comment by yangge24926** [comment]
![image](https://user-images.githubusercontent.com/40169135/128470111-5c869b18-c865-4d94-9930-e7ad453f5523.png)

![image](https://user-images.githubusercontent.com/40169135/128470143-c0158dac-0ddd-47f9-83aa-bcf316c16748.png)

I tried to reinstall it, very strange problem, probably problem is in my environment, thank you for your patience

**Comment by taozhi8833998** [comment]
> ![image](https://user-images.githubusercontent.com/40169135/128470111-5c869b18-c865-4d94-9930-e7ad453f5523.png)
> 
> ![image](https://user-images.githubusercontent.com/40169135/128470143-c0158dac-0ddd-47f9-83aa-bcf316c16748.png)
> 
> I tried to reinstall it, very strange problem, probably problem is in my environment, thank you for your patience

remove the node_modules folder, and reinstall

**Comment by yangge24926** [comment]
In progress, thank you

**Comment by yangge24926** [comment]
He is very good. This is my environmental problem. Thank you for your help. @taozhi8833998
