### ISSUE TITLE
Problem when parsing sql data with tab character

### ISSUE THREAD

**Issue by pidgeonman** [taozhi8833998/node-sql-parser#70]
I'm trying to astify some SQL that contains strings (raw HTML code) with tabs characters, but it's failing with the error:

`'Expected "\'", "\\\\\'", "\\\\/", "\\\\\\"", "\\\\\\\\", "\\\\b", "\\\\f", "\\\\n", "\\\\r", "\\\\t", "\\\\u", or [^\'\\\\\\0-\\x1F\\x7F] but "\\t" found.'`

I can't share the raw SQL I'm using because of privacy, but it's something like:

`INSERT INTO `some_table` (`ID`, `field_1`, `field_2`) VALUES (2124,'2017-02-08 15:33:17','2017-02-08 15:33:17','<strong>These are some HTML contents to be displayed on a page</strong>\n\nResources:\nThe following is a tab character, which will make astify fail:	');`

AFAIK, there shouldn't be any problems with raw tabs in SQL.

**Comment by pidgeonman** [comment]
More info:

Using the latest version. 

Some stack trace:

`{ SyntaxError: Expected "'", "\\'", "\\/", "\\\"", "\\\\", "\\b", "\\f", "\\n", "\\r", "\\t", "\\u", or [^'\\\0-\x1F\x7F] but "\t" found.
    at peg$buildStructuredError (/my/path/node_modules/node-sql-parser/build/pegjs-parser.js:1203:12)
    at peg$parse (/my/path/node_modules/node-sql-parser/build/pegjs-parser.js:13185:11)
    at Parser.parse (/my/path/node_modules/node-sql-parser/lib/parser.js:17:12)
    at Parser.astify (/my/path/node_modules/node-sql-parser/lib/parser.js:8:26)
...
`

**Comment by taozhi8833998** [comment]
The SQL you pasted has been parsed successfully in `1.4.1` version,  you could show me the real SQL

```javascript
const { Parser } = require('node-sql-parser');
const parser = new Parser();

const ast = parser.astify(`INSERT INTO some_table (ID, field_1, field_2) VALUES (2124,'2017-02-08 15:33:17','2017-02-08 15:33:17','<strong>These are some HTML contents to be displayed on a page</strong>\n\nResources:\nThe following is a tab character\t, which will make astify fail:	');`)

console.log(JSON.stringify(ast, null, 2))
const sql = parser.sqlify(ast)

console.log('sql==', JSON.stringify(sql))
```

**Comment by taozhi8833998** [comment]
If it stills there, you could show me the real SQL by removing the private data, and reopen the issue.
