### ISSUE TITLE
UNIQUE constraint when written alongside column definition in create query is giving an error upon parsing.

### ISSUE THREAD

**Issue by abhinav5481** [taozhi8833998/node-sql-parser#703]
**Describe the bug**
UNIQUE constraint when written alongside column definition is giving an error.

**Database Engine**
MySQL

**Expected behaviour**
The query with UNIQUE keyword (defined alongside column definition) should have been parsed successfully & the "unique_or_primary" field of the respective column should have "unique" instead of "null" in the AST.

**Screenshots**
<img width="940" alt="Unique_error" src="https://user-images.githubusercontent.com/60434542/128837205-001ae461-6428-4db7-825e-a47844be213f.png">

**Additional context**
NA

**Comment by taozhi8833998** [comment]
@abhinav5481 please show the SQL in text, while not in a screenshot.

**Comment by abhinav5481** [comment]
create table CourseTable( tutorial_id INT UNIQUE, tutorial_title VARCHAR(100) NOT NULL, tutorial_author VARCHAR(40) NOT NULL, submission_date DATE);

**Comment by taozhi8833998** [comment]
@abhinav5481 try `3.6.3` version
