### ISSUE TITLE
CHECK constraint when written alongside column definition is showing error upon parsing.

### ISSUE THREAD

**Issue by abhinav5481** [taozhi8833998/node-sql-parser#704]
**Describe the bug**
CHECK constraint when written alongside column definition is showing error upon parsing.

**Database Engine**
MySQL

**To Reproduce**
-the SQL that be parsed

CREATE TABLE parts (
    part_no VARCHAR(18) PRIMARY KEY,
    description VARCHAR(40),
    cost DECIMAL(10,2 ) NOT NULL CHECK (cost >= 0),
    price DECIMAL(10,2) NOT NULL CHECK (price >= 0)
);

-the node-sql-parser version
6.2 (latest - updated today)

**Expected behavior**
The query should have been parsed with constraint CHECK

**Screenshots**
<img width="937" alt="check_cmd" src="https://user-images.githubusercontent.com/60434542/128838366-d32bb26b-43d3-45d3-bdcf-158ac1afbeb3.png">

**Additional context**
NA

**Comment by taozhi8833998** [comment]
@abhinav5481 new version `3.6.3`  has been published, give it a shot, thank you.
