### ISSUE TITLE
Issue with `then` and `else` in INSERT.

### ISSUE THREAD

**Issue by Quinncuatro** [taozhi8833998/node-sql-parser#71]
```
select database() as dbname,col_a,col_b,col_c
then (select id from tbl_name.tbl_id where thing = stuff)
else ifnull(select id from tbl_name_2.tbl_id where thing = stuff)
from table_name
order by col_b;
```

outputs

```
SyntaxError: Expected "#", "--", "/*", ":=", "=", "INTO", or [ \t\n\r] but "t" found.
    at peg$buildStructuredError (/usr/src/code/node_modules/node-sql-parser/build/pegjs-parser.js:1333:12)
    at peg$parse (/usr/src/code/node_modules/node-sql-parser/build/pegjs-parser.js:14278:11)
    at Parser.parse (/usr/src/code/node_modules/node-sql-parser/lib/parser.js:17:12)
    at Parser.astify (/usr/src/code/node_modules/node-sql-parser/lib/parser.js:8:26)
    at astThatStuff (/usr/src/code/arrayChecker.js:88:16)
    at sanitizeSQL (/usr/src/code/arrayChecker.js:84:3)
    at read (/usr/src/code/arrayChecker.js:52:5)
```

**Comment by taozhi8833998** [comment]
ok, I will check it out

**Comment by taozhi8833998** [comment]
@Quinncuatro please show me the real SQL by removing the secret data. The SQL you pasted is invalid, and it's select not insert.

**Comment by Quinncuatro** [comment]
You're right that the SQL is invalid, but I can't share the original SQL. Company IP and all that.

**Comment by taozhi8833998** [comment]
> You're right that the SQL is invalid, but I can't share the original SQL. Company IP and all that.

you could replace the secret data with ? or empty, and the column name could be replaced, but the structure of SQL should be reserved

**Comment by Quinncuatro** [comment]
Trying to get my version up to speed with the changes you've made over the last few months. I can try to get you something if this is still not working.

**Comment by taozhi8833998** [comment]
is this MariaDB SQL syntax ??

**Comment by taozhi8833998** [comment]
Sorry for the delay, I hope that you could help me to understand this issue more clearly, and it will be solved as soon as possible. BTW, nice head portrait.

**Comment by Quinncuatro** [comment]
It's MariaDB still, yeah! When I have something to share, I'll post it here.

**Comment by taozhi8833998** [comment]
ok, I will be notified when u do that, keep waiting
