### ISSUE TITLE
MySQL: Distinct inside group_concat raises a syntax error

### ISSUE THREAD

**Issue by franciscojuane** [taozhi8833998/node-sql-parser#713]
**Describe the bug**
MySQL query can't be parsed.

**Database Engine**
MySQL (for some reason it works ok with PostgreSQL)

**To Reproduce**
-the SQL that be parsed:

1. select group_concat(distinct(asd)) as 'abc'
2. select group_concat(distinct asd) as 'abc'

-the node-sql-parser version:
3.6.4
-the node version
14.17.3

The first query fails with "SyntaxError: Expected [A-Za-z0-9_:] or [A-Za-z0-9_] but "(" found.".
The second query fails with "SyntaxError: Expected [A-Za-z0-9_:] or [A-Za-z0-9_] but " " found.".

**Additional context**
Just trying to parse a query to get the columns list.

**Comment by taozhi8833998** [comment]
@franciscojuane try `3.6.5`

**Comment by franciscojuane** [comment]
@taozhi8833998 Thanks! 😄 I tried 3.6.5 and it works, but now I'm getting another error when trying to parse GROUP_CONCAT(DISTINCT(IF(...)))
"SyntaxError: Expected "#", ")", "--", "->", "->>", ".", "/*", [ \t\n\r], [A-Za-z0-9_:], or [A-Za-z0-9_] but "(" found.""

**Comment by taozhi8833998** [comment]
@franciscojuane ok, reopen this issue.

**Comment by taozhi8833998** [comment]
@franciscojuane try the new version `3.6.6`

**Comment by franciscojuane** [comment]
@taozhi8833998 thanks! it works! but now I found another bug! using order by inside group concat gives another error

"group_concat(distinct(organization.name) order by organization.name) as column1"

"Expected "!=", "#-", "#>", "#>>", "%", "&&", ")", … "LIKE", "NOT", "||", or [ \t\n\r] but "o" found."

**Comment by taozhi8833998** [comment]
> @taozhi8833998 thanks! it works! but now I found another bug! using order by inside group concat gives another error
> 
> "group_concat(distinct(organization.name) order by organization.name) as column1"
> 
> "Expected "!=", "#-", "#>", "#>>", "%", "&&", ")", … "LIKE", "NOT", "||", or [ \t\n\r] but "o" found."

fixed in the next version
