### ISSUE TITLE
Link to install from browser not working

### ISSUE THREAD

**Issue by nkusibojoski** [taozhi8833998/node-sql-parser#726]
**Describe the bug**
I can't load the library in the browser. I am using this link: https://unpkg.com/node-sql-parser/umd/index.umd.js
It was running few hours ago and I am using it this way for about 1 year.

**Comment by nkusibojoski** [comment]
It seems that is working with this url https://unpkg.com/node-sql-parser@3.6.0/umd/index.umd.js.

**Comment by taozhi8833998** [comment]
@nkusibojoski Sorry for that, it's working now, refresh it.
