### ISSUE TITLE
Duplicate type definitions

### ISSUE THREAD

**Issue by HoldYourWaffle** [taozhi8833998/node-sql-parser#73]
Related to #9.

You contributed the type definitions for this package to [DefinitelyTyped yourself](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/32555), but they are also included in the package itself. Do you have a specific reason for this? I don't see a reason why a package with included typings needs to have an additional DefinitelyTyped package.

**Comment by taozhi8833998** [comment]
Sorry for anonying！ I have deleted `index.d.ts` in my project

**Comment by HoldYourWaffle** [comment]
> Sorry for anonying !

Oh it's not annoying or anything, just a little weird. since it makes the DefinitelyTyped package redundant.

> I have deleted index.d.ts in my project

Wouldn't it be better to keep the file here and remove the DefinitelyTyped variant? That way you don't have to maintain "2 repositories", can update the typings at any time without going through the approval procedure at DefinitelyTyped and users won't have to install an extra package. I'm pretty sure that's the recommended approach throughout the community.
If you want I could help with deprecating/removing the DefinitelyTyped package.
