### ISSUE TITLE
MYSQL: Not able to parse some statements

### ISSUE THREAD

**Issue by tbantle22** [taozhi8833998/node-sql-parser#736]
**Describe the bug**
I've been testing some common MySQL queries and have found a few that are returning syntax errors

**Database Engine**
MySQL

**To Reproduce**
-the SQL that be parsed

The failing queries and their errors: 
- [x] query: `alter table places drop primary key`
   error: SyntaxError: Expected "#", ",", "--", "->", "->>", ".", "/*", ";", or [ \t\n\r] but "k" found. 
- [x] query: `create index city_idx on places(city)`
   error: SyntaxError: Expected "#", "--", "/*", ":=", "=", "DATABASE", "SCHEME", "TABLE", "TEMPORARY", or [ \t\n\r] but "i" found. 
- [x] query: `create table places2 as select * from places;`
   error: "select" is a reserved word, can not as alias clause 
- [x] query: `create table places2 select * from places;  `
   error: SyntaxError: Expected [A-Za-z0-9_] but " " found. 
- [x] query: `alter table places change city city2 varchar(255)`
error: SyntaxError: Expected "#", ",", "--", "/*", "ADD", "ALGORITHM", "DROP", "FULL", "INNER", "JOIN", "LEFT", "LOCK", "NOCHECK", "RENAME", "RIGHT", "WITH", or [ \t\n\r] but "c" found. 

-the node-sql-parser version 3.6.10
-the node version 16.6.2

**Expected behavior**
Should not return syntax error

**Comment by taozhi8833998** [comment]
@tbantle22 fixed the first, the third, the fourth one.

**Comment by tbantle22** [comment]
Thank you!

**Comment by taozhi8833998** [comment]
@tbantle22 try the new `3.7.0` version.

**Comment by tbantle22** [comment]
> @tbantle22 try the new `3.7.0` version.

Works, thanks!
