### ISSUE TITLE
PostgreSQL: `percentile_cont` not recognized

### ISSUE THREAD

**Issue by joffreyvillard** [taozhi8833998/node-sql-parser#748]
**Describe the bug**
The query below (using the `percentile_cont` function) fails while being valid:

```
select percentile_cont(0.25) within group (order by a asc) as p25
from (values (0),(0),(1),(2),(3),(4)) as t(a)
```

Error

```
SyntaxError: Expected "--", "/*", "BY", or [ \t\n\r] but "(" found.
```

**Database Engine**
PostgreSQL

**To Reproduce**
-the SQL that be parsed: see above
-the node-sql-parser version: 3.6.10
-the node version: 14.15.5

**Expected behavior**
 No error, and the appropriate properties being filled up in the AST.

**Comment by taozhi8833998** [comment]
@joffreyvillard try the `3.8.0` version, it fixes the other issues related to pg, which was created by you.

**Comment by joffreyvillard** [comment]
It's all good, thanks again!
