### ISSUE TITLE
[MySQL]: Parsing `SHOW TABLES` query results in error

### ISSUE THREAD

**Issue by tbantle22** [taozhi8833998/node-sql-parser#778]
**Describe the bug**
Should handle all `SHOW TABLES` variations [here](https://dev.mysql.com/doc/refman/8.0/en/show-tables.html)

**Database Engine**
which database engine does your SQL running on? such as MySQL, PostgreSQL.
MySQL

**To Reproduce**
-the SQL that be parsed
-the node-sql-parser version ^3.8.4
-the node version

```
query: SHOW TABLES;

error: SyntaxError: Expected "#", "--", "/*", ":=", "=", "BINARY", "BINLOG", "CHARACTER", "COLLATION", "GRANTS", "MASTER", or [ \t\n\r] but "T" found.
```

**Comment by tbantle22** [comment]
@taozhi8833998 I'm getting this error for `SHOW TABLES` again with `^4.3.0`. Not sure when it started

**Comment by taozhi8833998** [comment]
> @taozhi8833998 I'm getting this error for `SHOW TABLES` again with `^4.3.0`. Not sure when it started

@tbantle22 Could you show me the codes? The corresponding test case is passed.

**Comment by tbantle22** [comment]
> > @taozhi8833998 I'm getting this error for `SHOW TABLES` again with `^4.3.0`. Not sure when it started
> 
> @tbantle22 Could you show me the codes? The corresponding test case is passed.

This is the error I'm getting:

```
query: show tables

error: SyntaxError: Expected "#", "--", "/*", ":=", "=", "BINARY", "BINLOG", "CHARACTER", "COLLATION", "GRANTS", "MASTER", or [ \t\n\r] but "t" found. 
```

**Comment by tbantle22** [comment]
This getting this error for MySQL in `4.6.5`.

**Comment by TonyGravagno** [comment]
Node 20.3.0  
NSP 4.6.6  
MariaDb 10.4.10

I've never used this code before. I just loaded (current npmjs) as dependency for mysql-to-zod which I forked with (so far) no changes. The full `[SyntaxError]` is below. Preceding that in my execution is a huge dump that may come from the local project or NSP, I dunno, but it ends in the following, which I hope might be helpful in finding the error:  
`,global&&global.window&&(global.window.NodeSQLParser={Parser:lt,util:n})}]));`  

If we know how to dump the text that is being parsed then we should be able to help identify the text that is causing the parse to abort. I'll rebuild with some debug lines if that will help. Just tell me where. 😄  


Error:
> s [SyntaxError]: Expected "#", ")", ",", "--", "/*", "AS", "AUTO_INCREMENT", "CHARACTER", "CHECK", "COLLATE", "COLUMN_FORMAT", "COMMENT", "CONSTRAINT", "DEFAULT", "GENERATED", "KEY", "NOT NULL", "NULL", "ON", "PRIMARY", "REFERENCES", "STORAGE", "UNIQUE", or [ \t\n\r] but "(" found.
>     at Ro (D:\Development\Projects\MySQL\MySqlToZod\node_modules\node-sql-parser\index.js:1:368364)
>     at Object.parse [as mysql] (D:\Development\Projects\MySQL\MySqlToZod\node_modules\node-sql-parser\index.js:1:512679)    at r.value (D:\Development\Projects\MySQL\MySqlToZod\node_modules\node-sql-parser\index.js:1:1250439)
>     at r.value (D:\Development\Projects\MySQL\MySqlToZod\node_modules\node-sql-parser\index.js:1:1249996)
>     at createSchemaFile (D:\Development\Projects\MySQL\MySqlToZod\dist\createSchemaFile.js:25:24)
>     at main (D:\Development\Projects\MySQL\MySqlToZod\dist\main.js:33:59)
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
>   expected: [
>     {
>       type: 'class',
>       parts: [ ' ', '\t', '\n', '\r' ],
>       inverted: false,
>       ignoreCase: false
>     },
>     { type: 'literal', text: '/*', ignoreCase: false },
>     { type: 'literal', text: '--', ignoreCase: false },
>     { type: 'literal', text: '#', ignoreCase: false },
>     { type: 'literal', text: 'NOT NULL', ignoreCase: true },
>     { type: 'literal', text: 'NULL', ignoreCase: true },
>     { type: 'literal', text: 'DEFAULT', ignoreCase: true },
>     { type: 'literal', text: 'AUTO_INCREMENT', ignoreCase: true },
>     { type: 'literal', text: 'UNIQUE', ignoreCase: true },
>     { type: 'literal', text: 'PRIMARY', ignoreCase: true },
>     {
>       type: 'class',
>       parts: [ ' ', '\t', '\n', '\r' ],
>       inverted: false,
>       ignoreCase: false
>     },
>     { type: 'literal', text: '/*', ignoreCase: false },
>     { type: 'literal', text: '--', ignoreCase: false },
>     { type: 'literal', text: '#', ignoreCase: false },
>     { type: 'literal', text: 'KEY', ignoreCase: true },
>     { type: 'literal', text: 'COMMENT', ignoreCase: true },
>     { type: 'literal', text: 'COLLATE', ignoreCase: true },
>     { type: 'literal', text: 'COLUMN_FORMAT', ignoreCase: true },
>     { type: 'literal', text: 'STORAGE', ignoreCase: true },
>     { type: 'literal', text: 'REFERENCES', ignoreCase: true },
>     { type: 'literal', text: 'ON', ignoreCase: true },
>     { type: 'literal', text: 'CONSTRAINT', ignoreCase: true },
>     {
>       type: 'class',
>       parts: [ ' ', '\t', '\n', '\r' ],
>       inverted: false,
>       ignoreCase: false
>     },
>     { type: 'literal', text: '/*', ignoreCase: false },
>     { type: 'literal', text: '--', ignoreCase: false },
>     { type: 'literal', text: '#', ignoreCase: false },
>     { type: 'literal', text: 'CHECK', ignoreCase: true },
>     { type: 'literal', text: 'CHARACTER', ignoreCase: true },
>     { type: 'literal', text: 'GENERATED', ignoreCase: true },
>     {
>       type: 'class',
>       parts: [ ' ', '\t', '\n', '\r' ],
>       inverted: false,
>       ignoreCase: false
>     },
>     { type: 'literal', text: '/*', ignoreCase: false },
>     { type: 'literal', text: '--', ignoreCase: false },
>     { type: 'literal', text: '#', ignoreCase: false },
>     { type: 'literal', text: 'AS', ignoreCase: true },
>     {
>       type: 'class',
>       parts: [ ' ', '\t', '\n', '\r' ],
>       inverted: false,
>       ignoreCase: false
>     },
>     { type: 'literal', text: '/*', ignoreCase: false },
>     { type: 'literal', text: '--', ignoreCase: false },
>     { type: 'literal', text: '#', ignoreCase: false },
>     { type: 'literal', text: ',', ignoreCase: false },
>     {
>       type: 'class',
>       parts: [ ' ', '\t', '\n', '\r' ],
>       inverted: false,
>       ignoreCase: false
>     },
>     { type: 'literal', text: '/*', ignoreCase: false },
>     { type: 'literal', text: '--', ignoreCase: false },
>     { type: 'literal', text: '#', ignoreCase: false },
>     { type: 'literal', text: ')', ignoreCase: false },
>     {
>       type: 'class',
>       parts: [ ' ', '\t', '\n', '\r' ],
>       inverted: false,
>       ignoreCase: false
>     },
>     { type: 'literal', text: '/*', ignoreCase: false },
>     { type: 'literal', text: '--', ignoreCase: false },
>     { type: 'literal', text: '#', ignoreCase: false },
>     { type: 'literal', text: 'NOT NULL', ignoreCase: true },
>     { type: 'literal', text: 'NULL', ignoreCase: true },
>     { type: 'literal', text: 'DEFAULT', ignoreCase: true },
>     { type: 'literal', text: 'AUTO_INCREMENT', ignoreCase: true },
>     { type: 'literal', text: 'UNIQUE', ignoreCase: true },
>     { type: 'literal', text: 'PRIMARY', ignoreCase: true },
>     {
>       type: 'class',
>       parts: [ ' ', '\t', '\n', '\r' ],
>       inverted: false,
>       ignoreCase: false
>     },
>     { type: 'literal', text: '/*', ignoreCase: false },
>     { type: 'literal', text: '--', ignoreCase: false },
>     { type: 'literal', text: '#', ignoreCase: false },
>     { type: 'literal', text: 'KEY', ignoreCase: true },
>     { type: 'literal', text: 'COMMENT', ignoreCase: true },
>     { type: 'literal', text: 'COLLATE', ignoreCase: true },
>     { type: 'literal', text: 'COLUMN_FORMAT', ignoreCase: true },
>     { type: 'literal', text: 'STORAGE', ignoreCase: true },
>     { type: 'literal', text: 'REFERENCES', ignoreCase: true },
>     { type: 'literal', text: 'ON', ignoreCase: true },
>     { type: 'literal', text: 'CONSTRAINT', ignoreCase: true },
>     {
>       type: 'class',
>       parts: [ ' ', '\t', '\n', '\r' ],
>       inverted: false,
>       ignoreCase: false
>     },
>     { type: 'literal', text: '/*', ignoreCase: false },
>     { type: 'literal', text: '--', ignoreCase: false },
>     { type: 'literal', text: '#', ignoreCase: false },
>     { type: 'literal', text: 'CHECK', ignoreCase: true },
>     { type: 'literal', text: 'CHARACTER', ignoreCase: true },
>     { type: 'literal', text: 'GENERATED', ignoreCase: true },
>     {
>       type: 'class',
>       parts: [ ' ', '\t', '\n', '\r' ],
>       inverted: false,
>       ignoreCase: false
>     },
>     { type: 'literal', text: '/*', ignoreCase: false },
>     { type: 'literal', text: '--', ignoreCase: false },
>     { type: 'literal', text: '#', ignoreCase: false },
>     { type: 'literal', text: 'AS', ignoreCase: true },
>     {
>       type: 'class',
>       parts: [ ' ', '\t', '\n', '\r' ],
>       inverted: false,
>       ignoreCase: false
>     },
>     { type: 'literal', text: '/*', ignoreCase: false },
>     { type: 'literal', text: '--', ignoreCase: false },
>     { type: 'literal', text: '#', ignoreCase: false },
>     { type: 'literal', text: ',', ignoreCase: false },
>     {
>       type: 'class',
>       parts: [ ' ', '\t', '\n', '\r' ],
>       inverted: false,
>       ignoreCase: false
>     },
>     { type: 'literal', text: '/*', ignoreCase: false },
>     { type: 'literal', text: '--', ignoreCase: false },
>     { type: 'literal', text: '#', ignoreCase: false },
>     { type: 'literal', text: ')', ignoreCase: false }
>   ],
>   found: '(',
>   location: {
>     start: { offset: 783, line: 15, column: 108 },
>     end: { offset: 784, line: 15, column: 109 }
>   }
> }
> 
> Node.js v20.3.0

**Comment by taozhi8833998** [comment]
@TonyGravagno please show me the SQL that caused the error.

**Comment by taozhi8833998** [comment]
> This getting this error for MySQL in `4.6.5`.

Sorry for missing the issue, fixed it

**Comment by TonyGravagno** [comment]
For anyone who sees this, the issue I reported here has the same error but not the same cause. The patch for SHOW TABLES does fix the issue for the OP. My issue is not relevant here and can be dismissed.
