### ISSUE TITLE
对mysql中的IF函数的sql解析在某些情况下会报错

### ISSUE THREAD

**Issue by 18742467616** [taozhi8833998/node-sql-parser#805]
**Describe the bug**
对mysql中的IF函数在条件首个为负数时，解析会报错

**Database Engine**
MySQL

**To Reproduce**
-the SQL that be parsed
select a from test where b like IF(-1 = -1, 'a', 'b');
-the node-sql-parser version
3.9.3
-the node version
12.22.6

**Comment by taozhi8833998** [comment]
@18742467616 please upgrade to the `3.9.4` version.
