### ISSUE TITLE
sql在astify和sqlify之后，失去了对特殊字符的转义，可造成sql注入

### ISSUE THREAD

**Issue by 18742467616** [taozhi8833998/node-sql-parser#809]
**Describe the bug**
sql在astify和sqlify之后，失去了对特殊字符的转义，可造成sql注入

**Database Engine**
MySQL

**To Reproduce**
-the SQL that be parsed
select * from test where a='te\'st';
-the node-sql-parser version
3.9.4
-the node version
12.22.6

**Expected behavior**
var mysql = require("mysql");
const { Parser } = require('node-sql-parser/build/mysql');
const parser = new Parser();
var sql = mysql.format("select * from test where a=?",["te'st"]);
var a = parser.astify(sql)
console.log(parser.sqlify(a));
期望能打印出select * from test where a='te\'st'
但是打印出select * from test where a='te'st'
执行sql会报错。希望尽快修复，此bug会造成sql注入。

**Comment by taozhi8833998** [comment]
@18742467616 try the `4.0.0` version
