### ISSUE TITLE
[TSQL] GO syntax

### ISSUE THREAD

**Issue by esetnik** [taozhi8833998/node-sql-parser#817]
**Describe the bug**
Support GO syntax

**Database Engine**
mssql

**To Reproduce**
-the SQL that be parsed
```sql
USE [master]
GO
```
-the node-sql-parser version
v3.9.4

-the node version
v14.18.1

**Expected behavior**
No error as this is valid syntax 

**Screenshots**
![image](https://user-images.githubusercontent.com/664434/140525923-38b0293d-95b8-4bc6-ae92-fbb4427655eb.png)

**Additional context**
https://docs.microsoft.com/en-us/sql/t-sql/language-elements/sql-server-utilities-statements-go?view=sql-server-ver15

**Comment by taozhi8833998** [comment]
@esetnik fixed, I will publish a new version later.

**Comment by taozhi8833998** [comment]
@esetnik try the `4.0.0` version
