### ISSUE TITLE
[BigQuery] WITH clause in FROM statement fails

### ISSUE THREAD

**Issue by pietermees** [taozhi8833998/node-sql-parser#819]
**Describe the bug**
Parsing a SQL statement that has a `WITH` clause in the `FROM` expression fails with the following error:
```
[SyntaxError]: Expected "#", "(", "--", "/*", "SELECT", or [ \t\n\r] but "W" found.
```

**Database Engine**
BigQuery

**To Reproduce**
```
SELECT * FROM (
    WITH temp AS (
        SELECT * FROM test
    )
    SELECT * FROM temp
)
```
node-sql-parser 3.9.4
Node v16.11.1

**Expected behavior**
Expect valid SQL statements to successfully parse.

**Comment by taozhi8833998** [comment]
@pietermees Sorry for the late reply, it has been fixed in the `4.0.0` version.
