### ISSUE TITLE
BigQuery: parser breaks with unnest in a "from" clause that also involves regular tables

### ISSUE THREAD

**Issue by joffreyvillard** [taozhi8833998/node-sql-parser#824]
**Describe the bug**

The parser raises a syntax error on the query below while it is valid.

```
SELECT *
FROM product.organization, unnest(array[1,2])
LIMIT 10
```

A simple select on `unnest` does not raise an error, but creates a `from` element with type `unnest`. Is this expected?

```
SELECT *
FROM unnest(array[1,2])
LIMIT 10
```

**Database Engine**
BigQuery

**To Reproduce**
-the SQL that be parsed: see above
-the node-sql-parser version: 3.9.4
-the node version: 14.15.5

**Expected behavior**
 No error, and the appropriate properties being filled up in the AST.

**Comment by taozhi8833998** [comment]
@joffreyvillard try the `4.0.0` version

**Comment by joffreyvillard** [comment]
Confirmed for this issue and the previously reported ones, thanks!
