### ISSUE TITLE
Does not support Postgres syntax of $<field>

### ISSUE THREAD

**Issue by joshstevens19** [taozhi8833998/node-sql-parser#831]
Thanks for the great lib! just seeing an issue with Postgres support

Does not support Postgres syntax of `$<field>`; aka

does not work:
```
SELECT * FROM table WHERE comment_id = $<fieldId>;
```

works: 
```
SELECT * FROM table  WHERE comment_id = $1;
```

**Database Engine**

PostgreSQL.

```ts
 const ast = parser.astify('SELECT * FROM table WHERE comment_id = $<fieldId>;', {
    database: 'postgresql',
  });
 ```

Error: 

C:\Users\taozhi\learning\node-sql-parser\pegjs\postgresql.pegjs:3437
    return new peg$SyntaxError(
           ^
u [SyntaxError]: Expected "+", "-", [0-9], or [A-Za-z_] but "<" found.

**Expected behavior**
It to behave as it would when using $1 as both valid syntaxes to use with parameters

**Comment by taozhi8833998** [comment]
@joshstevens19 fixed in the `4.0.0` version.
