### ISSUE TITLE
Anyway to Ignore few queries / keywords

### ISSUE THREAD

**Issue by kalidas3** [taozhi8833998/node-sql-parser#832]
I'm trying to use this parser to parse spark SQL.
The below given query is valid only but throws an error.
`select last(col) FROM VALUES(10),(5),(20) AS tab(col)`

Database Engine
MySQL

To Reproduce
-the node-sql-parser version: 4.0.1
-the node version: 16.13.0

If there's a way to ignore those queries or validation success, then it would work.
Thanks in advance

**Comment by taozhi8833998** [comment]
@kalidas3 You using MySQL as the option to parse this SQL?

**Comment by kalidas3** [comment]
> @kalidas3 You are using MySQL as the option to parse this SQL?

@taozhi8833998 Yes I am using MySQL.

**Comment by taozhi8833998** [comment]
> > @kalidas3 You are using MySQL as the option to parse this SQL?
> 
> @taozhi8833998 Yes I am using MySQL. - [Spark Reference Link](https://spark.apache.org/docs/latest/api/sql/index.html#last)

it not supported in [MySQL](https://dev.mysql.com/doc/refman/8.0/en/values.html)

**Comment by kalidas3** [comment]
@taozhi8833998 Thanks for quick response.
Yes. Is there any way to Ignore validation.
 
Like we have parser.whiteListCheck function 
`const whiteKeywordList = ['last', 'first'] // array that contain multiple authorities
const opt = {
  database: 'MySQL',
  type: 'keywords',
}
// opt is optional
parser.whiteListCheck(sql, whiteKeywordList, opt)`

or any other way to Ignore validation also fine.

**Comment by taozhi8833998** [comment]
> @taozhi8833998 Thanks for quick response. Yes. Is there any way to Ignore validation?.
> 
> Like we have parser.whiteListCheck function `const whiteKeywordList = ['last', 'first'] // array that contain multiple authorities const opt = { database: 'MySQL', type: 'keywords', } // opt is optional parser.whiteListCheck(sql, whiteKeywordList, opt)`
> 
> or any other way to achieve this?

The keywords are MySQL reversed words? I can't get the keyword checking in ur example, the "last" and "first".
