### ISSUE TITLE
Syntax error on certain query

### ISSUE THREAD

**Issue by ghostoy** [taozhi8833998/node-sql-parser#846]
**Describe the bug**
Some SQL throws syntax error

**Database Engine**
MySQL

**To Reproduce**
- SQL
  ```sql
  SELECT IF((`open_time` <= UNIX_TIMESTAMP()) AND (`close_time` > UNIX_TIMESTAMP()), 1, 0) FROM sometable
  ```
- the node-sql-parser version
`4.0.0`
- the node version
`14`

**Expected behavior**
Should be valid without error

This statement can get passed if wrapped the `if` statement with a parentheses like:
```sql
  SELECT IF(((`open_time` <= UNIX_TIMESTAMP()) AND (`close_time` > UNIX_TIMESTAMP())), 1, 0) FROM sometable
  ```

**Screenshots**
No

**Additional context**
No

**Comment by taozhi8833998** [comment]
@ghostoy fixed in `4.0.1`
