### ISSUE TITLE
PostgreSQL: parse fails with cast operator and some combination of parens

### ISSUE THREAD

**Issue by joffreyvillard** [taozhi8833998/node-sql-parser#852]
**Describe the bug**
The parser fails on the query below (similar cases can happen with complex calculations), while being valid:

```sql
select (2)::float/(3)::float
```

Note that both queries below are well parsed:

Parens in numerator only:

```sql
select (2)::float/3::float
```

Parens in denominator only:

```sql
select 2::float/(3)::float
```

**Database Engine**
PostgreSQL

**To Reproduce**
-the SQL that be parsed: see above
-the node-sql-parser version: 4.0.1
-the node version: 14.15.5

**Expected behavior**
 No error, and the appropriate properties being filled up in the AST.

**Comment by taozhi8833998** [comment]
@joffreyvillard fixed
