### ISSUE TITLE
Hive RLIKE function support

### ISSUE THREAD

**Issue by DmitryKovganov** [taozhi8833998/node-sql-parser#857]
**Describe the bug**
Doesn't support Hive syntax of RLIKE which is an advanced version of LIKE operator for regular expression searches.

**Database Engine**
Hive

**To Reproduce**
```
select emp_id,name,email_id
from emp_info
where email_id RLIKE '^([0-9]|[a-z]|[A-Z])';
```
or
```
parser.astify(`select emp_id,name,email_id
from emp_info
where email_id RLIKE '^([0-9]|[a-z]|[A-Z])'`, { database: 'hive' });
```

-the node-sql-parser version
4.0.1
-the node version
v16.13.0

**Expected behavior**
Should work exactly the same as LIKE. 
Should work with NOT (NOT RLIKE).
It is not necessary to add validation to the regular expression. If it's not difficult to do then it will be great.
Call of _astify_ should not return error, it should return right AST. For the query from "To Reproduce" it should be something like this:
```
{
    "type": "binary_expr",
    "operator": "RLIKE",
    "left": {
      "type": "column_ref",
      "table": null,
      "column": "email_id"
    },
    "right": {
      "type": "string",
      "value": "^([0-9]|[a-z]|[A-Z])"
    }
  }
```

**Additional context**
Link with RLIKE examples https://www.revisitclass.com/hadoop/rlike-regular-expression-function-in-hive-with-examples/

**Comment by taozhi8833998** [comment]
@DmitryKovganov I will support it today.

**Comment by taozhi8833998** [comment]
@DmitryKovganov it has been supported, I will publish a new version this week.

**Comment by DmitryKovganov** [comment]
@taozhi8833998 wow how fast. Thanks a lot

**Comment by taozhi8833998** [comment]
@DmitryKovganov try the `4.0.2` version, support `rlike` and `not rlike` in hive.
