### ISSUE TITLE
[TSQL] - Support EXEC

### ISSUE THREAD

**Issue by esetnik** [taozhi8833998/node-sql-parser#859]
**Describe the bug**
https://docs.microsoft.com/en-us/sql/t-sql/language-elements/execute-transact-sql?view=sql-server-ver15

**Database Engine**
mssql

**To Reproduce**
-the SQL that be parsed
```sql
/* Delete Database Backup and Restore History from MSDB System Database */
EXEC msdb.dbo.sp_delete_database_backuphistory @database_name = N'Test'
GO
```

-the node-sql-parser version
v4.0.0
-the node version

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/664434/144443013-3ba5b2bd-0773-47ba-9d37-76ee68ea7721.png)

**Additional context**

**Comment by taozhi8833998** [comment]
@esetnik try the `4.0.3` version.
