### ISSUE TITLE
BigQuery: unsupported `pivot` clause

### ISSUE THREAD

**Issue by joffreyvillard** [taozhi8833998/node-sql-parser#873]
**Describe the bug**

The parser raises a syntax error on the query below (using the `pivot` clause, see https://cloud.google.com/bigquery/docs/reference/standard-sql/query-syntax#pivot_operator) while it is valid.

```
select *
from by_plan pivot (sum(cnt) for plan in ('FREE','STARTER', 'PRO'))
```

**Database Engine**
BigQuery

**To Reproduce**
-the SQL that be parsed: see above
-the node-sql-parser version: 4.0.2
-the node version: 14.15.5

**Expected behavior**
 No error, and the appropriate properties being filled up in the AST.

**Comment by joffreyvillard** [comment]
Hi @taozhi8833998 
Do you plan to fix this bug in an upcoming release?
Thanks in advance!

**Comment by taozhi8833998** [comment]
> Hi @taozhi8833998 Do you plan to fix this bug in an upcoming release? Thanks in advance!

@joffreyvillard Sorry for the late reply. I have fixed it, you can get it in the next version.

**Comment by joffreyvillard** [comment]
Great, thanks!
