### ISSUE TITLE
Hive "==" operator support

### ISSUE THREAD

**Issue by DmitryKovganov** [taozhi8833998/node-sql-parser#882]
**Describe the bug**
Doesn't support Hive syntax of "==" which is synonym for the "=" operator.

**Database Engine**
Hive

**To Reproduce**
-the SQL that be parsed
```
select * from some_table where column1 == 'value'
```
-the node-sql-parser version
4.0.3
-the node version
v16.13.0

**Expected behavior**
Should work exactly the same as "=".

**Additional context**
https://cwiki.apache.org/confluence/display/Hive/LanguageManual+UDF#LanguageManualUDF-RelationalOperators

**Comment by taozhi8833998** [comment]
@DmitryKovganov fixed, I will publish new version this week.

**Comment by taozhi8833998** [comment]
@DmitryKovganov try the `4.0.4` version
