### ISSUE TITLE
Hive access array element by index (A[n]) support

### ISSUE THREAD

**Issue by DmitryKovganov** [taozhi8833998/node-sql-parser#891]
**Describe the bug**
Doesn't support Hive syntax of access array element by index

**Database Engine**
Hive

**To Reproduce**
-the SQL that be parsed
```
select some_array[0] from some_table;
```
-the node-sql-parser version
4.0.3
-the node version
v16.13.0

**Expected behavior**
Should support A[n] syntax, where A is an Array and n is an int. n - int is ideal case, but a temporary fix with support for square brackets syntax should be enough to start. 

**Additional context**
"Operators on Complex Types" section https://cwiki.apache.org/confluence/display/Hive/Tutorial

**Comment by taozhi8833998** [comment]
@DmitryKovganov try the `4.0.4` version
