### ISSUE TITLE
Hive access array element by index not fully supported 

### ISSUE THREAD

**Issue by DmitryKovganov** [taozhi8833998/node-sql-parser#894]
**Describe the bug**
According to #891, now we can get the value of the i-th element of array. This value can has different types, such as a string or an object. Various actions are expected to be performed on them. For example, call a function with this value as a parameter, or get the value of an object's property, or both at the same time. But now this cannot be done. 

**Database Engine**
Hive

**To Reproduce**
-the SQL that be parsed
1) call function with element value
```
select lower(some_array[0]) from some_table;
```
2) get the value of an object's property
```
select some_array[0].some_prop from some_table;
```
3) both cases
```
select lower(some_array[0].some_prop) from some_table;
```
-the node-sql-parser version
4.0.4
-the node version
v16.13.0

**Expected behavior**
Pass the test cases above.

**Comment by taozhi8833998** [comment]
@DmitryKovganov Sorry for that, try the `4.0.5` version.

**Comment by DmitryKovganov** [comment]
@taozhi8833998 very fast as always. Thank you very much, I will check.
