### ISSUE TITLE
Parser转换后总是大写的，会把select转换为SELECT， 可以保持不变么

### ISSUE THREAD

**Issue by queenlixiaoman** [taozhi8833998/node-sql-parser#896]
**Describe the bug**
select  * where  'name' = '2222'  

parser后变为

SELECT * WHERE   'name' = '2222'

期望变为

 select  * where  'name' = '2222'  

**Database Engine**
which database engine does your SQL running on? such as MySQL, PostgreSQL.

**To Reproduce**
-the SQL that be parsed
-the node-sql-parser version
-the node version

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by taozhi8833998** [comment]
@queenlixiaoman Uppercase the reserved words and keywords are more readable. You can easily separate the keywords from table and column names, etc. BTW, the SQL in the official document of MySQL is in the same way, [read more](https://dev.mysql.com/doc/refman/8.0/en/select.html)

![image](https://user-images.githubusercontent.com/7252180/149050832-c1971be2-b551-4880-b4a1-a1844f301d98.png)

**Comment by LeeLejia** [comment]
@taozhi8833998 转大写可以提供选项吗，特别是做为 column 的表达式。比如  select count(1) from xx;

在一些 orm 实现返回结构可能是  { 'count(1)': 7 }，这时候因为被转换成大写，导致无法取到值。
