### ISSUE TITLE
MySql/PostgreSql need some function parse support

### ISSUE THREAD

**Issue by tweet** [taozhi8833998/node-sql-parser#904]
**Describe the bug**
MySql/PostgreSql need support `trim ... from` function.
And some join problems if `on` or `and` clause use some function. 

**Database Engine**
MySQL, PostgreSQL.

**To Reproduce**
-the SQL that be parsed
```sql
SELECT TRIM( '.' from "....test.....") AS TrimmedString;
```

```sql
select * from pg_database a 
join pg_database b 
on upper(a.datctype) = upper(b.datctype)
AND a.oid = b.oid
```
or
```sql
select * from pg_database a 
join pg_database b 
on  a.oid = b.oid
and upper(a.datctype) = upper(b.datctype)
```
-the node-sql-parser version
4.0.6
-the node version
12.18.13

**Expected behavior**
should parse correctly.

**Current output**
1.
`Line 1, column 18: Expected "!=", "#", "%", "&&", ")", "*", "+", ",", "-", "--", "/", "/*", "<", "<=", "<>", "=", ">", ">=", "AND", "BETWEEN", "COLLATE", "IN", "IS", "LIKE", "NOT", "OR", "REGEXP", "RLIKE", "div", "\|\|", or [ \t\n\r] but "f" found.`
2.
`Line 4, column 1: Expected "!=", "#", "%", "*", "+", ",", "-", "--", "/", "/*", ";", "<", "<=", "<>", "=", ">", ">=", "FOR", "FULL", "GO", "GROUP", "HAVING", "INNER", "JOIN", "LEFT", "LIMIT", "ON", "ORDER", "OVER", "RIGHT", "UNION", "WHERE", "WINDOW", "div", [ \t\n\r], or end of input but "A" found.`

**Additional context**

**Comment by taozhi8833998** [comment]
@tweet Please upgrade to the `4.0.7` version, and try again.

**Comment by taozhi8833998** [comment]
@tweet Close the issue. You can reopen it if it has not been fixed.
