### ISSUE TITLE
the parser can not support presto sql format like "timestamp businessBeginTime - interval '3' day"

### ISSUE THREAD

**Issue by aajcx** [taozhi8833998/node-sql-parser#907]
**Describe the bug**
the parser can not support presto sql format like "timestamp businessBeginTime - interval '3' day"

**Database Engine**
hive

**To Reproduce**
-the SQL that be parsed
SELECT
     id
   from
     origindb.grocerystockjudg_judgment_stock0_sharding__judgment_bill
   WHERE
     _update_timestamp >= timestamp businessBeginTime - interval '3' day

-the node-sql-parser version
3.9.2

-the node version
10.16.0

**Expected behavior**
the parser can support presto sql format like "timestamp businessBeginTime - interval '3' day"

**Screenshots**
![image](https://user-images.githubusercontent.com/15937836/149905003-d0fb6557-1ac3-4ffa-b847-3a662e2f0c5f.png)

**Additional context**

**Comment by taozhi8833998** [comment]
@aajcx  It would be much more clearly if you can explain the meaning of the `timestamp businessBeginTime - interval '3' day` expression

**Comment by aajcx** [comment]
> @aajcx It would be much more clearly if you can explain the meaning of the `timestamp businessBeginTime - interval '3' day` expression

please kindly refer to the following doc:
https://prestodb.io/docs/current/functions/datetime.html

**Comment by taozhi8833998** [comment]
> > @aajcx It would be much more clearly if you can explain the meaning of the `timestamp businessBeginTime - interval '3' day` expression
> 
> please kindly refer to the following doc: https://prestodb.io/docs/current/functions/datetime.html

Thank you for the doc, I will check it and fix the issue asap.

**Comment by aajcx** [comment]
> > > @aajcx It would be much more clearly if you can explain the meaning of the `timestamp businessBeginTime - interval '3' day` expression
> > 
> > 
> > please kindly refer to the following doc: https://prestodb.io/docs/current/functions/datetime.html
> 
> Thank you for the doc, I will check it and fix the issue asap.

thank you bro.

**Comment by taozhi8833998** [comment]
@aajcx please upgrade the package version to `4.0.8`, and try again.
