### ISSUE TITLE
Stringify wrongly glues "distinct" and "case"

### ISSUE THREAD

**Issue by joffreyvillard** [taozhi8833998/node-sql-parser#937]
**Describe the bug**

The query below when parsed-then-stringified leads to some invalid SQL, due to "distinct" and "case" being glued together:

Original query
```
select count (
  distinct (
    case
      when order_purchase_timestamp between '2018-01-01' and '2018-12-31' then order_id
    end
  )
) as nb_orders
from retail.orders
```

Generated SQL (astify + stringify):
```
SELECT COUNT(DISTINCTCASE WHEN order_purchase_timestamp BETWEEN '2018-01-01' AND '2018-12-31' THEN order_id END) AS nb_orders FROM retail.orders
```

**Database Engine**
BigQuery

**To Reproduce**
-the SQL that be parsed: see above
-the node-sql-parser version: 4.0.2
-the node version: 14.15.5

**Expected behavior**
 Valid BigQuery being generated by stringify.

**Comment by taozhi8833998** [comment]
@joffreyvillard upgrade to `4.1.0`, and try again
