### ISSUE TITLE
Doesn't recognize dollar-quoted strings in Postgres

### ISSUE THREAD

**Issue by acarl005** [taozhi8833998/node-sql-parser#963]
**Describe the bug**

[Dollar-quoted strings](https://www.postgresql.org/docs/current/sql-syntax-lexical.html#SQL-SYNTAX-DOLLAR-QUOTING) cause a syntax error, when they should be recognized as string literals.

**Database Engine**

PostgreSQL

**To Reproduce**

- SQL that be parsed: `SELECT $$foo bar$$;`
- node-sql-parser version: 4.1.1
- node version: v17.5.0

**Expected behavior**

The parser should parse this as a literal string constant.

**Comment by acarl005** [comment]
I'm happy to attempt to submit a PR if you are open to supporting this.

**Comment by taozhi8833998** [comment]
> I'm happy to attempt to submit a PR if you are open to supporting this.

Happy to hear that, I have fixed the issue. You can try to open pr for another issue. Thanks for your kind heart.

**Comment by acarl005** [comment]
Awesome! Thanks!
