### ISSUE TITLE
[MySQL]: Error parsing `CREATE VIEW` query

### ISSUE THREAD

**Issue by tbantle22** [taozhi8833998/node-sql-parser#965]
Describe the bug
Should parse `CREATE VIEW` query. MySQL docs: https://dev.mysql.com/doc/refman/8.0/en/create-view.html

Database Engine
which database engine does your SQL running on? such as MySQL, PostgreSQL.
MySQL

To Reproduce
-the SQL that be parsed
-the node-sql-parser version ^4.1.1"
-the node version

```
query: CREATE VIEW test AS SELECT * FROM `tablename` LIMIT 200;

error: SyntaxError: Expected "#", "--", "/*", ":=", "=", "DATABASE", "FULLTEXT", "INDEX", "SCHEME", "SPATIAL", "TABLE", "TEMPORARY", "UNIQUE", or [ \t\n\r] but "V" found. 
```

**Comment by taozhi8833998** [comment]
@tbantle22 I have supported it in the `4.2.0`, try it.

**Comment by tbantle22** [comment]
Works now, thanks!
