### ISSUE TITLE
[PG] Unable to nest other statments into Common Table Expression (`WITH` clause)

### ISSUE THREAD

**Issue by acarl005** [taozhi8833998/node-sql-parser#967]
**Describe the bug**

According to the [Postgres SQL Grammar](https://www.postgresql.org/docs/14/sql-select.html), you can nest an `UPDATE`, `DELETE`, `INSERT`, or `VALUES` list inside the `WITH` clause of a `SELECT` statement. These types of queries are causing syntax errors.

```
SyntaxError: Expected "(", "--", "/*", "SELECT", "WITH", or [ \t\n\r] but "I" found.
```

**Database Engine**

PostgreSQL

**To Reproduce**

- the SQL that be parsed

```sql
CREATE TABLE stuff(id SERIAL PRIMARY KEY, name VARCHAR);

WITH new_stuff AS (
    INSERT INTO stuff (name) VALUES ('foo'), ('bar') RETURNING id
)
SELECT id
FROM new_stuff;
```

- the node-sql-parser version: 4.1.1
- the node version: v17.5.0

**Expected behavior**

The statement should be correctly parsed.

**Comment by taozhi8833998** [comment]
@acarl005 fixed in the newer version, upgrade to `4.2.0`, try again.
