### ISSUE TITLE
MySQL TIMESTAMPDIFF, TIMESTAMPADD unit argument becomes marked with identifier quote characters.

### ISSUE THREAD

**Issue by kryo2k** [taozhi8833998/node-sql-parser#969]
**Describe the bug**
When parsing a statement with a `TIMESTAMPDIFF` or `TIMESTAMPADD` function, the unit argument gets wrapped in identifier quote characters ( ` ). This ends up causing mysql to throw a syntax error (1064). This seems to happen regardless of being used as a projection of the selection or as part of the where filter.

**Database Engine**
MySQL 8.0.28

**To Reproduce**

Example 1:

```mysql
SELECT TIMESTAMPDIFF(SECOND,"2003-05-01 12:05:55","2003-05-01 12:06:32")
```

Example 2:
```mysql
SELECT * FROM `TEST` WHERE TIMESTAMPDIFF(SECOND,`A`,`B`) > 10
```

Example 3:
```mysql
DELETE FROM `TEST` WHERE TIMESTAMPDIFF(SECOND,`A`,`B`) > 10
```

Example 4:
```mysql
SELECT TIMESTAMPADD(MINUTE,1,"2003-01-02")
```

-the node-sql-parser version
```4.1.1```
-the node version
```v14.16.1```

**Expected behavior**
Expected the unit argument to remain unwrapped as it was input initially.

**Additional context**
Here's a quick nodeJS example to recreate the issue:

```javascript
const
{ Parser } = require('node-sql-parser'),
sqlParser = new Parser(),
testSQL = 'SELECT TIMESTAMPDIFF(SECOND,"2003-05-01 12:05:55","2003-05-01 12:06:32")';

console.log(sqlParser.sqlify(sqlParser.astify(testSQL)));

// outputs:
// SELECT TIMESTAMPDIFF(`SECOND`, '2003-05-01 12:05:55', '2003-05-01 12:06:32')

// MySQL Error:
// Error Code: 1064. You have an error in your SQL syntax; check the manual that
// corresponds to your MySQL server version for the right syntax to use near
// '`SECOND`, '2003-05-01 12:05:55', '2003-05-01 12:06:32')' at line 1
```

**Comment by taozhi8833998** [comment]
@kryo2k please upgrade to  the `4.2.0`.

**Comment by kryo2k** [comment]
Worked like a charm. Tyvm @taozhi8833998.
