### ISSUE TITLE
Postgres "on conflict do nothing"

### ISSUE THREAD

**Issue by vincenzon** [taozhi8833998/node-sql-parser#974]
This postgres specific phrase `on conflict do nothing` for an insert results in a syntax error: 

```
insert into t1 (c1, c2) values (1, 2) on conflict do nothing;
```

Postgres docs: https://www.postgresql.org/docs/9.5/sql-insert.html

**Comment by taozhi8833998** [comment]
@vincenzon it's supported in the latest version.
