### ISSUE TITLE
MySQL/MariaDB query with POSITION function call throws a SyntaxError exception.

### ISSUE THREAD

**Issue by kryo2k** [taozhi8833998/node-sql-parser#990]
**Describe the bug**
When parsing a SQL statement with a call to [POSITION](https://dev.mysql.com/doc/refman/8.0/en/string-functions.html#function_position) function, the parser throws a SyntaxError exception.

Exception message thrown:

```
Expected "#", "$", "'", "(", "--", "/*", "@", "@@", "X", "\"", or [ \t\n\r] but "`" found.
```

Attached [full output of error](https://github.com/taozhi8833998/node-sql-parser/files/8319644/full_output.txt).

**Database Engine**
`MySQL`

**To Reproduce**

-the SQL that be parsed

**Example 1.**

```mysql
SELECT * FROM `tableName` WHERE POSITION('\n' IN `largeText`) > 0;
```

**Example 2.**

```mysql
SELECT POSITION('\n' IN `largeText`) AS `charPosition` FROM `tableName`;
```

**Example 3.**

```mysql
SELECT POSITION('\n' IN `largeText`) FROM `tableName`;
```

-the node-sql-parser version

`4.2.0`

-the node version

`v14.16.1`

**Expected behavior**
Expected parse not to throw SyntaxError exception on call to `astify`, and properly put query back together again when calling `sqlify`.

**Comment by taozhi8833998** [comment]
@kryo2k fixed.

**Comment by kryo2k** [comment]
@taozhi8833998 Thank you!
