### ISSUE TITLE
MySQL/MariaDB query with CAST AS TIME(6) function returns invalid SQL syntax.

### ISSUE THREAD

**Issue by kryo2k** [taozhi8833998/node-sql-parser#991]
**Describe the bug**
The type parameters of [CAST](https://dev.mysql.com/doc/refman/8.0/en/cast-functions.html#function_cast) function call become incorrectly formatted after calling `sqlify` and lead to MySQL syntax error (1064). It seems to only happen when it's a single argument to type. So far, multiple arguments do format properly.

**Database Engine**
MySQL/MariaDB

**To Reproduce**
-the SQL that be parsed

**Example 1. ❌**
```mysql
SELECT CAST('12:31:41.8418443' AS TIME(6)) AS `time`;
-- Becomes: SELECT CAST('12:31:41.8418443' AS TIME6) AS `time`
```

**Example 2. ❌**
```mysql
SELECT CAST('2000-01-01 12:31:41.8418443' AS DATETIME(6)) AS `datetime`;
-- Becomes: SELECT CAST('2000-01-01 12:31:41.8418443' AS DATETIME6) AS `datetime`
```

**Example 3. ✅**
```mysql
SELECT CAST('52.183' AS DECIMAL(15,3)) AS `decimal`;
-- Becomes: SELECT CAST('52.183' AS DECIMAL(15, 3)) AS `decimal`
```

-the node-sql-parser version

`4.2.0`

-the node version

`v14.16.1`

**Expected behavior**
Expected call to `sqlify` to return the parsed object back to correct CAST syntax.

**Comment by taozhi8833998** [comment]
@kryo2k fixed it, I will publish a new version this week.

**Comment by kryo2k** [comment]
@taozhi8833998 Thank you!

**Comment by taozhi8833998** [comment]
@kryo2k please upgrade to `4.3.0`
